sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Number_of_Overdue_Billing_Accounts_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Overdue Billing Accounts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overdue_Balance_All_Accounts__c</fullName>
        <label>Overdue Balance All Accounts</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Balance__c</fullName>
        <description>Sum of the Balance per Billing Account</description>
        <label>Balance Owing All Accounts</label>
        <summarizedField>Billing_Account__c.Balance__c</summarizedField>
        <summaryForeignKey>Billing_Account__c.Customer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Bill_Due_Date__c</fullName>
        <label>Current Bill Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OverdueFlags__c</fullName>
        <formula>IF(( Overdue_Amount_Formula__c  &gt; 0),1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OverdueFlags</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overdue_Amount_Formula__c</fullName>
        <formula>IF(
	OR(Balance__c &lt;= 0, Is_Payment_Plan__c=TRUE, Direct_Debit__c=TRUE, Recovery_Suspended_Date__c &gt;= TODAY())
	, 0
	, IF(Balance__c &lt;= Current_Bill_Billed_Amount__c
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
			, Balance__c
			, 0)
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
				, Balance__c
				, IF(Balance__c &lt; Current_Bill_B_F_Balance__c
					,Balance__c
					,Current_Bill_B_F_Balance__c)
				)
			
		)
	)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/BillingComputeOverdueManual.cls
/*
    Type:       Trigger class
    Purpose:    class that will be used to compute the Billing OverdueAmount manually 

    Used By:    Billing Account Standard page    
    ---------------------------------------------------------------
    History:

    27/09/2012 J.Jayoma (Cloud Sherpas)   Created - for TP# 396  compute the Billing OverdueAmount manually
    24/02/2014 ejandusay(Cloud Sherpas)   Moved Test methods in a separate test class  
  
*/


public class BillingComputeOverdueManual {
    public BillingComputeOverdueManual(){
        
    }
    
    public void computeForOverdue(List<Billing_Account__c> billingAccountList){
        set<Id> accId = new set<Id>();  
        List<Account> accList = new List<Account>();
        
        for(Billing_Account__c billingAccount: billingAccountList){
            accId.add(billingAccount.customer__c);
        }   
        
        Map<Id,Double> overdueMap = new Map<Id,Double>();
        Map<Id,Double> totalNumberOfOverdueMap = new Map<Id,Double>(); 
        system.debug('@accId'+accId);
        for(Billing_Account__c b:[Select Id,Overdue_Amount_Formula__c,Current_Bill_Due_Date__c,Balance__c, customer__c,OverdueFlags__c from Billing_Account__c where customer__c in:accId]){ 
            
            // For 396 additional requiremenents compute for Number_of_Overdue_Billing_Accounts_Total__c                            
            
                if(overdueMap.containsKey(b.customer__c))
                {
                    Double a= overdueMap.get(b.customer__c);
                    overdueMap.put(b.customer__c, a+b.Overdue_Amount_Formula__c); 
                
                }
                else
                {
                    overdueMap.put(b.customer__c, b.Overdue_Amount_Formula__c);
                
                }
            
                if(totalNumberOfOverdueMap.containsKey(b.customer__c)){
                    Double a = totalNumberOfOverdueMap.get(b.customer__c);
                    totalNumberOfOverdueMap.put(b.customer__c,a+b.OverdueFlags__c);
                }
                else{
                    totalNumberOfOverdueMap.put(b.customer__c,b.OverdueFlags__c);
                }
        }      
                
        
        // Loop the account to batch update the Overdue_Balance_All_Accounts__c
        for(Account acc:[Select Total_Balance__c,Overdue_Balance_All_Accounts__c,Number_of_Overdue_Billing_Accounts_Total__c from Account where Id in:totalNumberOfOverdueMap.keySet()]){
            system.debug('@overdueMap.get(acc.Id)'+overdueMap.get(acc.Id));
            acc.Overdue_Balance_All_Accounts__c=overdueMap.get(acc.Id); 
            // added requirements for 396, count the overdues          
            acc.Number_of_Overdue_Billing_Accounts_Total__c = totalNumberOfOverdueMap.get(acc.Id);           
            accList.add(acc);
        }        
        
        system.debug('@accList'+accList);
        // update the account list
        if(accList.size()>0){
            update accList;
        }        
       
    }
   
}