sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <description>Residential customers that have business relationship with SEWL.</description>
        <label>Residential Customer</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <formula>Property__r.CIS_Property_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS Property Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <inlineHelpText>What is the case or activity about?</inlineHelpText>
        <label>What</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Payments &amp; Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Reform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Contact Type</description>
        <inlineHelpText>This field contains information that is parsed to BRE for SMR Cases.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>The first 255 characters of the full description will be automatically copied here.</description>
        <inlineHelpText>If blank , the first 255 characters of the full description will be automatically copied here.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <formula>Property__r.Suburb__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Suburb</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Read__c</fullName>
        <label>Type of Read</label>
        <picklist>
            <controllingField>Contact_Type__c</controllingField>
            <picklistValues>
                <fullName>Tenant Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Reading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification_Code__c.object
<CustomObject>
    <description>Classification codes for customers</description>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description for the customer classification</description>
        <inlineHelpText>Short Description for the customer classification</inlineHelpText>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Classification Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Drivers_License_Number__c</fullName>
        <label>Drivers License Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Customer_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Warnings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <formula>Billing_Account__r.HiAF_Account_Number__c</formula>
        <label>HiAF Account Number</label>
        <type>Text</type>
    </fields>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Livelink__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Livelink Document</label>
    <nameField>
        <label>Filename</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livelink Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <description>Property reference number in HiAF</description>
        <externalId>true</externalId>
        <label>CIS Property Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/QuickViewExCon_TestHelper.cls
/*
    Type:       Test Class
    Purpose:    Quick View Test Coverage

    Used By:    QuickViewExCon
    ---------------------------------------------------------------
    History:

    22-Nov-2012 D.Yu (Cloudsherpas)         Created
*/
@isTest
public class QuickViewExCon_TestHelper {
	//create user
	public static User createUser() {
		 Profile p = [SELECT Id FROM Profile WHERE Name='SEW Administrator'];
		 
		 User u = new User(Alias = 'foobar', Email='foobar@sewl.foo.com',
                        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US', ProfileId = p.Id, isActive = true,
                        TimeZoneSidKey='America/Los_Angeles', UserName='foobar@sewl.foo.com');
         insert u;
         return u;
	}
	
	//create customer record
	public static Account createCustomer(){
        RecordType rt = [Select r.DeveloperName From RecordType r
                            where DeveloperName = 'Residential' and sObjectType = 'Account'];       
        
        Account a 			= new Account();
        a.Name				='Foo';
        a.Account_Name__c	='Foo';
        a.RecordTypeId 		= rt.id;
        
        insert a;
        return a;
	}
	
	//create contact record
	public static Contact createContact(Account a){
		Contact c 					= new Contact();
		c.LastName					= 'Foo';
		c.FirstName					= 'Bar';
		c.BirthDate 				= system.today();
		c.Phone						= '12345';
		c.Drivers_License_Number__c	= '12345';
		c.AccountId 				= a.id;
        
        insert c;
        return c;
	}
	
	//Create Properties
	public static Property__c createProperty(){
		Property__c property 		= new Property__c();
        property.Name 				= 'TestProperty';
        property.Street_Address__c 	= '10 Foo st';
        property.Suburb__c 			= 'Fooville';
        property.CIS_Property_Id__c = '12';
        
        insert property;
        return property;
	}
	
	//create billing account with property
	public static Billing_Account__c createBillingAccount(Account a, Property__c p){
		Billing_Account__c billAcc 		= new Billing_Account__c();
		billAcc.Name 					= '12345';
        billAcc.HiAF_Account_Number__c 	= '12345';
        billAcc.Customer__c 			= a.id;
        billAcc.Property__c 			= p.id;
        
        insert billAcc;
        return billAcc;
	}
	
	//create classification code
	public static Classification_Code__c createClassificationCode(){
		Classification_Code__c code = new Classification_Code__c();
        code.Name 					= 'Test';
        code.Short_Description__c 	= 'Test';
        
        insert code;
        return code;
	}
	
	//create customer classification
	public static Customer_Classification__c createCustomerClassification(Account a, Billing_Account__c b, Classification_Code__c c){
		Customer_Classification__c cc 	= new Customer_Classification__c();
        cc.Customer__c 					= a.id;
        cc.Billing_Account__c 			= b.id;
        cc.Classification__c 			= c.id;
        
        insert cc;
        return cc;
	}
	
	//create case
	public static Case createCase(Account a, Billing_Account__c b, Property__c p){
		RecordType recType = [Select name from RecordType where name='Special Meter Read'];
		
		Case c 					= new Case();
        c.Contact_Type__c		= 'Tenant';
        c.Type_of_Read__c 		= 'Move Out';
        c.Property__c			= p.Id;  
        c.RecordTypeId			= recType.Id;
        c.Billing_Account__c 	= b.Id;
        c.AccountId 			= a.id;
        c.Origin 				= 'Phone';
        
        insert c;
        return c;
	}
	
	//create task
	public static Task createTaskByStatus(Account a, Billing_Account__c b, User u, Contact c, String taskStatus){
		Task taskRec = new Task();
        Id taskId;
        Id recordTypeId = [SELECT name FROM RecordType WHERE name = 'Read Only Tasks' LIMIT 1].Id;
        
        taskRec.Subject = 'Print Bill';
        taskRec.ActivityDate = date.today();
        taskRec.Type = 'Other';
        taskRec.RecordTypeId = recordTypeId;
        taskRec.Description = 'Test';
        taskRec.WhatId = a.Id; 
        taskRec.Status = taskStatus;
        taskRec.Group__c = 'Billing & Accounts';
        taskRec.Category_Level_1__c = 'Billing';
        taskRec.Category_Level_2__c = 'Billing';
        taskRec.Category_Level_3__c = 'Print Bill';
        taskRec.Mode__c = 'Action';
        taskRec.ownerId = u.id;
        
        insert taskRec;
        return taskRec;
	}
	
	//create Livelink Documents
	public static Livelink__c createLivelink(Account a, Billing_Account__c b, Case c, Property__c p){
		Livelink__c ll 			= new Livelink__c();
		ll.Name 				= 'Test';
		ll.Billing_Account__c 	= b.id;
		ll.Customer__c 			= a.id;
		ll.Case__c 				= c.id;
		ll.Property__c 			= p.id;
		
		insert ll;
		return ll;
	}
	
	//create Quick View Callout Custom settings
	public static Quick_View_Callout__c createQuickViewCalloutSetting(){
		Quick_View_Callout__c  qv 	= new Quick_View_Callout__c();
        qv.Name 					= 'Default';
        qv.Visibility__c 			= true;
        qv.on_tab_click__c 			= false;
        
        insert qv;
        return qv;
	}
}