sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <description>Residential customers that have business relationship with SEWL.</description>
        <label>Residential Customer</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <label>State/Postcode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address_Proper__c</fullName>
        <label>Street Address (Proper)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalManageAccountAddress_Controll_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalEnquiriesMyCases_Controller
    ---------------------------------------------------------------
    History:

    26-Feb-2014 G.Tsaousidis					Created
*/
@isTest
private class PortalManageAccountAddress_Controll_Test {

	/* TEST METHODS */
    public static testMethod void PortalManageAccountAddress_Controller_Test() {

        
        // Residential Customer
        Account resCustomer = PortalTestHelper.createResiCustomer();
        resCustomer.BillingStreet = 'resBillingStreet';
        resCustomer.BillingCity = 'resBillingCity';
        resCustomer.BillingState = 'resBillingState';
        resCustomer.BillingPostalCode = '1234';
        resCustomer.BillingCountry = 'resBillingCountry';
        
        resCustomer.ShippingStreet = 'resShippingStreet';
        resCustomer.ShippingCity = 'resShippingCity';
        resCustomer.ShippingState = 'resShippingState';
        resCustomer.ShippingPostalCode = '1234';
        resCustomer.ShippingCountry = 'resShippingCountry';
        update resCustomer;

        Contact c = PortalTestHelper.createContact(resCustomer);
        User user = PortalTestHelper.createUser(c);
        List<Property__c> listProp = PortalTestHelper.createProperties(2, 'zzz');
        listProp[0].Street_Address_Proper__c = 'Street';
        
        List<Billing_Account__c> listBA1 = PortalTestHelper.createBillingAccountsWithProperties(resCustomer, listProp);
    
        Test.startTest();
        System.runAs(user){
            // case 1:  
            PortalManageAccountAddress_Controller con1 = new PortalManageAccountAddress_Controller();
            
            con1.billID = listBA1[0].id;
            con1.address = 'xxx, xxx';
            con1.PopulateDPID();
            String qasiFrameURL = con1.qasiFrameURL;            
            con1.qasiFrameURL = 'www.google.com'; 
            
            con1.listBillingAccountsWrapper[0].billAcct.State__c = '';
            con1.dpid = con1.GetBillingAddressDPID(con1.listBillingAccountsWrapper[0]);     
            con1.listBillingAccountsWrapper[1].billAcct.State__c = 'State';
            con1.dpid = con1.GetBillingAddressDPID(con1.listBillingAccountsWrapper[1]);     
            con1.listBillingAccountsWrapper[0].selectedOption = 'Property';

            con1.saveAccountAddress();            

            System.assertEquals(con1.qasiFrameURL, 'www.google.com');            
            System.assertEquals(con1.dpid, '123456');
        }
        Test.stopTest();
    }
}