sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <description>Residential customers that have business relationship with SEWL.</description>
        <label>Residential Customer</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Same_Name_As_Customer__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Same Name As Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Quick_QoS_Response__c.object
<CustomObject>
    <description>This object is to host Quick Notes responses that are controlled by selection of Categories.</description>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_Code__c</fullName>
        <label>Letter Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_Name__c</fullName>
        <label>Letter Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_1_Category__c</fullName>
        <label>What</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_2_Category__c</fullName>
        <label>Why</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level_3_Category__c</fullName>
        <label>How</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Quick Notes Response</label>
    <nameField>
        <displayFormat>Response-{0000}</displayFormat>
        <label>Quick Notes Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quick_QoS_Response</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/AutoCompleteController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class AutoCompleteController
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class AutoCompleteController_Test {

    /* TEST METHOD */
    static testmethod void test_AutoCompleteController(){
        // create test data
        Account account = new Account();
        account.name = 'foo';
        RecordType rt = [Select id from RecordType where DeveloperName = 'Residential' and SobjectType = 'Account'];
        account.RecordTypeId = rt.id;
        insert account;

        Contact contact = new Contact();
        contact.LastName = 'Foo';
        contact.MobilePhone = '0412345678';
        contact.AccountId = account.id;
        contact.Title = 'x';
        contact.Phone = '0412345678';
        contact.Email = 'x@x.com';
        contact.Birthdate = Date.today();
        insert contact;

        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        insert prop;

        Billing_Account__c billAcc = new Billing_Account__c();
        billAcc.Name = 'asetwetwrt';
        billAcc.Title__c = 'dd';
        billAcc.Initials__c = 'fg';
        billAcc.Account_Name__c = 'hjy';
        billAcc.Same_Name_As_Customer__c = false;
        billAcc.Customer__c = account.id;
        billAcc.Property__c = prop.id;
        billAcc.HiAf_Account_Number__c = '9465494';
        insert billAcc;
        
        Quick_QoS_Response__c response = new Quick_QoS_Response__c();
        response.Level_1_Category__c = 'Test1';
        response.Level_2_Category__c = 'Test2';
        response.Level_3_Category__c = 'Test3';
        response.Response__c = 'TestResponse';
        response.Letter_Name__c = 'TestLetterName';
        response.Letter_Code__c = 'TLC';
        response.Group__c = 'Billing & Accounts';
        insert response;
        
        AutoCompleteController.findSObjects('Quick_QoS_Response__c', 'Test', 'Level_1_Category__c,Level_2_Category__c,Level_3_Category__c', 'Billing & Accounts');          
   }
   //Invalid Object Name
    static testmethod void test_AutoCompleteControllerNOObj(){
        // create test data
        Account account = new Account();
        account.name = 'foo';
        RecordType rt = [Select id from RecordType where DeveloperName = 'Residential' and SobjectType = 'Account'];
        account.RecordTypeId = rt.id;
        insert account;

        Contact contact = new Contact();
        contact.LastName = 'Foo';
        contact.MobilePhone = '0412345678';
        contact.AccountId = account.id;
        contact.Title = 'x';
        contact.Phone = '0412345678';
        contact.Email = 'x@x.com';
        contact.Birthdate = Date.today();
        insert contact;

        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        insert prop;

        Billing_Account__c billAcc = new Billing_Account__c();
        billAcc.Name = 'asetwetwrt';
        billAcc.Title__c = 'dd';
        billAcc.Initials__c = 'fg';
        billAcc.Account_Name__c = 'hjy';
        billAcc.Same_Name_As_Customer__c = false;
        billAcc.Customer__c = account.id;
        billAcc.Property__c = prop.id;
        billAcc.HiAf_Account_Number__c = '9465494';
        insert billAcc;
        
        Quick_QoS_Response__c response = new Quick_QoS_Response__c();
        response.Level_1_Category__c = 'Test1';
        response.Level_2_Category__c = 'Test2';
        response.Level_3_Category__c = 'Test3';
        response.Response__c = 'TestResponse';
        response.Letter_Name__c = 'TestLetterName';
        response.Letter_Code__c = 'TLC';
        response.Group__c = 'Billing & Accounts';
        insert response;
        
        AutoCompleteController.findSObjects('', 'Test', 'Level_1_Category__c,Level_2_Category__c,Level_3_Category__c', 'Billing & Accounts');           
   }
}