sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Overdue_Balance_All_Accounts__c</fullName>
        <label>Overdue Balance All Accounts</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Bill_Due_Date__c</fullName>
        <label>Current Bill Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Overdue_Amount_Formula__c</fullName>
        <formula>IF(
	OR(Balance__c &lt;= 0, Is_Payment_Plan__c=TRUE, Direct_Debit__c=TRUE, Recovery_Suspended_Date__c &gt;= TODAY())
	, 0
	, IF(Balance__c &lt;= Current_Bill_Billed_Amount__c
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
			, Balance__c
			, 0)
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
				, Balance__c
				, IF(Balance__c &lt; Current_Bill_B_F_Balance__c
					,Balance__c
					,Current_Bill_B_F_Balance__c)
				)
			
		)
	)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/BillingBatchOverdueAmount6_Test.cls
/*
    Type:       test class
    Purpose:    test class for  BillingBatchOverdueAmount class 

    Used By:   BillingBatchOverdueAmount class  
    ---------------------------------------------------------------
    History:

    05/09/2012 ICastillo (Cloud Sherpas)   Created    
  
*/
@isTest
private class BillingBatchOverdueAmount6_Test {

    static testMethod void BillingBatchOverdueAmount6() {
        List<Account> accList = new List<Account>(); 
        set<Id> accId = new set<Id>();
        for(Integer i=0; i<102; i++){
            Account acc = new Account(name='test acc'+i);
            accList.add(acc);           
        }
       
        insert accList;
        
         List<Billing_Account__c> bList = new List<Billing_Account__c>(); 
         for(Integer i=0; i < accList.size(); i++){
            Billing_Account__c billAccount = new Billing_Account__c(customer__c = accList[i].Id);
            bList.add(billAccount);
         }   
         insert bList;
        
        // Initialize the BillingBatchOverdueAmount class
        BillingBatchOverdueAmount6 billing = new BillingBatchOverdueAmount6();
        
        // pass a string Billing_Account__c query to the BillingBatchOverdueAmount query method
        billing.query = 'Select Overdue_Amount_Formula__c,Balance__c, Current_Bill_Due_Date__c, customer__c, customer__r.Overdue_Balance_All_Accounts__c from Billing_Account__c';
          
        
        Test.startTest();
        // call and execute the batch job
        ID batchprocessid = Database.executeBatch(billing);
        Test.stopTest();
    }
}