sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>When the Future Address details become applicable</description>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Address_DPID__c</fullName>
        <label>Mailing Address DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_DPID__c</fullName>
        <label>Primary Address DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Billing Account Address</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Billing Account Address</description>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DPID__c</fullName>
        <description>Billing Account Address DPID</description>
        <label>DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Future_Address__c.object
<CustomObject>
    <description>Captures Future Address information</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Customer for which the future address will apply to.</description>
        <inlineHelpText>The Customer for which the future address will apply to.</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Future Addresses</relationshipLabel>
        <relationshipName>Future_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <description>When the Future Address details become applicable</description>
        <label>Applicable Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Future Addresses</relationshipLabel>
        <relationshipName>Future_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Future City to mail to</description>
        <inlineHelpText>Future City to mail to, as per logged request</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Future Country to mail to, as per logged request</description>
        <inlineHelpText>Future Country to mail to</inlineHelpText>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPID__c</fullName>
        <description>Future DPID Reference</description>
        <inlineHelpText>Future DPID Reference</inlineHelpText>
        <label>DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Future Postal Code to mail to, as per logged request</description>
        <inlineHelpText>Future Postal Code to mail to, as per logged request</inlineHelpText>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field to trigger the future address for processing</description>
        <label>Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Future State to mail to, as per logged request</description>
        <inlineHelpText>Future City to mail to</inlineHelpText>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Future Street Address</description>
        <inlineHelpText>Future Street Address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Future Address</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>Future Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>DPID__c</fullName>
        <label>DPID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/Future_Address_Test.cls
/*
    Type:       Test Class
    Purpose:    Test Class for Future_Address.class

    Used By:    Future_Address.class
    ---------------------------------------------------------------
    History:
    24-Feb-2014 - G.Tsaousidis     Created
*/
@isTest
private class Future_Address_Test {

	private static TestMethod void TestMe() {
        Profile p = [select id from profile where name='SEW CSO (Customer Service Officer)'];
                        User u = new User(alias = 'fgjdf', email='dfjdfh@dfhxfgh.com',
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = p.Id,
        timezonesidkey='America/Los_Angeles', username='djgf@hjgfhj.com');
        insert u;

        System.runAs(u) {
            Account a = new Account(name='ABC');
            insert a;

            Future_Address__c fa = new Future_Address__c(account__c = a.id,
                                                            Street_Address__c = '100 ABC ST',
                                                            City__c = 'ABCVILLE',
                                                            State__c = 'ABC',
                                                            Postal_Code__c = '1234',
                                                            Country__c = 'ABCLAND',
                                                            DPID__c = '12345',
                                                            Address_Type__c = 'Mailing',
                                                            Applicable_date__c = system.today().addDays(2));
            insert fa;
            
            Property__c prop = new Property__c();
            prop.Universal_Id_c__c = 'sdgfsdgf';
            prop.Name = 'Test Property';
            insert prop;
    
            Billing_Account__c billAcc = new Billing_Account__c();
            billAcc.Name = 'asetwetwrt';
            billAcc.Customer__c = a.id;
            billAcc.Property__c = prop.id;
            insert billAcc;

            fa.Process__c = true;
            update fa;

            a = [select id, BillingStreet, BillingState, BillingPostalCode, BillingCity, Billing_Address_DPID__c, BillingCountry
                            from Account
                            where id = :a.id][0];
            system.assertequals(a.BillingStreet, fa.street_address__c);
            system.assertequals(a.BillingState, fa.State__c);
            system.assertequals(a.BillingPostalCode, fa.Postal_Code__c);
            system.assertequals(a.BillingCity, fa.City__c);
            
            fa.Address_Type__c = 'Primary';
            update fa;
            
            a = [select id, ShippingStreet, ShippingState, ShippingPostalCode, ShippingCity, Primary_Address_DPID__c, ShippingCountry
                            from Account
                            where id = :a.id][0];
            system.assertequals(a.ShippingStreet, fa.street_address__c);
            system.assertequals(a.ShippingState, fa.State__c);
            system.assertequals(a.ShippingPostalCode, fa.Postal_Code__c);
            system.assertequals(a.ShippingCity, fa.City__c);
            
            fa.Address_Type__c = 'Billing Only';
            fa.Billing_Account__c = billAcc.Id;
            update fa;
            
        }
    }
}