sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Same_As__c</fullName>
        <inlineHelpText>Please set flag None to change address in Billing Account.</inlineHelpText>
        <label>Billing Address Same As</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number_Check_Digit__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account Number (Check Digit)</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad-Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Phone_Type__c</fullName>
        <label>Preferred Phone Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/ECO_Price__c.object
<CustomObject>
    <fields>
        <fullName>ECO_Price__c</fullName>
        <label>ECO Price</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>ECO Prices</relationshipLabel>
        <relationshipName>ECO_Prices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rejected_Reason__c</fullName>
        <label>Rejected Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Too expensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment plant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Happy with septic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer&apos;s age</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday house</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Don&apos;t want to connect early</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>ECO Price</label>
    <nameField>
        <displayFormat>EP-{000000}</displayFormat>
        <label>ECO Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ECO Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/ECOPrice_Trigger_Test.cls
/*
    Type:       Test Class
    Purpose:    
                Performs Testing for ECO Price trigger

    ---------------------------------------------------------------
    History:
	03-Feb-2014	N.Patterson		US554 - Created
*/

@isTest
private class ECOPrice_Trigger_Test {

    static testMethod void testEOIOpptyExists() {
    	
    	// Setup test data
        Account acc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        con.MobilePhone = '0422123456';
        con.Preferred_Phone_Type__c = 'Mobile';
        update con;
        
        Property__c prop = PortalTestHelper.createProperty();
        prop.Postal_Code__c = '3000';
        prop.State__c = 'VIC';
        update prop;
        Meter_Details__c meter = PortalTestHelper.createMeter(prop, 'theMeter');
        Billing_Account__c billAcct = PortalTestHelper.createBillingAccount(acc, prop);
        billAcct.Billing_Address_Same_As__c = 'Property';
        
        update billAcct;
        
        billAcct = [Select id, HiAF_Account_Number_Check_Digit__c, HiAF_Account_Number__c, customer__c, RecordTypeId, role__c, Property__c, account_Name__c, status__c
        			FROM Billing_Account__c
        			WHERE id = :billAcct.id];
        
        Opportunity oppty = new Opportunity();
		oppty.StageName = 'Eligible';
		oppty.name = 'ECO';
		oppty.Type = 'Existing Business';
		oppty.CloseDate = Date.parse('31/12/2032');
		oppty.LeadSource = 'Web';
		oppty.Billing_Account__c = billAcct.Id;
		oppty.AccountId = billAcct.Customer__c;
		insert oppty;
		
		ECO_Price__c ep1 = new ECO_Price__c();
		ep1.ECO_Price__c = 111;
		ep1.Opportunity__c = oppty.id;
		
		ECO_Price__c ep2 = new ECO_Price__c();
		ep2.ECO_Price__c = 222;
		ep2.Opportunity__c = oppty.id;
		
		ECO_Price__c ep3 = new ECO_Price__c();
		ep3.ECO_Price__c = 333;
		ep3.Opportunity__c = oppty.id;
		ep3.Rejected_Reason__c = 'Too expensive';
		
		Test.startTest();
			insert ep1;
			System.assertEquals(111, getOpptyAmount(oppty.Id));
			
			insert ep2;
			System.assertEquals(222, getOpptyAmount(oppty.Id));
			
			insert ep3;
			System.assertEquals(222, getOpptyAmount(oppty.Id));
			
			ep3.Rejected_Reason__c = '';
			update ep3;
			System.assertEquals(333, getOpptyAmount(oppty.Id));
			
			ep2.Rejected_Reason__c = 'Too expensive';
			update ep2;
			//System.assertEquals(333, getOpptyAmount(oppty.Id));
			
			ep3.Rejected_Reason__c = 'Too expensive';
			update ep3;
			System.assertEquals(111, getOpptyAmount(oppty.Id));
			
			delete ep1;
			System.assertEquals(null, getOpptyAmount(oppty.Id));
			
		Test.stopTest();
    }
    
    static Decimal getOpptyAmount(Id opptyId){
    	if(opptyId != null){
    		return [SELECT Id, Amount FROM Opportunity WHERE Id = :opptyId].Amount;
    	}
    	else {
    		return null;
    	}
    }
}