sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>When the Future Address details become applicable</description>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Address_DPID__c</fullName>
        <label>Mailing Address DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_DPID__c</fullName>
        <label>Primary Address DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Same_As__c</fullName>
        <inlineHelpText>Please set flag None to change address in Billing Account.</inlineHelpText>
        <label>Billing Address Same As</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Billing Account Address</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Billing Account Address</description>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPID__c</fullName>
        <description>Billing Account Address DPID</description>
        <label>DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Run_From_Workflow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to prevent trigger runs when update comes from a workflow when applying future addresses</description>
        <label>Run From Workflow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Billing_City__c</fullName>
        <label>(Temp) Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Billing_Country__c</fullName>
        <label>(Temp) Billing Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Billing_Postal_Code__c</fullName>
        <label>(Temp) Billing Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Billing_State__c</fullName>
        <label>(Temp) Billing State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Billing_Street_Address__c</fullName>
        <label>(Temp) Billing Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Future_Address__c.object
<CustomObject>
    <description>Captures Future Address information</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>The Customer for which the future address will apply to.</description>
        <inlineHelpText>The Customer for which the future address will apply to.</inlineHelpText>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Future Addresses</relationshipLabel>
        <relationshipName>Future_Addresses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Type__c</fullName>
        <label>Address Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <description>When the Future Address details become applicable</description>
        <label>Applicable Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account_ID__c</fullName>
        <label>Account</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Future Addresses</relationshipLabel>
        <relationshipName>Future_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Future City to mail to</description>
        <inlineHelpText>Future City to mail to, as per logged request</inlineHelpText>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Future Country to mail to, as per logged request</description>
        <inlineHelpText>Future Country to mail to</inlineHelpText>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPID__c</fullName>
        <description>Future DPID Reference</description>
        <inlineHelpText>Future DPID Reference</inlineHelpText>
        <label>DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Done__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate that the Future Address change is done</description>
        <inlineHelpText>Flag to indicate that the Future Address change is done</inlineHelpText>
        <label>Done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Future Postal Code to mail to, as per logged request</description>
        <inlineHelpText>Future Postal Code to mail to, as per logged request</inlineHelpText>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Hidden field to trigger the future address for processing</description>
        <label>Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Future State to mail to, as per logged request</description>
        <inlineHelpText>Future City to mail to</inlineHelpText>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Future Street Address</description>
        <inlineHelpText>Future Street Address</inlineHelpText>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <label>Future Address</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>Future Address #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Future Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/Future_Address.cls
public without sharing class Future_Address {

/*
    Type:       Utility Class
    Purpose:    ProcessFutureAddress () - updates future address on customer

    Used By:    Future_Address.trigger
    ---------------------------------------------------------------
    History:
        22-Sep-2011 - D.Thong (SFDC)    Created
        17-Aug-2012 - I.Castillo        Added "if" condition for updating mailing or primary address
        05-Sep-2012 - D.Yu (Cloud Sherpas) #TP212 - Added handling on future addresses for billing accounts
        17-Dec-2012 - N.Patterson       Changed to without sharing as a portal user cannot update the Account record
        24-Feb-2012	- G.Tsaousidis		Technical Debt - Moved test methods to Test Class Future_Address_Test
*/

    public static void ProcessFutureAddress(List<Id> futureAddressIds) {
        // 1. select future addresses sorted by account and applicable date
        // 2. update the customer's address
        // 3. Set done flag = 'Y' and process_flag = 'N'

        Map<Id, Account> accounts = new Map<Id, Account>();
        Map<Id, Account> accountsPrimary = new Map<Id, Account>();
        Map<Id, Billing_Account__c> baccounts = new Map<ID, Billing_Account__c>();
        Map<Id, Future_Address__c> faMap = new Map<Id, Future_Address__c>();
        Account acct = new Account();
        Billing_Account__c bacct = new Billing_Account__c();
        
        for (Future_Address__c fa : [select id, account__c, street_address__c, city__c, state__c, postal_code__c, country__c, dpid__c, process__c, done__c, Address_Type__c, 
                                        Billing_Account_ID__c, Billing_Account__c from Future_Address__c
                                        where id in :futureAddressIds
                                        and Process__c = true
                                        order by account__c, applicable_date__c]) {
            if(fa.Address_Type__c == 'Mailing'){
                if(fa.account__c != null){
                    acct = new Account(id=fa.account__c,
                                            BillingStreet=fa.street_address__c,
                                            BillingCity=fa.City__c,
                                            BillingState=fa.State__c,
                                            BillingPostalCode=fa.Postal_Code__c,
                                            BillingCountry=fa.Country__c,
                                            Billing_Address_DPID__c=fa.DPID__c);
                    accounts.put(fa.id, acct);
                }
            }else if(fa.Address_Type__c == 'Primary'){
                if(fa.account__c != null){
                    acct = new Account(id=fa.account__c,
                                            ShippingStreet=fa.street_address__c,
                                            ShippingCity=fa.City__c,
                                            ShippingState=fa.State__c,
                                            ShippingPostalCode=fa.Postal_Code__c,
                                            ShippingCountry=fa.Country__c,
                                            Primary_Address_DPID__c=fa.DPID__c);
                     accountsPrimary.put(fa.id, acct);
                }
            }else if(fa.Address_Type__c == 'Billing Only'){
                if(fa.Billing_Account__c != null){
                    bacct = new Billing_Account__c(id=fa.Billing_Account__c,
                                                    Street_Address__c = fa.street_address__c,
                                                    City__c = fa.City__c,
                                                    State__c = fa.State__c,
                                                    Postal_Code__c = fa.Postal_Code__c,
                                                    Country__c = fa.Country__c,
                                                    DPID__c = fa.DPID__c,
                                                    Billing_Address_Same_As__c = 'Other',
                                                    run_from_workflow__c = true,
                                                    Temp_Billing_City__c = fa.City__c,
                                                    Temp_Billing_State__c = fa.State__c,
                                                    Temp_Billing_Postal_Code__c = fa.Postal_Code__c,
                                                    Temp_Billing_Country__c = fa.Country__c,
                                                    Temp_Billing_Street_Address__c = fa.street_address__c);
                    baccounts.put(fa.Id, bacct);
                }
            }
           
            
            fa.Done__c = true;
            fa.Process__c = false;

            faMap.put(fa.id, fa);
        }

        Savepoint sp = Database.setSavepoint();

        try {
            if (!accounts.isEmpty()) {
                update accounts.values();
            }
            
            if (!accountsPrimary.isEmpty()) {
                update accountsPrimary.values();
            }
            
            if(!baccounts.isEmpty()){
                update baccounts.values();
            }

            if (!faMap.isEmpty()) {
                update faMap.values();
            }
            
        } catch (Exception e) {Database.rollback(sp); throw(e);}
    }

}