sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Non_Residential_Company_Customer</fullName>
        <active>true</active>
        <description>Non-residential company customers or third parties that have business relationship with SEWL.</description>
        <label>Non-Residential Company Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Non_Residential_Individual_Customer</fullName>
        <active>true</active>
        <description>Non-residential Individual customers.</description>
        <label>Non-Residential Individual Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <description>Residential customers that have business relationship with SEWL.</description>
        <label>Residential Customer</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Bad_Debt__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Cust Verification - Bad Debt</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <formula>Property__r.CIS_Property_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS Property Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clerical__c</fullName>
        <label>Clerical</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recovery_Path__c</fullName>
        <label>Recovery Path</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <recordTypes>
        <fullName>Ad_Hoc</fullName>
        <active>true</active>
        <description>Ad-hoc billing account.</description>
        <label>Ad-Hoc</label>
    </recordTypes>
    <recordTypes>
        <fullName>Billing_Account</fullName>
        <active>true</active>
        <description>Billing Account that is not a Group Billing Account or Adhoc Account</description>
        <label>Billing Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Group_Billing_Account</fullName>
        <active>true</active>
        <description>Group Billing Account that may have multiple Sub Accounts under its umbrella.</description>
        <label>Group Billing Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Budget__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Cust Verification - Budget</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recovery_Path__c</fullName>
        <label>Recovery Path</label>
        <picklist>
            <picklistValues>
                <fullName>D1 - RESIDENTIAL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2 - RESIDENTIAL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D3 - TENANT USAGE - RES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD - Parks and Drainage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N1 - NON RESIDENTIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N2 - Non Res Serv Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N3 - NON RES USAGE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>The first 255 characters of the full description will be automatically copied here.</description>
        <inlineHelpText>If blank , the first 255 characters of the full description will be automatically copied here.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <recordTypes>
        <fullName>Concession</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Create and Update Concession</description>
        <label>Concession</label>
    </recordTypes>
    <recordTypes>
        <fullName>Concession_Delete</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Delete Concession</description>
        <label>Concession - Delete</label>
    </recordTypes>
    <recordTypes>
        <fullName>General_Enquiry</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Create general enquiry cases</description>
        <label>General Enquiry</label>
    </recordTypes>
    <recordTypes>
        <fullName>Information_Statement_Update</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Request for Information Statement Update.</description>
        <label>Information Statement Update</label>
    </recordTypes>
    <recordTypes>
        <fullName>Notice_of_Sale</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Case to track Notice of Sale process.</description>
        <label>Notice of Sale</label>
    </recordTypes>
    <recordTypes>
        <fullName>Special_Meter_Read</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Request for Special Meter Read.</description>
        <label>Special Meter Read</label>
    </recordTypes>
    <recordTypes>
        <fullName>Suspend_Recovery</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Request to pay at a later stage and go through the suspend recovery process.</description>
        <label>More Time to Pay</label>
    </recordTypes>
    <recordTypes>
        <fullName>Take_Customer_Meter_Read</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Case to record Customer Meter Read.</description>
        <label>Take Customer Meter Read</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification_Code__c.object
<CustomObject>
    <description>Classification codes for customers</description>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description for the customer classification</description>
        <inlineHelpText>Short Description for the customer classification</inlineHelpText>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Classification Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Clerical__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of clericals for Customer Verification</description>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cust Verification - Clerical</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Customer_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Person_Customer_Relationship__c.object
<CustomObject>
    <label>Third Party Relationship</label>
    <nameField>
        <displayFormat>Link-{000000000}</displayFormat>
        <label>3rd Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <description>Property reference number in HiAF</description>
        <externalId>true</externalId>
        <label>CIS Property Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Recovery_Path__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of clericals for customer verification</description>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cust Verification - Recovery Path</label>
</CustomObject>

sample/retrieveUnpackaged/classes/SObjectCreator.cls
/**
 * Apex code is a strongly-typed, object-oriented programming language that allows developers to execute flow and
 * transaction control statements on the Force.com platform server in conjunction with calls to the Force.com API.
 * It has a syntax that will be familiar to Java and C# programmers and has the usual array of features such as classes,
 * interfaces, constants, class variables, and annotations.
 *
 * <Project>South East Water Limited - TestMethod Helper</Project>
 * <Title>SObjectCreator</Title>
 *
 * <Description>
 *  This class creates sObjects to be used in YOUR testMethods.
 *  It should be updated to include the custom sObjects needed for YOUR testMethods.
 *  Existing testMethods in this class may fail due to custom validation rules or required custom fields.
 *  These, if required, should be updated so that it can be successfully inserted to the database.
 *
 *  The sObjects created here have the bare minimum of fields needed to be inserted.
 *  Additional fields required for your testMethods should be added to in YOUR testMethods, not here.
 *  Any relationships including RecordTypes should be added to in YOUR testMethods, not here.
 *  There should be no DML or SOQL in the code here, only in the testMethods.
 *  Object with RecordType should be specified, otherwise they are default which is bad practice.
 *  All class should always have 100% code coverage.
 * </Description>
 *
 * <Organization>South East Water Limited<Organization>
 * <ClassName>SObjectCreator<ClassName>
 * <ApiVersion>22.0<ApiVersion>
 * <CreatedBy>Gareth Knight<CreatedBy>
 * <CreatedDate>Tue, 13/09/2011<CreatedDate>
 *
 * <Changes>
 *  <Author></Author>
 *  <Date></Date>
 *  <Description>
 *
 *  </Description>
 * </Changes>
 
 	25-Feb-2014		ejandusay(Cloud Sherpas)	Moved test method in a separate test class
 */

public with sharing class SObjectCreator {

    //******************************************************************************************
    //                          Set up for Test Methods
    //******************************************************************************************
    // <Get all required RecordTypes>
    static{
        getRecordTypeIds();
    }

    private static Id RecordTypeAccountResidentialId;
    private static Id RecordTypeAccountNonResidentialCompanyId;
    private static Id RecordTypeAccountNonResidentialIndividualId;
    private static Id RecordTypeBillingAccountGroupBillingAccountId;
    private static Id RecordTypeBillingAccountBillingAccountId;
    private static Id RecordTypeBillingAccountAdHocId;
    private static Id RecordTypeCaseConcessionId;
    private static Id RecordTypeCaseConcessionDeleteId;
    private static Id RecordTypeCaseGeneralEnquiryId;
    private static Id RecordTypeCaseInfoStatementUpdateId;
    private static Id RecordTypeCaseNoticeOfSaleId;
    private static Id RecordTypeCaseSpecialMeterReadId;
    private static Id RecordTypeCaseSuspendRecoveryId;
    private static Id RecordTypeCaseTakeCustomerMeterReadId;
    private static Id RecordTypeCaseWebId;


    private static void getRecordTypeIds(){
        List<RecordType> RecordType_List = [SELECT r.SobjectType, r.DeveloperName FROM RecordType r
            WHERE (
                (r.SobjectType = 'Account' AND r.DeveloperName = 'Residential') OR
                (r.SobjectType = 'Account' AND r.DeveloperName = 'Non_Residential_Company_Customer') OR
                (r.SobjectType = 'Account' AND r.DeveloperName = 'Non_Residential_Individual_Customer') OR
                (r.SobjectType = 'Billing_Account__c' AND r.DeveloperName = 'Ad_Hoc') OR
                (r.SobjectType = 'Billing_Account__c' AND r.DeveloperName = 'Group_Billing_Account') OR
                (r.SobjectType = 'Billing_Account__c' AND r.DeveloperName = 'Billing_Account') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Concession') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Concession_Delete') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'General_Enquiry') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Information_Statement_Update') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Notice_of_Sale') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Special_Meter_Read') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Suspend_Recovery') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Take_Customer_Meter_Read') OR
                (r.SobjectType = 'Case' AND r.DeveloperName = 'Web')

            ) AND r.IsActive=true];
        for(RecordType r : RecordType_List){
            if(r.SobjectType=='Account' && r.DeveloperName=='Residential'){
                RecordTypeAccountResidentialId = r.Id;
            }
            else if(r.SobjectType=='Account' && r.DeveloperName=='Non_Residential_Company_Customer'){
                RecordTypeAccountNonResidentialCompanyId = r.Id;
            }
            else if(r.SobjectType=='Account' && r.DeveloperName=='Non_Residential_Individual_Customer'){
                RecordTypeAccountNonResidentialIndividualId = r.Id;
            }
            else if(r.SobjectType=='Billing_Account__c' && r.DeveloperName=='Ad_Hoc'){
                RecordTypeBillingAccountAdHocId = r.Id;
            }
            else if(r.SobjectType=='Billing_Account__c' && r.DeveloperName=='Billing_Account'){
                RecordTypeBillingAccountBillingAccountId = r.Id;
            }
            else if(r.SobjectType=='Billing_Account__c' && r.DeveloperName=='Group_Billing_Account'){
                RecordTypeBillingAccountGroupBillingAccountId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Concession'){
                RecordTypeCaseConcessionId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Concession_Delete'){
                RecordTypeCaseConcessionDeleteId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'General_Enquiry'){
                RecordTypeCaseGeneralEnquiryId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Information_Statement_Update'){
                RecordTypeCaseInfoStatementUpdateId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Notice_of_Sale'){
                RecordTypeCaseNoticeOfSaleId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Special_Meter_Read'){
                RecordTypeCaseSpecialMeterReadId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Suspend_Recovery'){
                RecordTypeCaseSuspendRecoveryId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Take_Customer_Meter_Read'){
                RecordTypeCaseTakeCustomerMeterReadId = r.Id;
            }
            else if (r.SobjectType == 'Case' && r.DeveloperName == 'Web'){
                RecordTypeCaseWebId = r.Id;
            }
        }
    }
    //*/// </Get all required RecordTypes>

    //******************************************************************************************
    //                     Standard Object and RecordTypes Creation
    //******************************************************************************************

    // <Create AccountResidentialCustomer>
    public static Account createAccountResidentialCustomer(){
        Account AccountResidentialCustomerObject = new Account();
        AccountResidentialCustomerObject.Name = 'Test Account Residential Customer';
        AccountResidentialCustomerObject.RecordTypeId = RecordTypeAccountResidentialId;
        return AccountResidentialCustomerObject;
    }
    //*/// </Create AccountResidentialCustomer>

    // <Create AccountNonResidentialIndividual>
    public static Account createAccountNonResidentialIndividual(){
        Account AccountNonResidentialIndividualObject = new Account();
        AccountNonResidentialIndividualObject.Name = 'Test Account Non-Residential Individual';
        AccountNonResidentialIndividualObject.RecordTypeId = RecordTypeAccountNonResidentialIndividualId;
        return AccountNonResidentialIndividualObject;
    }
    //*/// </Create AccountNonResidentialIndividual>

    // <Create AccountNonResidentialCompany>
    public static Account createAccountNonResidentialCompany(){
        Account AccountNonResidentialCompanyObject = new Account();
        AccountNonResidentialCompanyObject.Name = 'Test Account Non-Residential Company';
        AccountNonResidentialCompanyObject.RecordTypeId = RecordTypeAccountNonResidentialCompanyId;
        return AccountNonResidentialCompanyObject;
    }
    //*/// </Create AccountNonResidentialCompany>

    // <Create Contact>
    public static Contact createContact(){
        Contact ContactObject = new Contact();
        ContactObject.FirstName = 'TestFirstName';
        ContactObject.LastName = 'TestLastName';
        ContactObject.Title = 'TestTitle';
        ContactObject.Phone = '021123456';
        ContactObject.Email = 'testEmail@testEmail.com';
        return ContactObject;
    }

    //*/// </Create Contact>

    // <Create BillingAccountAdhoc>
    public static Billing_Account__c createBillingAccountAdHoc(){
        Billing_Account__c BillingAccountAdHocObject = new Billing_Account__c();
        BillingAccountAdhocObject.Name = 'Test AdHoc Account #';
        BillingAccountAdHocObject.RecordTypeId = RecordTypeBillingAccountAdHocId;
        return BillingAccountAdhocObject;
    }
    //*/// </Create BillingAccountAdHoc>

    // <Create BillingAccountAdhoc>
    public static Billing_Account__c createBillingAccountBillingAccount(){
        Billing_Account__c BillingAccountBillingAccountObject = new Billing_Account__c();
        BillingAccountBillingAccountObject.Name = 'Test Billing Account #';
        BillingAccountBillingAccountObject.RecordTypeId = RecordTypeBillingAccountBillingAccountId;
        return BillingAccountBillingAccountObject;
    }
    //*/// </Create BillingAccountBillingAccount>

    // <Create BillingAccountAdhoc>
    public static Billing_Account__c createBillingAccountGroupBillingAccount(){
        Billing_Account__c BillingAccountGroupBillingAccountObject = new Billing_Account__c();
        BillingAccountGroupBillingAccountObject.Name = 'Test Group Billing Account #';
        BillingAccountGroupBillingAccountObject.RecordTypeId = RecordTypeBillingAccountGroupBillingAccountId;
        return BillingAccountGroupBillingAccountObject;
    }
    //*/// </Create BillingAccountGroupBillingAccount>

    // <Create Property>
    public static Property__c createProperty(){
        Property__c PropertyObject = new Property__c();
        PropertyObject.Name = 'TestProperty';
        PropertyObject.Universal_Id_c__c = 'asdflkj';
        PropertyObject.CIS_Property_Id__c = '01A/00000/0';
        return PropertyObject;
    }

    //*/// </Create Property>

    // <Create CaseInfoStatementUpdate>
    public static Case createCaseInfoStatementUpdate(){
        Case CaseInfoStatementUpdateObject = new Case();
        CaseInfoStatementUpdateObject.RecordTypeId = RecordTypeCaseInfoStatementUpdateId;
        CaseInfoStatementUpdateObject.Status = 'New';
        return CaseInfoStatementUpdateObject;
    }

    //*/// </Create CaseInfoStatementUpdate>

    // <Create Notice of Sale case>
    public static Case createCaseNoticeOfSale(){
        Case CaseNoticeOfSaleObject = new Case();
        CaseNoticeOfSaleObject.RecordTypeId = RecordTypeCaseNoticeOfSaleId;
        CaseNoticeOfSaleObject.Status = 'New';
        return CaseNoticeOfSaleObject;
    }

    //*/// </Create Notice of Sale case>

    // <CreateClassificationCode>
    public static Classification_Code__c createClassificationCode(){
        Classification_Code__c ClassificationCodeObject = new Classification_Code__c();
        ClassificationCodeObject.Name = 'ZZ';
        ClassificationCodeObject.Short_Description__c = 'A test description';
        return ClassificationCodeObject;
    }

    //*/// </CreateClassificationCode>

    // <CreateCustomerClassification>
    public static Customer_Classification__c createCustomerClassification(){
        Customer_Classification__c CustomerClassificationObject = new Customer_Classification__c();
        return CustomerClassificationObject;
    }

    //*/// </CreateCustomerClassification>

    // <CreatePersonCustomerRelationship >
    public static Person_Customer_Relationship__c createPersonCustomerRelationship(){
        Person_Customer_Relationship__c PersonCustomerRelationshipObject = new Person_Customer_Relationship__c();
        return PersonCustomerRelationshipObject;
    }

    
    //*/// </CreatePersonCustomerRelationship>

    // <CreateBadDebt>
    public Static Bad_Debt__c createBadDebtCustomSetting(){
        Bad_Debt__c BadDebtCustomSetting = new Bad_Debt__c();
        BadDebtCustomSetting.Name = 'Test';
        return BadDebtCustomSetting;
    }

   //*/// </CreateBadDebt>

    // <CreateRecoveryPath>
    public static Recovery_Path__c createRecoveryPathCustomSetting(){
        Recovery_Path__c RecoveryPathCustomSetting = new Recovery_Path__c();
        RecoveryPathCustomSetting.Name = 'Test';
        return RecoveryPathCustomSetting;
    }

    //*/// </CreateRecoveryPath>

    // <CreateClerical>
    public static Clerical__c createClericalCustomSetting(){
        Clerical__c ClericalCustomSetting = new Clerical__c();
        ClericalCustomSetting.Name = 'test';
        return ClericalCustomSetting;
    }

    //*/// </CreateClerical>

    // <CreateBudget>
    public static Budget__c createBudgetCustomSetting(){
        Budget__c BudgetCustomSetting = new Budget__c();
        return BudgetCustomSetting;
    }

    
}