sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Company Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Billing_Address_Same_As__c</fullName>
        <inlineHelpText>Please set flag None to change address in Billing Account.</inlineHelpText>
        <label>Billing Address Same As</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Billing Account Address</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Billing Account Address</description>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number_Check_Digit__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account Number (Check Digit)</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>Property__r.Street_Address__c &amp; br() &amp; Property__r.Suburb__c &amp;&quot; &quot;&amp; text( Property__r.State__c)&amp;&quot; &quot;&amp; Property__r.Postal_Code__c</formula>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Person_Name__c</fullName>
        <inlineHelpText>For Person that is not in system and no need to record in system.</inlineHelpText>
        <label>Contact Person Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <label>Country</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expression_of_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An orphaned Expression of Interest because it couldn&apos;t be matched to a Billing Account</description>
        <label>Expression of Interest</label>
        <referenceTo>Expression_of_Interest__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <label>State/Postcode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <formula>Property__r.Suburb__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Suburb</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Early_Connection_Option</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <label>ECO Expression of Interest</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Phone_Number__c</fullName>
        <inlineHelpText>This field will be updated based on your selection of Preferred Phone Type.</inlineHelpText>
        <label>Preferred Phone Number</label>
        <type>Phone</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Expression_of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_Email_Address__c</fullName>
        <label>Confirm Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <label>Customer number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>Mailing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Mailing Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Postal_Code__c</fullName>
        <label>Mailing Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <label>Mailing State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address__c</fullName>
        <label>Mailing Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Expressions of Interest</relationshipLabel>
        <relationshipName>Expressions_of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_details__c</fullName>
        <description>Value to be entered if the Where did you hear about the Early Connection Option? is set to Other.</description>
        <label>Other details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Country__c</fullName>
        <label>Property Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Postal_Code__c</fullName>
        <label>Property Postal code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Address__c</fullName>
        <label>Property Street address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Where_did_you_hear_about_ECO__c</fullName>
        <label>What prompted your enquiry today?</label>
        <picklist>
            <picklistValues>
                <fullName>Outdoor advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter from SE Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern Peninsula News</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mornington Peninsula Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word of mouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE Water website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE Water bill insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rye office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EOI-{0000000}</displayFormat>
        <label>EOI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expressions of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Creation_Method__c</fullName>
        <label>Creation Method</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>Property__r.Address_Also_Known_As__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/ECOExpressionOfInterestForm_ExCon.cls
/*
    Type:       Controller Extension
    Purpose:    
                Controller Extension for ECO Expression of Interest Form

    ---------------------------------------------------------------
    History:
	03-Jan-2014	N.Patterson		US557 - Created
	20-Jan-2014 N.Patterson		US546 - All EOIs need to create a case as they need to be called
*/

public without sharing class ECOExpressionOfInterestForm_ExCon {
	private ApexPages.StandardController stdCon;
    public Opportunity oppty {get; set;}
    public Billing_Account__c ba {get; set;}
    public Expression_of_Interest__c eoi {get; set;}
    
    public String enteredPropertyAddress {get; set;}
    public String enteredMailingAddress {get; set;}
    public Boolean mailingSameAsProperty {get; set;}
    public static String SUBMISSION_ERROR_MESSAGE = 'An error has occurred while submitting your details.  Please email us at peninsulaeco@sew.com.au or contact us directly on 1800 720 613 between 9am and 5pm, Monday to Friday.';
    
    public ECOExpressionOfInterestForm_ExCon (ApexPages.StandardController controller) {
        stdCon = controller;
        eoi = (Expression_of_Interest__c) stdCon.getRecord();
        oppty = null;
        ba = null;
        
        
        //check for parameters
        String encryptedBANumber = ApexPages.currentPage().getParameters().get('ba');
        String encryptedPersonId = ApexPages.currentPage().getParameters().get('p');
        
        System.debug('#####encryptedBANumber: ' + encryptedBANumber + '\nencryptedPersonId: ' + encryptedPersonId);
        
        if (encryptedBANumber != null){
        	String baNumber = null;
        	
        	if (Test.isRunningTest()) {
        		baNumber = SystemUtil.decryptURLFriendlyValue(encryptedBANumber);
        		System.debug('#####Test baNumber: ' + baNumber);
        	}
        	else {
        		baNumber = SystemUtil.decryptValue(encryptedBANumber);
        		System.debug('#####baNumber: ' + baNumber);
        	}
        	
        	if (baNumber != null && baNumber.length() > 0){
        		List<Billing_Account__c> baList = [Select Id, HiAF_Account_Number_Check_Digit__c, Property_Address__c, Customer__c, Property__c, Street_Address__c, State__c, Postal_Code__c, Country__c, City__c, Billing_Address_Same_As__c,
        												Property__r.State__c, Property__r.Postal_Code__c, Property__r.Suburb__c, Property__r.Street_Address__c
        											FROM Billing_Account__c 
        											WHERE HiAF_Account_Number_Check_Digit__c = :baNumber];
        		if(!baList.isEmpty()){
        			ba = baList[0];

        			eoi.Customer_Number__c = ba.HiAF_Account_Number_Check_Digit__c;
        			if (ba.Property__c != null){
        				eoi.Property_State__c = ba.Property__r.State__c;
        				eoi.Property_Postal_Code__c = ba.Property__r.Postal_Code__c;
        				eoi.Property_City__c = ba.Property__r.Suburb__c;
        				eoi.Property_Street_Address__c = ba.Property__r.Street_Address__c;
        				eoi.Property_Country__c = 'AUSTRALIA';
        				enteredPropertyAddress = eoi.Property_Street_Address__c + ', ' + eoi.Property_City__c + ', ' + eoi.Property_State__c + ' ' + eoi.Property_Postal_Code__c;
        			}
        			
        			eoi.Mailing_State__c = ba.State__c;
    				eoi.Mailing_Postal_Code__c = ba.Postal_Code__c;
    				eoi.Mailing_City__c = ba.City__c;
    				eoi.Mailing_Street_Address__c = ba.Street_Address__c;
    				eoi.Mailing_Country__c = ba.Country__c;
    				enteredMailingAddress = eoi.Mailing_Street_Address__c + ', ' + eoi.Mailing_City__c + ', ' + eoi.Mailing_State__c + ' ' + eoi.Mailing_Postal_Code__c;
        		}
        	}
        }
        
        if (encryptedPersonId != null){
        	String pId = null;
        	try {
        		pId = SystemUtil.decryptURLFriendlyValue(encryptedPersonId);
        	}
        	catch (Exception e){
        		pId = SystemUtil.decryptValue(encryptedPersonId);
        	}
        	if (pId != null && pId.length() > 0){
        		List<Contact> contactList = [Select Id, Preferred_Phone_Number__c, LastName, FirstName, Email From Contact c Where id = :pId];
        		if (!contactList.isEmpty()){
        			eoi.First_Name__c = contactList[0].FirstName;
        			eoi.Last_Name__c = contactList[0].LastName;
        			eoi.Phone_Number__c = contactList[0].Preferred_Phone_Number__c;
        			eoi.Email_Address__c = contactList[0].Email;
        		}
        	}
        }
    }
    
    public PageReference submitForm(){
        Id billingAccountId = null;
        Boolean validationErrorFound = false;
        System.debug('####submitForm eoi:' + eoi);
        try {
        	// Property and mailing address are mandatory
        	if (eoi.Mailing_City__c == '' || eoi.Mailing_Street_Address__c == '' || eoi.Mailing_Postal_Code__c == '' || eoi.Mailing_State__c == '' ||
        		eoi.Mailing_City__c == null || eoi.Mailing_Street_Address__c == null || eoi.Mailing_Postal_Code__c == null || eoi.Mailing_State__c == null){
        		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Not all mandatory Mailing address fields have been entered') );
        		System.debug('#####Mailing address not complete: City=' + eoi.Mailing_City__c + ' Street=' + eoi.Mailing_Street_Address__c + ' PC=' + eoi.Mailing_Postal_Code__c + ' State=' + eoi.Mailing_State__c);
        		validationErrorFound = true;
        	}
        	
        	if (eoi.Property_City__c == '' || eoi.Property_Street_Address__c == '' || eoi.Property_Postal_Code__c == '' || eoi.Property_State__c == '' ||
        		eoi.Property_City__c == null || eoi.Property_Street_Address__c == null || eoi.Property_Postal_Code__c == null || eoi.Property_State__c == null){
        		ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Not all mandatory Property address fields have been entered') );
        		System.debug('#####Property address not complete: City=' + eoi.Property_City__c + ' Street=' + eoi.Property_Street_Address__c + ' PC=' + eoi.Property_Postal_Code__c + ' State=' + eoi.Property_State__c);
        		validationErrorFound = true;
        	}
        	
        	
        	// check if the email address and confirm email address match
        	if (eoi.Confirm_Email_Address__c != eoi.Email_Address__c){
        		eoi.Confirm_Email_Address__c.addError('The email addresses must match');
        		eoi.Email_Address__c.addError('The email addresses must match');
        		System.debug('#####email address not complete: email=' + eoi.Email_Address__c);
        		validationErrorFound = true;
        	}
        	
        	// if other is selected, then other details is mandatory
        	if (eoi.Where_did_you_hear_about_ECO__c == 'Other' && (eoi.Other_details__c == null || eoi.Other_details__c == '' || eoi.Other_details__c == 'Please enter where you heard about the ECO')){
        		eoi.Other_details__c.addError('If Other is selected, please enter the details');
        		System.debug('#####Other not complete: Where_did_you_hear_about_ECO__c=' + eoi.Where_did_you_hear_about_ECO__c + ' Other_details__c=' + eoi.Other_details__c);
        		validationErrorFound = true;
        	}
        	
        	if (validationErrorFound){
        		return null;
        	}
        	
        	
	        // check for the customer number and if it is valid 
	        if (ba == null && eoi.Customer_Number__c != null && eoi.Customer_Number__c.length() > 0){
	        	List<Billing_Account__c> baList = [SELECT Id, Property_Address__c, Customer__c, Property__c FROM Billing_Account__c WHERE HiAF_Account_Number_Check_Digit__c = :eoi.Customer_Number__c];
	        	if (!baList.isEmpty()){
	        		ba = baList[0]; 
	        	}
	        }
	        
	        // if we have a billing account, look for the Opportunity
	        if (oppty == null && ba != null){
	        	List<Opportunity> existingOppty = [SELECT Id, StageName FROM Opportunity WHERE Billing_Account__c = :ba.id];
	        	if(!existingOppty.isEmpty()){
	        		oppty = existingOppty[0];
	        		oppty.LeadSource = 'Web';
	        		if (oppty.StageName == 'Eligible' || oppty.StageName == 'Maybe-Eligible' || oppty.StageName == 'Ineligible'){
	            		oppty.StageName = 'Inquired';
	        		}
	        		eoi.Opportunity__c = oppty.Id;
	        		update oppty;
	        	}
	        	else {
	        		// Billing account exists, but opportunity doesn't, so lets create the oppty
	        		oppty = new Opportunity();
	        		oppty.StageName = 'Inquired';
	        		oppty.name = 'ECO - ' + ba.Property_Address__c.replaceAll('<br>',' ');
	        		oppty.Type = 'Existing Business';
	        		oppty.CloseDate = Date.parse('31/12/2032');
	        		oppty.LeadSource = 'Web';
	        		oppty.Billing_Account__c = ba.Id;
	        		oppty.Creation_Method__c = 'Manual';
	        		oppty.AccountId = ba.Customer__c;
	        		oppty.Property__c = ba.Property__c;
	        		insert oppty;
	        		eoi.Opportunity__c = oppty.Id;
	        	}
	        }
	        
			// insert Expression Of Interest object, if Oppty has been found, then update it, if not and Billing Account can't be found, then create case.  Otherwise create Oppty
        	insert eoi;
        	
        	// US546 - Need to create a case for all enquiries
        	
			// create case
			Case newCase = new Case();
			newCase.OwnerId = [Select Id, DeveloperName From Group Where DeveloperName = 'ECO_Cases'].Id;
			newCase.RecordTypeId = [Select Id, DeveloperName From RecordType  Where DeveloperName = 'Early_Connection_Option'].Id;
			newCase.Due_Date__c = Date.today().addDays(14);
			newCase.Contact_Person_Name__c = eoi.First_Name__c + ' ' + eoi.Last_Name__c;
			newCase.Contact_Email__c = eoi.Email_Address__c;
			newCase.Contact_Phone_Number__c = eoi.Phone_Number__c;
			newCase.Type = 'Property Development';
			newCase.Category_Level_1__c = 'Programs';
			newCase.Category_Level_2__c = 'Early Connection Option';
			newCase.Category_Level_3__c = 'Link EOI to Opportunity';
			newCase.Status = 'New';
			newCase.Origin = 'Web';
			newCase.Subject = 'Unable to locate billing account for ECO EOI form';
			
			// add the billing account, customer and opportunity to the case if the Opportunity exists or has been created.
			if (oppty != null){
				newCase.AccountId = oppty.AccountId;
				newCase.Billing_Account__c = oppty.Billing_Account__c;
				newCase.Opportunity__c = oppty.Id;
				newCase.Category_Level_3__c = 'Follow up EOI';
				newCase.Subject = 'Follow up ECO EOI form';
			}
			
			String customerNumber = '';
			String companyName = '';
			String otherDetails = '';
			
			if (eoi.Other_details__c != null){
				otherDetails = eoi.Other_details__c;
			}
			
			if (eoi.Customer_Number__c != null){
				customerNumber = eoi.Customer_Number__c;
			}
			
			if (eoi.Company_Name__c != null){
				companyName = eoi.Company_Name__c;
			}
			
			newCase.Short_Description__c = 'Unable to match Expression of Interest form for ' + eoi.First_Name__c + ' ' + eoi.Last_Name__c + '\n' +
								'Customer number: ' + customerNumber + '\n' +
								'Phone: ' + eoi.Phone_Number__c + '\n' +
								'Email: ' + eoi.Email_Address__c;
			newCase.Description = 'Unable to match the Expression of Interest form to a Billing Account:\n' +
								'Customer number: ' + customerNumber + '\n' +
								'Company name: ' + companyName + '\n' +
								'First name: ' + eoi.First_Name__c + '\n' +
								'Last name: ' + eoi.Last_Name__c + '\n' +
								'Property address: ' + eoi.Property_Street_Address__c + ' ' + eoi.Property_City__c + ', ' + eoi.Property_State__c + ' ' + eoi.Property_Postal_Code__c + ' ' + eoi.Property_Country__c + '\n' +
								'Mailing address: ' + eoi.Mailing_Street_Address__c + ' ' + eoi.Mailing_City__c + ', ' + eoi.Mailing_State__c + ' ' + eoi.Mailing_Postal_Code__c + ' ' + eoi.Mailing_Country__c + '\n' +
								'Phone: ' + eoi.Phone_Number__c + '\n' +
								'Email: ' + eoi.Email_Address__c + '\n' +
								'What prompted your enquiry today? ' + eoi.Where_did_you_hear_about_ECO__c + ' ' + eoi.Other_details__c;
			
			newCase.Expression_of_Interest__c = eoi.id;		
			
			insert newCase;
        
        	
    	}
    	catch (DmlException e){
    		if (e.getDmlType(0) != StatusCode.REQUIRED_FIELD_MISSING && e.getDmlType(0) != StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION && e.getDmlType(0) != StatusCode.INVALID_EMAIL_ADDRESS && e.getDmlType(0) != StatusCode.REQUIRED_FIELD_MISSING){  
    			ApexPages.addmessage(
            	new ApexPages.message(ApexPages.severity.ERROR, SUBMISSION_ERROR_MESSAGE) );
    		}
    		return null;
    	}
    	catch (Exception e) {
    		ApexPages.addmessage(
            	new ApexPages.message(ApexPages.severity.ERROR, SUBMISSION_ERROR_MESSAGE) );
            return null;
    	}   
        /*ApexPages.addmessage(
	            	new ApexPages.message(ApexPages.severity.INFO, 'Thank you for your expression of interest.  One of our consultants will be in touch soon.') );*/
        
        return Page.ECOExpressionOfInterestFeedback;
    }
}