sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Company Email</label>
        <type>Email</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Same_As__c</fullName>
        <inlineHelpText>Please set flag None to change address in Billing Account.</inlineHelpText>
        <label>Billing Address Same As</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number_Check_Digit__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account Number (Check Digit)</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad-Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expression_of_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An orphaned Expression of Interest because it couldn&apos;t be matched to a Billing Account</description>
        <label>Expression of Interest</label>
        <referenceTo>Expression_of_Interest__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <label>State/Postcode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Preferred_Phone_Type__c</fullName>
        <label>Preferred Phone Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Expression_of_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Confirm_Email_Address__c</fullName>
        <label>Confirm Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <label>Customer number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Expressions of Interest</relationshipLabel>
        <relationshipName>Expressions_of_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_details__c</fullName>
        <description>Value to be entered if the Where did you hear about the Early Connection Option? is set to Other.</description>
        <label>Other details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Country__c</fullName>
        <label>Property Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Postal_Code__c</fullName>
        <label>Property Postal code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Street_Address__c</fullName>
        <label>Property Street address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Where_did_you_hear_about_ECO__c</fullName>
        <label>What prompted your enquiry today?</label>
        <picklist>
            <picklistValues>
                <fullName>Outdoor advertising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter from SE Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southern Peninsula News</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mornington Peninsula Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word of mouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE Water website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE Water bill insert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rye office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EOI-{0000000}</displayFormat>
        <label>EOI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expressions of Interest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/SystemSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Aes128PrivateKey__c</fullName>
        <label>Aes128PrivateKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SystemSettings</label>
</CustomObject>

sample/retrieveUnpackaged/classes/TestECO_EOI.cls
/*
    Type:       Test Class
    Purpose:    
                Performs Testing for ECO Expression of Interest Form

    ---------------------------------------------------------------
    History:
	03-Jan-2014	N.Patterson		US557 - Created
*/
@isTest
private class TestECO_EOI {
	static void setupSystemSetting(){
    	// setup systemsettings for the tests
    	SystemSettings__c aes = SystemSettings__c.getOrgDefaults();
    	User thisUser = [ Select Id from User where Id = :UserInfo.getUserId() ];
		System.runAs( thisUser ){
			if(aes == null || aes.id == null) {
				aes = new SystemSettings__c();
				aes.Aes128PrivateKey__c = EncodingUtil.base64encode(Crypto.generateAesKey(128));
				insert aes;
			}
			else {
				aes.Aes128PrivateKey__c = EncodingUtil.base64encode(Crypto.generateAesKey(128));
				update aes;
			}
		}
		System.debug('####aes: ' + aes);
    }
    

    static testMethod void testEOIOpptyExists() {
    	setupSystemSetting();
    	
    	// Setup test data
        Account acc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        con.MobilePhone = '0422123456';
        con.Preferred_Phone_Type__c = 'Mobile';
        update con;
        
        Property__c prop = PortalTestHelper.createProperty();
        prop.Postal_Code__c = '3000';
        prop.State__c = 'VIC';
        update prop;
        Meter_Details__c meter = PortalTestHelper.createMeter(prop, 'theMeter');
        Billing_Account__c billAcct = PortalTestHelper.createBillingAccount(acc, prop);
        billAcct.Billing_Address_Same_As__c = 'Property';
        
        update billAcct;
        
        billAcct = [Select id, HiAF_Account_Number_Check_Digit__c, HiAF_Account_Number__c, customer__c, RecordTypeId, role__c, Property__c, account_Name__c, status__c
        			FROM Billing_Account__c
        			WHERE id = :billAcct.id];
        
        Opportunity oppty = new Opportunity();
		oppty.StageName = 'Eligible';
		oppty.name = 'ECO';
		oppty.Type = 'Existing Business';
		oppty.CloseDate = Date.parse('31/12/2032');
		oppty.LeadSource = 'Web';
		oppty.Billing_Account__c = billAcct.Id;
		oppty.AccountId = billAcct.Customer__c;
		insert oppty;
		
		PageReference pageRef = Page.ECOExpressionOfInterestForm;
		//pageRef.getParameters().put('ba',SystemUtil.encryptForURL(billAcct.HiAF_Account_Number_Check_Digit__c));
		//pageRef.getParameters().put('p',SystemUtil.encryptForURL(con.Id));
        Test.setCurrentPageReference(pageRef);
        System.debug('####ba: ' + SystemUtil.encryptForURL(billAcct.HiAF_Account_Number_Check_Digit__c) + ' from ' + billAcct.HiAF_Account_Number_Check_Digit__c);
        System.debug('####p: ' + SystemUtil.encryptForURL(con.Id) + ' from ' + con.Id);
        System.currentPageReference().getParameters().put('ba',SystemUtil.encryptForURL(billAcct.HiAF_Account_Number_Check_Digit__c));
        System.currentPageReference().getParameters().put('p',SystemUtil.encryptForURL(con.Id));
        
        ApexPages.StandardController stdCon = new ApexPages.standardController(new Expression_of_Interest__c());  
        
		
		Test.startTest();
			ECOExpressionOfInterestForm_ExCon controller = new ECOExpressionOfInterestForm_ExCon(stdCon);
			System.assertEquals(con.FirstName, controller.eoi.First_Name__c);
			System.assertEquals(con.LastName, controller.eoi.Last_Name__c);
			System.assertEquals(billAcct.HiAF_Account_Number_Check_Digit__c, controller.eoi.Customer_Number__c);
			
			controller.EOI.Email_Address__c = 'me@me.com'; 
			controller.eoi.Confirm_Email_Address__c = 'me@me.com';
			controller.eoi.Where_did_you_hear_about_ECO__c = 'Other';
			controller.eoi.Other_details__c = 'Other';
			System.assert(controller.submitForm() != null);
			
			oppty = [Select ID, StageName, Billing_Account__c From Opportunity Where Id = :oppty.id];
			Expression_of_Interest__c eoi = [Select Id, Opportunity__c From Expression_of_Interest__c Where Id = :controller.eoi.id];
			System.assertEquals(oppty.Id, eoi.Opportunity__c);
		Test.stopTest();
    }
    
    static testMethod void testEOIOpptyNotExists() {
    	setupSystemSetting();
    	
    	// Setup test data
        Account acc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        Property__c prop = PortalTestHelper.createProperty();
        Meter_Details__c meter = PortalTestHelper.createMeter(prop, 'theMeter');
        Billing_Account__c billAcct = PortalTestHelper.createBillingAccount(acc, prop);
        billAcct = [Select id, HiAF_Account_Number_Check_Digit__c, HiAF_Account_Number__c, customer__c, RecordTypeId, role__c, Property__c, account_Name__c, status__c
        			FROM Billing_Account__c
        			WHERE id = :billAcct.id];
        
        PageReference pageRef = Page.ECOExpressionOfInterestForm;
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardController stdCon = new ApexPages.standardController(new Expression_of_Interest__c());  
        
		Test.startTest();
			ECOExpressionOfInterestForm_ExCon controller = new ECOExpressionOfInterestForm_ExCon(stdCon);
			
			controller.eoi.First_Name__c = 'John';
			controller.eoi.Last_Name__c = 'Smith';
			controller.EOI.Email_Address__c = 'me@me.com'; 
			controller.eoi.Confirm_Email_Address__c = 'me@me.com';
			controller.eoi.Where_did_you_hear_about_ECO__c = 'Other';
			controller.eoi.Other_details__c = 'Other';
			controller.eoi.Customer_Number__c = billAcct.HiAF_Account_Number_Check_Digit__c;
			controller.eoi.Phone_Number__c = '0395523222';
			controller.eoi.Property_State__c = 'VIC';
        	controller.eoi.Property_Postal_Code__c = '3202';
        	controller.eoi.Property_City__c = 'Heatherton';
			controller.eoi.Property_Street_Address__c = '20 Corporate Drive';
			controller.eoi.Property_Country__c = 'AUSTRALIA';
			controller.enteredPropertyAddress = controller.eoi.Property_Street_Address__c + ', ' + controller.eoi.Property_City__c + ', ' + controller.eoi.Property_State__c + ' ' + controller.eoi.Property_Postal_Code__c;
        	controller.eoi.Mailing_State__c = 'VIC';
    		controller.eoi.Mailing_Postal_Code__c = '3202';
			controller.eoi.Mailing_City__c = 'Geelong';
			controller.eoi.Mailing_Street_Address__c = '10 Cats Street';
			controller.eoi.Mailing_Country__c = 'AUSTRALIA';
			controller.enteredMailingAddress = controller.eoi.Mailing_Street_Address__c + ', ' + controller.eoi.Mailing_City__c + ', ' + controller.eoi.Mailing_State__c + ' ' + controller.eoi.Mailing_Postal_Code__c;
			controller.submitForm();
			
			Opportunity oppty = [Select ID, StageName, Billing_Account__c From Opportunity Where Id = :controller.oppty.Id];
			Expression_of_Interest__c eoi = [Select Id, Opportunity__c From Expression_of_Interest__c Where Id = :controller.eoi.id];
			System.assertEquals(oppty.Id, eoi.Opportunity__c);
			System.assertEquals('Inquired', oppty.StageName);
		Test.stopTest();
    }
    
    static testMethod void testEOINoBAEntered() {
    	setupSystemSetting();
    	
    	// Setup test data
    	
		PageReference pageRef = Page.ECOExpressionOfInterestForm;
        Test.setCurrentPageReference(pageRef);
        ApexPages.StandardController stdCon = new ApexPages.standardController(new Expression_of_Interest__c());  
        
		Test.startTest();
			ECOExpressionOfInterestForm_ExCon controller = new ECOExpressionOfInterestForm_ExCon(stdCon);
			controller.EOI.Email_Address__c = 'me@me.com'; 
			controller.eoi.Confirm_Email_Address__c = 'you@me.com';
			controller.eoi.Where_did_you_hear_about_ECO__c = 'Other';

			System.assertEquals(null, controller.submitForm());
			
			controller.eoi.First_Name__c = 'John';
			controller.eoi.Last_Name__c = 'Smith';
			controller.eoi.Confirm_Email_Address__c = 'me@me.com';
			controller.eoi.Other_details__c = 'Other';
			controller.eoi.Phone_Number__c = '0395523222';
			controller.eoi.Property_State__c = 'VIC';
        	controller.eoi.Property_Postal_Code__c = '3202';
        	controller.eoi.Property_City__c = 'Heatherton';
			controller.eoi.Property_Street_Address__c = '20 Corporate Drive';
			controller.eoi.Property_Country__c = 'AUSTRALIA';
			controller.enteredPropertyAddress = controller.eoi.Property_Street_Address__c + ', ' + controller.eoi.Property_City__c + ', ' + controller.eoi.Property_State__c + ' ' + controller.eoi.Property_Postal_Code__c;
        	controller.eoi.Mailing_State__c = 'VIC';
    		controller.eoi.Mailing_Postal_Code__c = '3202';
			controller.eoi.Mailing_City__c = 'Geelong';
			controller.eoi.Mailing_Street_Address__c = '10 Cats Street';
			controller.eoi.Mailing_Country__c = 'AUSTRALIA';
			controller.enteredMailingAddress = controller.eoi.Mailing_Street_Address__c + ', ' + controller.eoi.Mailing_City__c + ', ' + controller.eoi.Mailing_State__c + ' ' + controller.eoi.Mailing_Postal_Code__c;
			
			controller.submitForm();
			
			List<Case> caseList = [Select Id, Category_Level_1__c, Category_Level_2__c, Category_Level_3__c, Status
									FROM Case
									Where Expression_of_Interest__c = :controller.eoi.id];
			System.assert(caseList.size() == 1);
			
		Test.stopTest();
    }
}