sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Overdue_Balance_All_Accounts__c</fullName>
        <label>Overdue Balance All Accounts</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Bill_Due_Date__c</fullName>
        <label>Current Bill Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Overdue_Amount_Formula__c</fullName>
        <formula>IF(
	OR(Balance__c &lt;= 0, Is_Payment_Plan__c=TRUE, Direct_Debit__c=TRUE, Recovery_Suspended_Date__c &gt;= TODAY())
	, 0
	, IF(Balance__c &lt;= Current_Bill_Billed_Amount__c
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
			, Balance__c
			, 0)
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
				, Balance__c
				, IF(Balance__c &lt; Current_Bill_B_F_Balance__c
					,Balance__c
					,Current_Bill_B_F_Balance__c)
				)
			
		)
	)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/CalculateBillingOverdueAmountScheduler8.cls
/*
    Type:       Class Scheduler
    Purpose:    class that will be used for BillingBatchOverdueAmount6  and will be scheduled to execute every 8:00 AM daily

    Used By:    Billing Account Standard page    
    ---------------------------------------------------------------
    History:

    04/09/2012 ICastillo (Cloud Sherpas)   Created    
  
*/
global class CalculateBillingOverdueAmountScheduler8 implements Schedulable{   
    global void execute(SchedulableContext SC) {    
            // Initialize the BillingBatchOverdueAmount class
            BillingBatchOverdueAmount6 billing = new BillingBatchOverdueAmount6();
            // pass a string Billing_Account__c query to the BillingBatchOverdueAmount query method
            billing.query = 'Select Overdue_Amount_Formula__c,Balance__c, Current_Bill_Due_Date__c, customer__c, customer__r.Overdue_Balance_All_Accounts__c from Billing_Account__c';
            // call and execute the batch job
            ID batchprocessid = Database.executeBatch(billing,200);      
           
    }
}