sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Non_Residential_Company_Customer</fullName>
        <active>true</active>
        <description>Non-residential company customers or third parties that have business relationship with SEWL.</description>
        <label>Non-Residential Company Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <description>Residential customers that have business relationship with SEWL.</description>
        <label>Residential Customer</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Same_As__c</fullName>
        <inlineHelpText>Please set flag None to change address in Billing Account.</inlineHelpText>
        <label>Billing Address Same As</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Billing Account Address</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Same_Name_As_Customer__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Same Name As Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/CreateBillingAccountWizardExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class CreateBillingAccountWizardExCon
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class CreateBillingAccountWizardExCon_Test {

    /* TEST METHOD */
    public static testmethod void test_CreateBillingAccountWizardExCon(){
        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        prop.Street_Address__c = 'sdgservgtwe';
        prop.Suburb__c = 'sdgservgtwe';
        prop.State__c = 'sdgservgtwe';
        prop.Postal_Code__c = '1234';
        insert prop;
        Account acc = new Account();
        acc.Title__c = 'Mr';
        acc.Initials__c = 'J';
        acc.Account_Name__c = 'Jay and Kay El';
        acc.name = acc.Account_Name__c;
        acc.RecordTypeId = [Select id from RecordType where DeveloperName = 'Residential' and SObjectType = 'Account'][0].id;
        acc.BillingStreet = 'sdfascvv';
        acc.BillingCity = 'sdfascvv';
        acc.BillingState = 'sdfascvv';
        acc.BillingPostalCode = '1234';
        acc.BillingCountry = 'sdfascvv';
        acc.ShippingStreet = 'sdfascvv';
        acc.ShippingCity = 'sdfascvv';
        acc.ShippingState = 'sdfascvv';
        acc.ShippingPostalCode = '1234';
        insert acc;
        Contact cont = new Contact();
        cont.AccountId = acc.Id;
        cont.LastName = 'TEST LASTNAME';
        cont.OtherStreet = 'sdfascvv';
        cont.OtherCity = 'sdfascvv';
        cont.OtherState = 'sdfascvv';
        cont.OtherStreet = '1234';
        insert cont;
        acc.RecordTypeId = [Select id from RecordType where DeveloperName = 'Non_Residential_Company_Customer' and SObjectType = 'Account'][0].id;
        update acc;
        PageReference pageRef = Page.CreateBillingAccountWizard;
        pageRef.getParameters().put('propertyId',prop.id);
        pageRef.getParameters().put('customerId',acc.id);
        pageRef.getParameters().put('isWHK', 'true');
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(new Billing_Account__c());
        CreateBillingAccountWizardExCon excon = new CreateBillingAccountWizardExCon(stdCon);
        System.assertEquals(false, excon.isStepTwo);
        System.assertEquals(false, excon.isGroupBillAcc);
        System.assertEquals(false, excon.isBillAcc);
        System.assertEquals(false, excon.isAdHoc);
        for(SelectOption option: excon.billAccRecordTypeSelections){
            if('Group Billing Account'.equals(option.getLabel())){
                excon.currentBillAcc.recordTypeId = option.getValue();
            }
        }
        excon.updateBillAccRecordType();
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Customer Mailing';
        excon.updateBillAddSame();
        
        acc.RecordTypeId = [Select id from RecordType where DeveloperName = 'Residential' and SObjectType = 'Account'][0].id;
        update acc;
        excon.updateBillAddSame();
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Customer Primary';
        excon.updateBillAddSame();
        
        acc.RecordTypeId = [Select id from RecordType where DeveloperName = 'Non_Residential_Company_Customer' and SObjectType = 'Account'][0].id;
        update acc;
        excon.updateBillAddSame();
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Customer Primary';
        excon.updateBillAddSame();
        
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Customer Primary';
        excon.updateBillAddSame();
        acc.ShippingStreet = null;
        acc.ShippingCity = null;
        acc.ShippingState = null;
        acc.ShippingPostalCode = null;
        update acc;
        excon.updateBillAddSame();
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Property';
        excon.updateBillAddSame();
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Other';
        excon.updateBillAddSame();
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Group Account';
        excon.updateBillAddSame();
        excon.currentBillAcc.Billing_Address_Same_As__c = null;
        excon.updateBillAddSame();
        excon.currentBillAcc.Street_Address__c = null;
        excon.currentBillAcc.State__c = null;
        excon.currentBillAcc.City__c = null;
        excon.currentBillAcc.Postal_Code__c  = null;
        excon.currentBillAcc.Street_Address__c = null;
        System.assertEquals(true, excon.isStepTwo);
        System.assertEquals(true, excon.isGroupBillAcc);
        System.assertEquals(false, excon.isBillAcc);
        System.assertEquals(false, excon.isAdHoc);
        for(SelectOption option: excon.billAccRecordTypeSelections){
            if('Ad-Hoc'.equals(option.getLabel())){
                excon.currentBillAcc.recordTypeId = option.getValue();
            }
        }
        excon.updateBillAccRecordType();
        System.assertEquals(true, excon.isStepTwo);
        System.assertEquals(false, excon.isGroupBillAcc);
        System.assertEquals(false, excon.isBillAcc);
        System.assertEquals(true, excon.isAdHoc);
        for(SelectOption option: excon.billAccRecordTypeSelections){
            if('Billing Account'.equals(option.getLabel())){
                excon.currentBillAcc.recordTypeId = option.getValue();
            }
        }
        excon.updateBillAccRecordType();
        System.assertEquals(true, excon.isStepTwo);
        System.assertEquals(false, excon.isGroupBillAcc);
        System.assertEquals(true, excon.isBillAcc);
        System.assertEquals(false, excon.isAdHoc);
        excon.submit();
        System.assertEquals(false, excon.createSuccessful);
        List<SelectOption> temp = excon.billAddressSameAsSelections;
        excon.currentBillAcc.Same_Name_As_Customer__c = true;
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Customer Mailing';
        excon.submit();
        System.assertEquals(true, excon.createSuccessful);
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Customer Primary';
        excon.submit();
        System.assertEquals(true, excon.createSuccessful);
        excon.currentBillAcc.Billing_Address_Same_As__c = 'Property';
        excon.submit();
        System.assertEquals(true, excon.createSuccessful);
        excon.noOfBillAccsToCreate = 2;
        pageRef = excon.submit();
        System.assertEquals(true, excon.createSuccessful);
        excon.viewCreatedRecord();
        String url = excon.accountListUrl;
        url = excon.retURL;
        //Test.setCurrentPage(pageRef);
        //stdCon = new ApexPages.StandardController([Select id from Billing_Account__c where id = :pageRef.getParameters().get('id')]);
        //excon = new CreateBillingAccountWizardExCon(stdCon);
        //System.assertEquals(2, excon.noOfBillAccsToCreate);

        TibcoCreateBillingAccount_MessageType.ErrorStatus_element  err = new TibcoCreateBillingAccount_MessageType.ErrorStatus_element();
    }
}