sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>When the Future Address details become applicable</description>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Applicable_Date__c</fullName>
        <label>Applicable Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Change Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Contact Type</description>
        <inlineHelpText>This field contains information that is parsed to BRE for SMR Cases.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FutureStreetAddress__c</fullName>
        <label>Future Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Address_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag which is set by time based workflow to check the box when the &apos;Applicable Date&apos; is reached. This will fire a trigger to copy the Future Address to the Billing Account</description>
        <label>Future Address Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_Read__c</fullName>
        <label>Type of Read</label>
        <picklist>
            <controllingField>Contact_Type__c</controllingField>
            <picklistValues>
                <fullName>Tenant Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Reading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/TestPortalCaseView_Controller.cls
/*
    Type:       TestMethod class
    Purpose:    Test the PortalCaseView_Controller class 			

    Used By:    PortalCaseView.page
    ---------------------------------------------------------------
    History:

    29-Oct-2013 N.Patterson				Created as part of TT10401 - Allow for multiple customers/users linked
*/
@isTest
private class TestPortalCaseView_Controller {

    static testMethod void myUnitTest() {
    	// Create a case
    	// create account
        Account a = new Account(name='ABC');
        insert a;

        // create billing account
        Billing_Account__c bill = new Billing_Account__c();
        bill.Customer__c = a.id;
        bill.Street_Address__c = '1234 Street';
        insert bill;

        // create case with future street address, applicable date and change billing address flag checked
        Case c1 = new Case (RecordTypeId = CaseUtil.SMR_RECORDTYPE_ID, Billing_Account__c = bill.id, 
                                Contact_Type__c = 'Vendor', Type_of_Read__c = 'Move Out',
                                Change_Billing_Address__c = true, Applicable_Date__c = system.today(),
                                FutureStreetAddress__c = '5678 Street', Future_Address_Process__c = true); 
    	insert c1;
    	
    	// test for no parameters
        PortalCaseView_Controller pcv = new PortalCaseView_Controller();
        System.assert(pcv.caseView != null);
        System.assert(pcv.caseView.Id == null);
        
        // Test for an invalid parameter
        PageReference pageRef = Page.PortalCaseView;
        Test.setCurrentPage(pageRef);
        String newId = c1.id;
        newId = newId.left(newId.length()-6) + 'ZZZZZZ';
        ApexPages.currentPage().getParameters().put('id', newId);
        pcv = new PortalCaseView_Controller();
        System.assert(pcv.caseView == null);
        // Test for an valid parameter
        pageRef = Page.PortalCaseView;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', c1.id);
        pcv = new PortalCaseView_Controller();
        System.assert(pcv.caseView != null);
        System.assertEquals(pcv.caseView.Id, c1.id);
        
    }
}