sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Concession_cnt__c</fullName>
        <label>Concession cnt</label>
        <summarizedField>Billing_Account__c.Concession_cnt__c</summarizedField>
        <summaryForeignKey>Billing_Account__c.Customer__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Account_Address__c</fullName>
        <formula>Street_Address__c &amp;br()&amp; City__c &amp;&quot; &quot;&amp; State__c &amp;&quot; &quot;&amp; Postal_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_Formula__c</fullName>
        <formula>IF(ISBLANK(Title__c), &apos;&apos;, Title__c + &apos; &apos;) +  IF(ISBLANK(Initials__c), &apos;&apos;, Initials__c+ &apos; &apos;) +  Account_Name__c</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Average_Daily_Water_Usage_KL__c</fullName>
        <formula>Total_Water_Usage_KL__c /  Total_Consumption_Days__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Average Daily Water Usage (KL)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <formula>Property__r.CIS_Property_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS Property Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Concession_cnt__c</fullName>
        <formula>IF( Valid_Concession__c , 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Concession_cnt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Bill_Due_Date__c</fullName>
        <label>Current Bill Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Customer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Direct_Debit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct Debit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number_Check_Digit__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account Number (Check Digit)</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Payment_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Bill_Date__c</fullName>
        <label>Last Bill Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Bill_Number__c</fullName>
        <label>Last Bill Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Made__c</fullName>
        <label>Last Payment Made</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Next_Bill_Date__c</fullName>
        <label>Next Bill Date (Approx)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Overdue_Amount_Formula__c</fullName>
        <formula>IF(
	OR(Balance__c &lt;= 0, Is_Payment_Plan__c=TRUE, Direct_Debit__c=TRUE, Recovery_Suspended_Date__c &gt;= TODAY())
	, 0
	, IF(Balance__c &lt;= Current_Bill_Billed_Amount__c
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
			, Balance__c
			, 0)
		, IF(Current_Bill_Due_Date__c &lt; TODAY()
				, Balance__c
				, IF(Balance__c &lt; Current_Bill_B_F_Balance__c
					,Balance__c
					,Current_Bill_B_F_Balance__c)
				)
			
		)
	)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overdue Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Sort_Order__c</fullName>
        <description>Controls the order the account is displayed in portal</description>
        <formula>CASE( Status__c , &apos;Active&apos;, 1, &apos;Pending&apos;, 2, 3)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Portal Sort Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>Property__r.Street_Address__c &amp; br() &amp; Property__r.Suburb__c &amp;&quot; &quot;&amp; text( Property__r.State__c)&amp;&quot; &quot;&amp; Property__r.Postal_Code__c</formula>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Id__c</fullName>
        <formula>Property__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recipient_Email__c</fullName>
        <formula>eBill_Recipient__r.Email</formula>
        <label>Recipient Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recovery_Suspended_Date__c</fullName>
        <description>Shows the date suspend recovery was applied until</description>
        <inlineHelpText>Shows the date suspend recovery was applied until</inlineHelpText>
        <label>Recovery Suspended To Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>eBill_Method__c</fullName>
        <label>eBill Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BPAY View</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Consumption_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Account_Periodic_Consumption_and_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Read_Date__c</fullName>
        <description>Current consumption meter read date.</description>
        <inlineHelpText>Current consumption meter read date.</inlineHelpText>
        <label>Current Read Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <description>Number of days in the consumption period (based on meter read dates)</description>
        <inlineHelpText>Number of days in the consumption period (based on meter read dates)</inlineHelpText>
        <label>Number of Days</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebilled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exception Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Water_Volume__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Water Volume (KL)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Consumption and Charge</label>
    <nameField>
        <label>Consumption Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumption and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>DP_Key__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Duplicate Person Key</label>
        <referenceTo>Duplicate_Person_Key__c</referenceTo>
        <relationshipLabel>Duplicate Person Records</relationshipLabel>
        <relationshipName>DP_Records</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Meter_Location__c</fullName>
        <description>Shows the meter location on the house in an image form</description>
        <formula>IF(Location_Code__c == &quot;99&quot;, &quot;No Meter&quot;,
IMAGE(  &quot;https://southeastwater--c.ap1.content.force.com&quot; +
CASE(  LEFT(Location_Code__c , 1),
&quot;0&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mB4&quot;, 
&quot;1&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAo&quot;,
&quot;2&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAt&quot;,
&quot;3&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAy&quot;,
&quot;4&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAu&quot;,
&quot;5&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mB3&quot;,
&quot;6&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mB8&quot;,
&quot;7&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mBD&quot;,
&quot;8&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mBI&quot;,
&quot;9&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mBN&quot;,
&quot;/servlet/servlet.ImageServer?id=015900000003GOp&quot;) + &quot;&amp;oid=00DO0000000W4pz&quot; 
, &quot;Meter Image&quot;))</formula>
        <label>Meter Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <description>Property reference number in HiAF</description>
        <externalId>true</externalId>
        <label>CIS Property Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WS_RetrieveCustomerBillingAccounts.cls
/*
    Type:       Webservice extension class
    Purpose:    Process the Retrieve Customer Billing Accounts request from the Webservice call

    Used By:    CustomerWebService_1_0.class
    ---------------------------------------------------------------
    History:
    10-May-13   N.Patterson         Created
    23-Sep-13   N.Patterson		    TT11239 - No longer show Pending or closed (with $0 balance) Accounts in the Portal
    23-Sep-13	N.Patterson			TT10401 - Be able to view billing accounts linked to another customer and set the class to "without sharing" 
*/

public without sharing class WS_RetrieveCustomerBillingAccounts {
	public static List<CustomerWebService_1_0.BillingAccountResult> retrieveCustomerBillingAccounts(){
		System.debug(System.LoggingLevel.DEBUG, 'WS_RetrieveCustomerBillingAccounts.retrieveCustomerBillingAccounts(userid): ' + UserInfo.getUserId());
		List<CustomerWebService_1_0.BillingAccountResult> resultList = new List<CustomerWebService_1_0.BillingAccountResult> ();
		
		Set <Id> accountIdList = new Set<Id>();  // Set of account Ids for the user
		Set <Id> dpKeyIdSet = new Set<Id>();  // TT10401 - Set of Duplicate Key Ids for the user
		
		for (User u: [Select Id, Contact.AccountId , ContactId, Contact.DP_Key__c From User Where id = :UserInfo.getUserId()]){
			if (u.ContactId != null){
            	accountIdList.add(u.Contact.AccountId);
			}
			System.debug('u:' + u);
			// TT10401 - Get the Duplicate Key Ids for the user's contact
			if (u.Contact != null && u.Contact.DP_Key__c != null){
				if (!dpKeyIdSet.contains(u.Contact.DP_Key__c)){
					dpKeyIdSet.add(u.Contact.DP_Key__c);
				}
				
			}
        }
        System.debug('dpKeyIdSet:' + dpKeyIdSet);
        System.debug('accountIdList:' + accountIdList);
        // TT10401 - Add the Accounts to the list for the persons who have that Duplicate Key
        if(!dpKeyIdSet.isEmpty()){
	        for (Contact c: [Select Id, AccountId From Contact Where DP_Key__c in :dpKeyIdSet]){
	        	System.debug('c:' + c);
				if (c.AccountId != null && !accountIdList.contains(c.AccountId)){
	            	accountIdList.add(c.AccountId);
				}
	        }
        }
        
		if (accountIdList.isEmpty()){
			resultList.add(createEmptyResult('User has no person or customer record'));
		}
		else {
			List<Billing_Account__c> baList = [SELECT Account_Address__c, Is_Payment_Plan__c, Next_Bill_Date__c, Concession_cnt__c, Account_Name_Formula__c, Account_Name__c, HiAF_Account_Number_Check_Digit__c, 
            										Average_Daily_Water_Usage_KL__c, Balance__c, Customer_Name__c, Last_Bill_Date__c, Property_Address__c, Status__c, Property_Id__c, CIS_Property_Id__c, Property__c,
            										Last_Bill_Number__c, Last_Payment_Made__c, Last_Payment_Date__c, Payment_Method__c, Current_Bill_Due_Date__c, eBill_Method__c, Recipient_Email__c, Direct_Debit__c, 
            										Recovery_Suspended_Date__c, Overdue_Amount_Formula__c
                                        FROM Billing_Account__c WHERE Customer__c IN :accountIdList AND (Status__c = 'Active' OR (Status__c = 'Closed' AND (LastModifiedDate >= :System.now().addYears(-1) OR (Balance__c != 0 AND Balance__c != null))))
                                        ORDER BY Portal_Sort_Order__c, HiAF_Account_Number_Check_Digit__c];

            if (baList == null || baList.size() == 0){
                resultList.add(createEmptyResult('User has no billing accounts'));
            }
			else {
	            for (Billing_Account__c ba: baList){
	            	CustomerWebService_1_0.BillingAccountResult bar = new CustomerWebService_1_0.BillingAccountResult();
	            	bar.billingAccount = ba;
	            	if (ba.Property__c != null){
	            		bar.propertyMeterList = [SELECT Id, Name, Meter_Location__c  
	            									FROM Meter_Details__c  
	            									WHERE Property__c = :ba.Property__c];
	            	}
					
					if (ba.HiAF_Account_Number_Check_Digit__c != null && ba.Last_Bill_Number__c != null){
						BillViewExCon vbm = new BillViewExCon('No', ba.HiAF_Account_Number_Check_Digit__c, ba.Last_Bill_Number__c);
			            PageReference pr = vbm.billView();
			            if (pr != null){
			            	bar.lastBillURL = pr.getURL(); 
			            }
			            else {
			            	bar.lastBillURL = '';
			            }
					}
					else {
						bar.lastBillURL = '';
					}
					System.debug(System.LoggingLevel.DEBUG, 'bar.lastBillURL: ' + bar.lastBillURL);
					// Get latest consumption and charge so that we can populate the AverageDailyWaterUsageKL field without querying HiAf
	            	List<Consumption_and_Charge__c> consumptionList = [SELECT Billing_Account__c, Current_Read_Date__c, Water_Volume__c, Number_of_Days__c 
	            														FROM Consumption_and_Charge__c 
	            														Where Billing_Account__c = :ba.Id
	            														  and Current_Read_Date__c != null 
	            														ORDER BY Current_Read_Date__c desc LIMIT 1];
	            														
					if (!(consumptionList.isEmpty())){
						if (consumptionList[0].Number_of_Days__c > 0){
							Decimal avgDailyConsumption = consumptionList[0].Water_Volume__c * 1000;
							bar.currentAverageDailyUsageL = (((consumptionList[0].Water_Volume__c * 100000.00 / consumptionList[0].Number_of_Days__c).round()) / 100);
							System.debug(System.LoggingLevel.DEBUG, 'avgDailyConsumption: ' + avgDailyConsumption + '\n consumptionList[0].Number_of_Days__c: ' + consumptionList[0].Number_of_Days__c);
						}
						else if (consumptionList[0].Number_of_Days__c == 0){
							bar.currentAverageDailyUsageL = 0;
						}
						System.debug(System.LoggingLevel.DEBUG, 'bar.currentAverageDailyUsageL: ' + bar.currentAverageDailyUsageL);
					}
		            resultList.add(bar);
	            }
			}
		}
		
		return resultList;
	}
	
	private static CustomerWebService_1_0.BillingAccountResult createEmptyResult (String messageText){
		System.debug(System.LoggingLevel.ERROR, '\nWS_RetrieveCustomerBillingAccounts empty result: ' + messageText + '\nUser: ' + Userinfo.getUserName() + ', ' + UserInfo.getSessionId() + ', ' + UserInfo.getUserId());
		CustomerWebService_1_0.BillingAccountResult bar = new CustomerWebService_1_0.BillingAccountResult();
		bar.billingAccount = null;
		bar.propertyMeterList = new List<Meter_Details__c> ();
		bar.lastBillURL = '';
		bar.currentAverageDailyUsageL = null;
		bar.messageText = messageText;
		return bar;
	}
}