sample/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Trading_Name__c</fullName>
        <label>Trading Name</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Trading_Name__c</fullName>
        <formula>Customer__r.Trading_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trading Name</label>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <inlineHelpText>What is the case or activity about?</inlineHelpText>
        <label>What</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Payments &amp; Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Reform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_2__c</fullName>
        <inlineHelpText>Why is the case or activity occurring?</inlineHelpText>
        <label>Why</label>
        <picklist>
            <controllingField>Category_Level_1__c</controllingField>
            <picklistValues>
                <fullName>Account/Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns &amp; Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Recovery Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Receive Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficiency Programs &amp; Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Explanation of Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot Issues - Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Statement Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Readings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In / Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Customer/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Off/On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Restrictions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Injury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tappings/Pluggings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_3__c</fullName>
        <inlineHelpText>The solution, the response, the process - the case creation</inlineHelpText>
        <label>How</label>
        <picklist>
            <controllingField>Category_Level_2__c</controllingField>
            <picklistValues>
                <fullName>Acceptance of Works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access to Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Balance/Due Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Amend Concession Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Hoc Billing Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Meter Reading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Property Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog Sewer Charges Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Debt Recommendation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy and  Liquidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build overs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Opt In/Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caveat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Occupier Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check for Tampering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent to connect Water or Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Classifaction Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read Taken</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>New field added to have a higher level categorisation of the case by business function. Currently only used by Portal, but can be reused at a later date.</description>
        <label>Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Article Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession - Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Statement Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merge Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Time To Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Time To Pay Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice of Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration Name Match</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Meter Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession - Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Reading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Trading_Name__c</fullName>
        <formula>Account.Trading_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Trading Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>HIDDEN_Confirmed_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(Hidden) Confirmed Portal User</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalNameChangeWizard_ExCon.cls
/*
    Type:       Controller
    Purpose:    Portal wizard to support Epic 122 Request Customer Name Change functionality for Portal users

    Used By:    PortalNameChangeWizard.page
    ---------------------------------------------------------------
    History:
    02-Apr-2012 M.Erwin (Salesforce)	Created - per Epic 122
    12-Nov-2012 D.Thong - populate case subtype field
    25-Oct-2013 N.Patterson - TT10401 - Multiple customer view
    25-Feb-2014 N.Patterson             Moving test methods to a test class to reduce code usage

*/
public with sharing class PortalNameChangeWizard_ExCon extends PortalPageWithCase_Virtual_Con {

	/* CONSTANTS */
	public final static String SPELLING_ERROR = 'SpellingError';
	public final static String LEGAL_NAME_CHANGE = 'LegalNameChange';
	public final static String ERROR_DOCS_LESS_5MB = 'Documents must be less than 5MB';
	public final static String ERROR_NO_DOC_SELECTED = 'No document selected.';
	public final static Integer MAX_ATTACHMENT_SIZE = 5242880; // 5MB = 1024 * 1024 * 5

	/* CONSTRUCTORS */
	public PortalNameChangeWizard_ExCon() {
		attachment = new Attachment();
		step='new';
		if (customerList != null && customerList.size() == 1){
			selectedCustomer = customerList[0].id;
			customer = CustomerUtil.getCustomerDetails(selectedCustomer);
			step='edit';
		}
			
	}

	/* PRIVATE PROPERTIES */

	/* PUBLIC PROPERTIES */
	/*public User curUser {get;set;}

	// Check that the user is not a confirmed portal user
	public PageReference CheckRedirectConfirmed() {
		curUser = [Select Id, HIDDEN_Confirmed_Portal_User__c from User where Id =: UserInfo.getUserId()];
		if (curUser.HIDDEN_Confirmed_Portal_User__c != true) { 
			return Page.PortalUserConfirmation.setRedirect(true);		
		}
		return null;
	}*/
	
	public Attachment attachment { get; set; }
	transient public Blob attachmentBody { get; set; }

	public String firstName {
		get {
			if (firstName == null) {
				firstName = userContact.FirstName;
			}
			return firstName;
		}
		set;
	}
	public String lastName {
		get {
			if (lastName == null) {
				lastName = userContact.LastName;
			}
			return lastName;
		}
		set;
	}
	public String customerName {
		get {
			if (customerName == null) {
				customerName = customer.Name;
			}
			return customerName;
		}
		set;
	}
	public String tradingName {
		get {
			if (tradingName == null) {
				tradingName = customer.Trading_Name__c;
			}
			return tradingName;
		}
		set;
	}

	public String reasonForChange { get; set; }
	public String reasonForChangeLong { get; set; }
	
	public String selectedCustomer {get; set;} // TT10401 - Keep track of selected customer
	
	public String step {
		get {
			if (step == null) {
				step = 'edit';
			}
			return step;
		}
		set;
	}

	/* PRIVATE METHODS */

	/* PUBLIC METHODS */
	public PageReference returnToMyDetails() {
		return Page.PortalMyDetails;
	}
	public override PageReference submit() {
				
        // Populate Case fields
		caseRec.Type = 'Group Billing & Accounts';
		caseRec.Category_Level_1__c = 'Customer Details';
		caseRec.Category_Level_2__c = 'Update Customer/Person';
		caseRec.Category_Level_3__c = 'Update Name';
		caseRec.Mode__c = 'Action';
		caseRec.Status = 'In Progress';
		caseRec.RecordTypeId = PortalPageWithCase_Virtual_Con.GENERALENQUIRY_RECORDTYPEID;
		caseRec.OwnerId = user.Id;
		
		Map<Id, Contact> customerContactMap = CustomerUtil.getCustomersLinkedToPersons(userContact.Id); 
		
		caseRec.ContactId = customerContactMap.get(customer.Id).Id;
		caseRec.AccountId = customer.Id;
		caseRec.Billing_Account__c = null;

		// DT - 12-Nov-2012 - populate subtype
		caseRec.Sub_Type__c = 'Customer Details';
        
        // Populate Case Description with name change details
		caseRec.Description = 'Name change request:\n';
		caseRec.Description += 'Name details before change:\n';
		caseRec.Description += 'First Name: ' + userContact.FirstName + '\n';
		caseRec.Description += 'Last Name: ' + userContact.LastName +'\n';
		caseRec.Description += 'Customer Name: ' + customer.Name +'\n';
		caseRec.Description += 'Trading Name: ' + customer.Trading_Name__c +'\n';
		caseRec.Description += '\n';
		caseRec.Description += 'Name details after change:\n';
		caseRec.Description += 'First Name: ' + firstName +'\n';
		caseRec.Description += 'Last Name: ' + lastName +'\n';
		caseRec.Description += 'Customer Name: ' + customerName +'\n';
		caseRec.Description += 'Trading Name: ' + tradingName +'\n';
		// TODO: (which fields changed - if time).
		caseRec.Description += '\n';
		caseRec.Description += 'Chosen reason: ' + reasonForChange +'\n';
		if (reasonForChange == LEGAL_NAME_CHANGE) {
			caseRec.Description += 'Detailed reason: ' + reasonForChangeLong +'\n';
		}

        // call super to insert Case
        if (super.submit() != null) {
            submitted=true;
        }
        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: reasonForChange: ' + reasonForChange);
		if (reasonForChange == LEGAL_NAME_CHANGE && caseRec.Id != null) {

	        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: attachment.Name: ' + attachment.Name);
			// validate attachment name exists
	        if (attachment.Name == null ) {
	            apexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, ERROR_NO_DOC_SELECTED);
	            apexPages.addMessage(msg);
	            return null;
	        }

	        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: attachment.BodyLength: ' + attachment.BodyLength);
			// validate attachment size < 5MB
	        if (attachment.BodyLength > MAX_ATTACHMENT_SIZE || attachmentBody.size() > MAX_ATTACHMENT_SIZE) {
	            apexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, ERROR_DOCS_LESS_5MB);
	            apexPages.addMessage(msg);
	            return null;
	        }

			// insert attachment
	        attachment.Body = attachmentBody;
	        attachment.ParentId = caseRec.Id;
	        attachment.Description = 'Supporting legal documentation for Name Change request';
	
	        System.debug(System.LoggingLevel.DEBUG, '##DEBUG: attachment prior to insert: ' + attachment);
	        try {
	            //TT10401 insert attachment;
	            PortalUtil.insertAttachment(attachment);
	        } catch (Exception e) {
	            ApexPages.addMessages(e);
	        } finally {
	            attachment.body = null; // avoids view state issues
	            attachment = new Attachment();
	        }
		}
		
		step = 'confirmation';
		return null;
	}
	
	//TT10401 - When the drop list is updated
    public PageReference changeSelectedCustomer(){
    	System.debug('selectedCustomer:' + selectedCustomer);
    	if (selectedCustomer != '' && selectedCustomer != null){
	    	customer = CustomerUtil.getCustomerDetails(selectedCustomer);
	    	customerName = customer.Name;
	    	step='edit';
    	}
    	else {
    		step='new';
    	}
    	return null;
    }
    //TT10401 - When the drop list is updated
    public List<SelectOption> customerOptionList{
        get{
            if(customerOptionList==null){
                customerOptionList= new List<SelectOption>();
                customerOptionList.add(new SelectOption('', 'Select Account'));
                for(Account a: customerList){
                    customerOptionList.add(new SelectOption(a.id, a.name));
                    
                }
            }return customerOptionList;
        }
        private set;
    }


	
}