sample/retrieveUnpackaged/objects/Bad_Debt__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>MaxThreshold__c</fullName>
        <label>Max Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinThreshold__c</fullName>
        <label>Min Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NumDays__c</fullName>
        <label>Number of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cust Verification - Bad Debt</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Clerical__c</fullName>
        <label>Clerical</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recovery_Path__c</fullName>
        <label>Recovery Path</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Budget__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AllowedArrears__c</fullName>
        <label>Allowed Arrears</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ReviewDateThreshold__c</fullName>
        <label>Review Date Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cust Verification - Budget</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recovery_Path__c</fullName>
        <label>Recovery Path</label>
        <picklist>
            <picklistValues>
                <fullName>D1 - RESIDENTIAL 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2 - RESIDENTIAL 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D3 - TENANT USAGE - RES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PD - Parks and Drainage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N1 - NON RESIDENTIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N2 - Non Res Serv Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N3 - NON RES USAGE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>The first 255 characters of the full description will be automatically copied here.</description>
        <inlineHelpText>If blank , the first 255 characters of the full description will be automatically copied here.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used on Classfication Codes button.</description>
    <label>Classification</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification_Code__c.object
<CustomObject>
    <description>Classification codes for customers</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description for the customer classification</description>
        <inlineHelpText>Short Description for the customer classification</inlineHelpText>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Classification Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Clerical__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of clericals for Customer Verification</description>
    <fields>
        <fullName>Check_Type__c</fullName>
        <inlineHelpText>Must be one of the following values: 
0 - Alert 
1 - Warning 
2 - Informational 
3 - Not Checked</inlineHelpText>
        <label>Check Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cust Verification - Clerical</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Customer_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Warnings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Person_Customer_Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Person_Customer_Relations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Person_Customer_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Third_Party_Type__c</fullName>
        <label>Third Party Type</label>
        <picklist>
            <picklistValues>
                <fullName>Real Estage Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Power of Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owners Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Third Party Relationship</label>
    <nameField>
        <displayFormat>Link-{000000000}</displayFormat>
        <label>3rd Party</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Third Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Recovery_Path__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>List of clericals for customer verification</description>
    <fields>
        <fullName>Check_Type__c</fullName>
        <inlineHelpText>Must be one of the following values:
0 - Alert
1 - Warning
2 - Informational
3 - Not Checked</inlineHelpText>
        <label>Check Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cust Verification - Recovery Path</label>
</CustomObject>

sample/retrieveUnpackaged/classes/SObjectCreator_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class SObjectCreator
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class SObjectCreator_Test {

    public static testMethod void testInsertBudgetCustomSetting(){
        Budget__c BudgetCustomSetting = SObjectCreator.createBudgetCustomSetting();
        BudgetCustomSetting.AllowedArrears__c = 30;
        BudgetCustomSetting.ReviewDateThreshold__c = 42;
        try {
            insert BudgetCustomSetting;
        } catch (Exception e) {}
    }
    
    public static testMethod void testInsertPersonCustomerRelationship(){
        Account AccountResidentialObject1 = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialObject1;

        Account AccountResidentialObject2 = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialObject2;

        Contact ContactObject = SObjectCreator.createContact();
        ContactObject.AccountId = AccountResidentialObject1.Id;
        insert ContactObject;

        Person_Customer_Relationship__c PersonCustomerRelationshipObject = SObjectCreator.createPersonCustomerRelationship();
        PersonCustomerRelationshipObject.Customer__c = AccountResidentialObject2.Id;
        PersonCustomerRelationshipObject.Person__c = ContactObject.Id;
        PersonCustomerRelationshipObject.Third_Party_Type__c = 'Third Party';
        insert PersonCustomerRelationshipObject;
    }
    
     public static testMethod void testInsertBadDebtCustomSetting(){
        Bad_Debt__c BadDebtCustomSetting = SObjectCreator.createBadDebtCustomSetting();
        BadDebtCustomSetting.MaxThreshold__c = 200;
        BadDebtCustomSetting.MinThreshold__c = 50;
        BadDebtCustomSetting.NumDays__c = 183;
        try {
            insert BadDebtCustomSetting;
        } catch (Exception e) {}
    }
    
    public static testMethod void testInsertRecoveryPathCustomSetting(){
        Recovery_Path__c RecoveryPathCustomSetting = SObjectCreator.createRecoveryPathCustomSetting();
        RecoveryPathCustomSetting.Short_Description__c = 'Test Short';
        RecoveryPathCustomSetting.Message__c = 'Test Message';
        RecoveryPathCustomSetting.Check_Type__c = '0 - Alert';
        insert RecoveryPathCustomSetting;
    }
    
    public static testMethod void testInsertClericalCustomSetting(){
        Clerical__c ClericalCustomSetting = SObjectCreator.createClericalCustomSetting();
        ClericalCustomSetting.Message__c = 'Test Message';
        ClericalCustomSetting.Short_Description__c = 'Test Short';
        ClericalCustomSetting.Check_Type__c = '0 - Alert';
        insert ClericalCustomSetting;
    }
    
    public static testMethod void testInsertAccountResidentialCustomer(){
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        //## Required Relationships

        //## Additional fields and relationships / Updated fields
        insert AccountResidentialCustomerObject;
    }
    
    public static testMethod void testInsertAccountNonResidentialIndividual(){
        Account AccountNonResidentialIndividualObject = SObjectCreator.createAccountNonResidentialIndividual();
        //## Required Relationships

        //## Additional fields and relationships / Updated fields
        insert AccountNonResidentialIndividualObject;
    }
    
    public static testMethod void testInsertAccountNonResidentialCompany(){
        Account AccountNonResidentialCompanyObject = SObjectCreator.createAccountNonResidentialCompany();
        //## Required Relationships

        //## Additional fields and relationships / Updated fields
        insert AccountNonResidentialCompanyObject;
    }
    
    public static testMethod void testInsertContact(){
        Contact ContactObject = SObjectCreator.createContact();
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;
        ContactObject.AccountId = AccountResidentialCustomerObject.Id;
        insert ContactObject;
    }
    
    public static testMethod void testInsertBillingAccountAdhoc(){
        Billing_Account__c BillingAccountAdHocObject = SObjectCreator.createBillingAccountAdHoc();
        //## Required Relationships
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;
        BillingAccountAdHocObject.Customer__c = AccountResidentialCustomerObject.Id;
        insert BillingAccountAdHocObject;
    }
    
    public static testMethod void testInsertBillingAccountBillingAccount(){
        Billing_Account__c BillingAccountBillingAccountObject = SObjectCreator.createBillingAccountBillingAccount();
        //## Required Relationships
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;
        BillingAccountBillingAccountObject.Customer__c = AccountResidentialCustomerObject.Id;
        insert BillingAccountBillingAccountObject;
    }
    
    public static testMethod void testInsertBillingAccountGroupBillingAccount(){
        Billing_Account__c BillingAccountGroupBillingAccountObject = SObjectCreator.createBillingAccountGroupBillingAccount();
        //## Required Relationships
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;
        BillingAccountGroupBillingAccountObject.Customer__c = AccountResidentialCustomerObject.Id;
        insert BillingAccountGroupBillingAccountObject;
    }
    
    public static testMethod void testInsertProperty(){
        Property__c PropertyObject = SObjectCreator.createProperty();
        insert PropertyObject;
    }
    
    public static testMethod void testInsertCaseInfoStatementUpdate(){
        Case CaseInfoStatementUpdateObject = SObjectCreator.createCaseInfoStatementUpdate();
        //## Required Relationships
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;
        Billing_Account__c BillingAccountBillingAccountObject = SObjectCreator.createBillingAccountBillingAccount();
        BillingAccountBillingAccountObject.Customer__c = AccountResidentialCustomerObject.Id;
        insert BillingAccountBillingAccountObject;
        CaseInfoStatementUpdateObject.AccountId = AccountResidentialCustomerObject.Id;
        CaseInfoStatementUpdateObject.Billing_Account__c = BillingAccountBillingAccountObject.Id;
        insert CaseInfoStatementUpdateObject;
    }
    
    public static testMethod void testInsertCaseNoticeOfSale(){
        Case CaseNoticeOfSaleObject = SObjectCreator.createCaseNoticeOfSale();
        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;
        Billing_Account__c BillingAccountBillingAccountObject = SObjectCreator.createBillingAccountBillingAccount();
        BillingAccountBillingAccountObject.Customer__c = AccountResidentialCustomerObject.Id;
        insert BillingAccountBillingAccountObject;
        CaseNoticeOfSaleObject.AccountId = AccountResidentialCustomerObject.Id;
        CaseNoticeOfSaleObject.Billing_Account__c = BillingAccountBillingAccountObject.Id;
        insert CaseNoticeOfSaleObject;
    }
    
    public static testMethod void testInsertClassificationCode(){
        Classification_Code__c ClassificationCodeObject = SObjectCreator.createClassificationCode();
        insert ClassificationCodeObject;
    }
    
    public static testMethod void testInsertCustomerClassification(){
        Customer_Classification__c CustomerClassificationObject = SObjectCreator.createCustomerClassification();

        Account AccountResidentialCustomerObject = SObjectCreator.createAccountResidentialCustomer();
        insert AccountResidentialCustomerObject;

        Classification_Code__c ClassificationCodeObject = SObjectCreator.createClassificationCode();
        insert ClassificationCodeObject;

        CustomerClassificationObject.Customer__c = AccountResidentialCustomerObject.Id;
        CustomerClassificationObject.Classification__c = ClassificationCodeObject.Id;
        insert CustomerClassificationObject;
    }
    
}