sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Meter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag field that determines if a property belongs to digital meter trial.</description>
        <label>Digital Meter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile_Setup_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Profile Setup Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/DMTrialMainCCTest.cls
/*
*created by: Bryan Trinidad
*created date: February 04, 2014
*description: test class for DMTrialMainCC class
*/
@isTest
private class DMTrialMainCCTest {
  
    //DMTrialMainCC test method
    static testMethod void dmTrialMainTest() {
        DMTrialMainCC con = new DMTrialMainCC();
        //create customer
        Account acct = PortalTestHelper.createResiCustomer();
        system.assertEquals(acct != null,true);
        
        //create contact
        Contact cont = PortalTestHelper.createContact(acct);
        system.assertEquals(cont != null,true);
        
        //create user
        User portalUser = PortalTestHelper.createUser(cont);
        system.assertEquals(portalUser != null,true);
        
        //create property
        Property__c prop = PortalTestHelper.createProperty();       
        system.assertEquals(prop != null,true);

        
        //insert billing account
        Billing_Account__c billAcct = PortalTestHelper.createBillingAccount(acct,prop,'19999999');
        system.assertEquals(billAcct != null,true);
        Test.startTest();
            
            System.runAs(portalUser) {
                con.profileBlock();
            }
            
            //update property
            prop.Digital_Meter__c = true;
            prop.Profile_Setup_Complete__c = false;
            update prop;
            
            //run method again
            System.runAs(portalUser) {
                con.profileBlock();
            }
        Test.stopTest();
    }
}