sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WaterMAP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WaterMAP</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>Watermap</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>The customer who is actually responsible for paying usage charges to SEW</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>WaterMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KBAI_Description__c</fullName>
        <label>KBAI Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KBAI_Type__c</fullName>
        <label>KBAI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP</label>
    <nameField>
        <label>Water MAP #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WaterMAPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP_Submission__c.object
<CustomObject>
    <description>xxxx</description>
    <fields>
        <fullName>Authorised_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorised By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WaterMAP Submissions (Authorised By)</relationshipLabel>
        <relationshipName>WaterMAP_Submissions_Authorised_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prepared_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prepared By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions_Preparer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by SEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Watermap__c</fullName>
        <label>Watermap</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009/10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008/09</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaterMAP Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WaterMAPHistoryController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class WaterMAPHistoryController
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class WaterMAPHistoryController_Test {

    /* TESTERS */
    private static testmethod void TestMe() {
        // create test data
        Account account = new Account();
        account.name = 'foo';
        insert account;

        Contact contact = new Contact();
        contact.LastName = 'Foo';
        contact.AccountId = account.id;
        contact.Title = '0123456789';
        contact.Phone = '0123456789';
        contact.Email = 'x@x.com';
        insert contact;

        Profile p = [select id from profile where name = 'SEW WaterMAP Portal User'];

        String testemail = 'puser000@amamama.com';
        User pu = new User(profileId = p.id, username = testemail, email = testemail,
                           emailencodingkey = 'UTF-8', localesidkey = 'en_US',
                           languagelocalekey = 'en_US', timezonesidkey = 'America/Los_Angeles',
                           alias='cspu', lastname='lastname', contactId = contact.id);

        insert pu;

        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        insert prop;

        Billing_Account__c billAcc = new Billing_Account__c();
        billAcc.Name = 'asetwetwrt';
        billAcc.Customer__c = account.id;
        billAcc.Property__c = prop.id;
        insert billAcc;

        Watermap__c waterMap = new Watermap__c();
        waterMap.Name = 'Test Me';
        waterMap.Customer__c = account.id;
        waterMap.Status__c = 'Not Started';
        waterMap.Billing_Account__c = billAcc.id;
        waterMAP.KBAI_Type__c = 'Average';
        waterMAP.KBAI_Description__c = 'Widget';
        insert waterMap;

        WaterMAP_Submission__c waterMapSub = new WaterMAP_Submission__c();
        waterMapSub.Customer__c = account.id;
        waterMapSub.Prepared_By__c = contact.id;
        waterMapSub.Prepared_By__r = contact;
        waterMapSub.Authorised_By__c = contact.id;
        waterMapSub.Authorised_By__r = contact;
        waterMapSub.Status__c = 'Review Completed';
        waterMapSub.Watermap__c = waterMap.id;
        waterMapSub.Watermap__r = waterMap;
        waterMapSub.Year__c = '2011/12';
        insert waterMapSub;

        Attachment attachment = new Attachment();
        attachment.ParentId = waterMapSub.id;
        attachment.Description = 'WaterMAP';
        attachment.Body = Blob.valueOf('xyz');
        attachment.Name = 'WaterMAP.pdf';
        insert attachment;

        Attachment attachment2 = new Attachment();
        attachment2.ParentId = waterMapSub.id;
        attachment2.Description = 'Review';
        attachment2.Name = 'Review.pdf';
        attachment2.Body = Blob.valueOf('xyz');
        insert attachment2;

        System.runAs(pu) {

            System.debug([Select ContactId, AccountId
                        From  User
                        Where Id = :UserInfo.getUserId() LIMIT 1]);

            WaterMAPHistoryController controller = new WaterMAPHistoryController();
            System.assertEquals(1, controller.wmapHistoryRecordsCount);
            System.debug(controller.wmapHistoryrecords);
            System.assertEquals(attachment.id, controller.wmapHistoryRecords[0].waterMAP.id);
        }
    }
}