sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Attention__c</fullName>
        <label>Attention</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Address_Same_As__c</fullName>
        <inlineHelpText>Please set flag None to change address in Billing Account.</inlineHelpText>
        <label>Billing Address Same As</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Care_Of__c</fullName>
        <label>Care Of</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>Billing Account Address</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Billing Account Address</description>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPID__c</fullName>
        <description>Billing Account Address DPID</description>
        <label>DPID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Sub_Account_Addresses__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used in the Batch Class that updates all Sub Billing Account Addresses when the Group Account Address is updated</description>
        <label>Update Sub Account Addresses</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/CopyGroupBillingAddressScheduler.cls
global class CopyGroupBillingAddressScheduler implements Schedulable{

/*
    Type:       Scheduler Class
    Purpose:    Schedules Billing Address Copy nightly job

    Used By:    
    ---------------------------------------------------------------
    History:
    	24-Feb-2014		ejandusay(Cloud Sherpas)	Moved test method in a separate test class


*/

    global void execute(SchedulableContext SC) {
        List<Billing_Account__c> groupBillingAccounts = [   SELECT    Id
                                                                    , Street_Address__c
                                                                    , City__c
                                                                    , State__c
                                                                    , Country__c
                                                                    , Postal_Code__c
                                                                    , Attention__c
                                                                    , Care_Of__c
                                                                    , Billing_Address_Same_As__c
                                                                    , Update_Sub_Account_Addresses__c
                                                                    , DPID__c
                                                            FROM    Billing_Account__c
                                                            WHERE   Update_Sub_Account_Addresses__c = TRUE];

        CopyGroupBillingAddress_BATCH copyGroupBillingAddress = new CopyGroupBillingAddress_BATCH(groupBillingAccounts);
        ID batchProcessId = Database.executeBatch( copyGroupBillingAddress);
    }

    
}