sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/PortalServicesMap__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Maps a service displayed in the portal to a list of tariffs</description>
    <fields>
        <fullName>Other_Authority_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checked if its another authority</inlineHelpText>
        <label>Other Authority?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tariff_Matcher__c</fullName>
        <inlineHelpText>Regular expression to match the tariff code</inlineHelpText>
        <label>Tariff Matcher</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Portal Service To Tariff</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tariff__c</fullName>
        <label>Tariff</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalAccountDetail_ExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalAccountDetail_ExCon
    ---------------------------------------------------------------
    History:

    25-Feb-2014 G Tsaousidis    Created
*/

@isTest
private class PortalAccountDetail_ExCon_Test {

 private static TestMethod void TestMe() {
        Account c = PortalTestHelper.createResiCustomer();
        Contact  p = PortalTestHelper.createContact(c);
        Billing_Account__c ba = PortalTestHelper.createAccounts(c, 1)[0];
        
        // create custom settings for data independence
        PortalServicesMap__c s1 = new PortalServicesMap__c(Name = 'Drainage Charge', Tariff_Matcher__c = '^[D]\\d{2,}', Other_Authority_Flag__c = true);
        insert s1;

        PortalServicesMap__c s2 = new PortalServicesMap__c(Name = 'Water Usage', Tariff_Matcher__c = '^[U]\\d{2,}');
        insert s2;

		// create the services
		Service__c svc1 = new Service__c (name = 'D1', tariff__c = 'D01', billing_account__c = ba.id);
		insert svc1;

		Service__c svc2 = new Service__c (name = 'U1', tariff__c = 'U01', billing_account__c = ba.id);
		insert svc2;

		Service__c svc3 = new Service__c (name = 'X1', tariff__c = 'XX01', billing_account__c = ba.id);
		insert svc3;
		
		PageReference pageref = Page.PortalAccountDetailPage;
        pageref.getParameters().put('id', ba.Id);
        Test.setCurrentPage(pageRef);
        PortalAccountDetail_ExCon con = new PortalAccountDetail_ExCon();
        
        pageref = con.SelectAccount();
        Test.setCurrentPage(pageRef);
        con = new PortalAccountDetail_ExCon();
        con.PopulateServices(); 
        system.assert(con.hasServices);
        system.assert(con.hasOtherServices);
        
        system.assert(con.services.size() == 1);
        
        PortalAccountDetail_ExCon con2 = new PortalAccountDetail_ExCon();
        
        
    }
}