sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Secondary_Contact__c</fullName>
        <label>Primary / Secondary Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Financial_Hardship__c.object
<CustomObject>
    <description>Financial Hardship Stream

Represents Financial Hardship information for customers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Signifies that the Financial Hardship Program is Active for the Customer</inlineHelpText>
        <label>Program Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SCRUM 2013 - Vulnerable Customer Stream</description>
        <inlineHelpText>Represents a Customer under a Financial Hardship program</inlineHelpText>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Hardship</relationshipLabel>
        <relationshipName>Financial_Hardship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hardship_Status__c</fullName>
        <inlineHelpText>Represents the level of financial hardship status for the related customer</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hardship_Story__c</fullName>
        <inlineHelpText>The initial story for the Financial Hardship Customer.</inlineHelpText>
        <label>Hardship Story</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Review_Action__c</fullName>
        <inlineHelpText>TO BE DEFINED</inlineHelpText>
        <label>Next Review Action</label>
        <picklist>
            <picklistValues>
                <fullName>Check URGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Centrepay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Plumbing Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Negotiated Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Water usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send URGS Application</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <defaultValue>TODAY() + 56</defaultValue>
        <inlineHelpText>The next review date. Defaulted to eight weeks from today, however SAO&apos;s can change this (except for setting it to a past date on creation).</inlineHelpText>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nominated_Financial_Hard_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The nominated Financial Hardship Billing Account</inlineHelpText>
        <label>Nominated Billing Account Number</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Financial Hardship</relationshipLabel>
        <relationshipName>Financial_Hardship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Financial Hardship</relationshipLabel>
        <relationshipName>Financial_Hardship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Hardship</label>
    <nameField>
        <displayFormat>FHA-{000000}</displayFormat>
        <label>Hardship Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Hardship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/FinancialHardshipBatchJob_Test.cls
/*
    Author: Eugene Jandusay
    Company: Cloud Sherpas 
    Description: (US-491 ) Test class for FinancialHardshipBatchJob .
    History
    01/07/2014 Eugene Jandusay Created

*/
@isTest
private class FinancialHardshipBatchJob_Test {
    
    //test to make sure changes were applied
    static testMethod void unitTestPositive() {
        //create Customer
        Account currentCustomer = PortalTestHelper.createNonResiCustomer();
        
        //create Contact
        Contact con = new Contact();
        con.LastName = 'Test';
        con.FirstName = 'Contact';
        con.Primary_Secondary_Contact__c = 'Primary Contact';
        con.AccountId = currentCustomer.Id;
        
        insert con;
        
        //create billing account
        Billing_Account__c billAccount = PortalTestHelper.createBillingAccount(currentCustomer,'100048');
        
        //create financial hardship
        
        Financial_Hardship__c financialHardship = new Financial_Hardship__c();
        
        financialHardship.Active__c = true;
        financialHardship.Hardship_Status__c = 'Silver';
        financialHardship.Next_Review_Date__c = date.today();
        financialHardship.Next_Review_Action__c = 'Silver Review';
        financialHardship.Customer__c = currentCustomer.Id;
        financialHardship.Primary_Contact__c = con.Id;
        financialHardship.Nominated_Financial_Hard_Billing_Account__c = billAccount.Id;
        financialHardship.Hardship_Story__c = 'test';
        
        insert financialHardship;
        
        test.startTest();
        
        FinancialHardshipBatchJob batchjob = new FinancialHardshipBatchJob();
        database.executeBatch(batchjob,200);
        
        test.stopTest();
        
        Financial_Hardship__c currentFH = [Select Hardship_Status__c FROM Financial_Hardship__c WHERE ID=:financialHardship.Id ];
        system.assertEquals(currentFH.Hardship_Status__c, 'Bronze');
        
    }
    
    //Negative test. Program is inactive. no changes should be made
    static testMethod void unitTestNegativeInactive() {
        //create Customer
        Account currentCustomer = PortalTestHelper.createNonResiCustomer();
        
        //create Contact
        Contact con = new Contact();
        con.LastName = 'Test';
        con.FirstName = 'Contact';
        con.Primary_Secondary_Contact__c = 'Primary Contact';
        con.AccountId = currentCustomer.Id;
        
        insert con;
        
        //create billing account
        Billing_Account__c billAccount = PortalTestHelper.createBillingAccount(currentCustomer,'100048');
        
        //create financial hardship
        
        Financial_Hardship__c financialHardship = new Financial_Hardship__c();
        
        financialHardship.Active__c = false;
        financialHardship.Hardship_Status__c = 'Silver';
        financialHardship.Next_Review_Date__c = date.today();
        financialHardship.Next_Review_Action__c = 'Silver Review';
        financialHardship.Customer__c = currentCustomer.Id;
        financialHardship.Primary_Contact__c = con.Id;
        financialHardship.Nominated_Financial_Hard_Billing_Account__c = billAccount.Id;
        financialHardship.Hardship_Story__c = 'test';
        
        insert financialHardship;
        
        test.startTest();
        
        FinancialHardshipBatchJob batchjob = new FinancialHardshipBatchJob();
        database.executeBatch(batchjob,200);
        
        test.stopTest();
        
        Financial_Hardship__c currentFH = [Select Hardship_Status__c FROM Financial_Hardship__c WHERE ID=:financialHardship.Id ];
        system.assertEquals(currentFH.Hardship_Status__c, 'Silver');
        
    }
    
    //Negative test. Program status is Gold. no changes should be made
    static testMethod void unitTestNegativeGold() {
        //create Customer
        Account currentCustomer = PortalTestHelper.createNonResiCustomer();
        
        //create Contact
        Contact con = new Contact();
        con.LastName = 'Test';
        con.FirstName = 'Contact';
        con.Primary_Secondary_Contact__c = 'Primary Contact';
        con.AccountId = currentCustomer.Id;
        
        insert con;
        
        //create billing account
        Billing_Account__c billAccount = PortalTestHelper.createBillingAccount(currentCustomer,'100048');
        
        //create financial hardship
        
        Financial_Hardship__c financialHardship = new Financial_Hardship__c();
        
        financialHardship.Active__c = false;
        financialHardship.Hardship_Status__c = 'Gold';
        financialHardship.Next_Review_Date__c = date.today();
        financialHardship.Next_Review_Action__c = 'Check Gold';
        financialHardship.Customer__c = currentCustomer.Id;
        financialHardship.Primary_Contact__c = con.Id;
        financialHardship.Nominated_Financial_Hard_Billing_Account__c = billAccount.Id;
        financialHardship.Hardship_Story__c = 'test';
        
        insert financialHardship;
        
        test.startTest();
        
        FinancialHardshipBatchJob batchjob = new FinancialHardshipBatchJob();
        database.executeBatch(batchjob,200);
        
        test.stopTest();
        
        Financial_Hardship__c currentFH = [Select Hardship_Status__c FROM Financial_Hardship__c WHERE ID=:financialHardship.Id ];
        system.assertEquals(currentFH.Hardship_Status__c, 'Gold');
        
    }
}