sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>Watermap</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>The customer who is actually responsible for paying usage charges to SEW</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>WaterMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <formula>Billing_Account__r.Property_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP</label>
    <nameField>
        <label>Water MAP #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WaterMAPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP_Submission__c.object
<CustomObject>
    <description>xxxx</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <formula>Watermap__r.Site_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by SEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Watermap__c</fullName>
        <label>Watermap</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009/10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008/09</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaterMAP Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WaterMAPHistoryController.cls
public without sharing class WaterMAPHistoryController {
/*
    Type:       Controller
    Purpose:    Controller to display the list of historical Watermaps

    Used By:    WaterMAPHistoryPage VF Page
    ---------------------------------------------------------------
    History:

    13-Jun-2011 D.Thong (Salesforce)    Created
    25-Feb-2014 ejandusay(Cloud Sherpas) Moved test method in a separate test class

*/

    /* PUBLIC PROPERTIES */
    // list of history records
    public List<WMAPHistory> wmapHistoryRecords {
        get {
            // Our return list
            List<WMAPHistory> wmapHistoryRecords = new List<WMAPHistory>();

            // assume that the user is always there!
            User user = [Select ContactId, AccountId
                        From  User
                        Where Id = :UserInfo.getUserId() LIMIT 1];

            // retrieve the historical watermap records
            List <WaterMAP_Submission__c> wmapSubs =
                            [Select Year__c, WaterMAP__r.Billing_Account__r.HiAF_Account_Number_Check_Digit__c,
                                    Site_Address__c,
                                    (Select Id, Name From Attachments
                                            Where Name In ('WaterMAP.pdf', 'Review.pdf'))
                                From WaterMAP_Submission__c
                                Where Customer__c = :user.AccountId
                                And   Status__c = 'Review Completed'
                                Order by Year__c, WaterMAP__r.Billing_Account__r.HiAF_Account_Number_Check_Digit__c];

            for (WaterMAP_Submission__c wmsub : wmapSubs) {
                Attachment wMapAtt;
                Attachment ReviewAtt;

                for (Attachment a : wmsub.Attachments) {
                    if (a.Name == 'WaterMAP.pdf')
                        wMapAtt = a;
                    else
                        ReviewAtt = a;
                }
                wmapHistoryRecords.add(new WMAPHistory(wmsub.Year__c,
                                                        wmsub.WaterMAP__r.Billing_Account__r.HiAF_Account_Number_Check_Digit__c,
                                                        wmsub.Site_Address__c,
                                                        wMapAtt, ReviewAtt));
            }

            return wmapHistoryRecords;
        }
    }

    // count of history records
    public integer wmapHistoryRecordsCount {
        get { return wmapHistoryRecords.size(); }
    }

    /* CONSTRUCTOR */
    public WaterMAPHistoryController() {}

    /* PUBLIC CLASSES */
    // wraps historical watermaps
    public class WMAPHistory {
        public String year {get; set;}
        public String siteAddress {get; set;}
        public String customerNbr {get; set;}
        public Attachment waterMAP {get; set;}
        public Attachment review {get; set;}

        public WMAPHistory(String year, String customerNbr, String siteAddress,
                                Attachment waterMAP, Attachment review) {
            this.year = year;
            this.waterMAP = waterMAP;
            this.review = review;
            this.siteAddress = siteAddress;
            this.customerNbr = customerNbr;
        }
    }

    

}