sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <formula>Property__r.CIS_Property_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CIS Property Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account_SMR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field has the property filter on and will be displayed only on SMR page.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (Billing Account)</relationshipLabel>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meter1_Reading__c</fullName>
        <description>Meter Reading</description>
        <inlineHelpText>Meter Reading</inlineHelpText>
        <label>Meter 1 Reading</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meter1_Serial__c</fullName>
        <label>Meter 1 Serial</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Query</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reading_Date__c</fullName>
        <label>Reading Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>New field added to have a higher level categorisation of the case by business function. Currently only used by Portal, but can be reused at a later date.</description>
        <label>Sub Type</label>
        <picklist>
            <picklistValues>
                <fullName>Article Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession - Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feedback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Statement Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merge Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Time To Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More Time To Pay Exception</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice of Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration Enquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration Name Match</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Meter Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession - Delete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Reading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Take_Customer_Meter_Read</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Case to record Customer Meter Read.</description>
        <label>Take Customer Meter Read</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Meter_Type__c</fullName>
        <label>Meter Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pit_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Pit Reference</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>CIS_Property_Id__c</fullName>
        <description>Property reference number in HiAF</description>
        <externalId>true</externalId>
        <label>CIS Property Id</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>HIDDEN_Confirmed_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(Hidden) Confirmed Portal User</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalSubmitMeterRead_Controller.cls
public with sharing class PortalSubmitMeterRead_Controller extends PortalPageWithCase_Virtual_Con {

/*
    Type:       Controller class
    Purpose:    Submit Meter Reading
                

    Used By:    
    ---------------------------------------------------------------
    History:

    18-Feb-2011 D.Thong (Salesforce)    Created
    07-May-2012 Ji Zhang (Coretec Solutions) Updated: add selectedBillingAccount.Name
                                             RetrieveMeterReadings(meters[0].Meter_Type__c, meters[0].Pit_Reference__c, selectedBillingAccount.Name)
    12-Jun-2012 DYu                          Updated: 5231
    31-Oct-2012 - I.Castillo                 Updated: 5233 – Show the last read date on the Submit Meter Read page
	12-Nov-2012 - Dthong					 Added subtype
	25-Feb-2014 N.Patterson   				Moving test methods to a test class to reduce code usage
*/

    /* PUBLIC PROPERTIES */
    // Meter list
    public List<SelectOption> meterOptions {
        get {
            meterOptions = new List<SelectOption>();
            if (caseRec != null && caseRec.Billing_Account__c != null && 
                    selectedBillingAccount != null && selectedBillingAccount.property__c != null) {
                for(Meter_Details__c meter : [Select Name, Id From Meter_Details__c  
                                                where property__c = :selectedBillingAccount.property__c
                                                order by Name ]) {
                    meterOptions.add(new SelectOption(meter.Name, meter.Name));
                }
            } 
            if (meterOptions.isEmpty()){
                meterOptions.add(new SelectOption('', '-- No meters on property --'));
            }       
            
            return meterOptions;
        }
        private set;
    }
    
    public Long priorMeterRead {
        get {
            return GetPriorMeterRead();
        }
    }
    
     public Date priorMeterReadDate {
        get {
            return GetPriorMeterReadDate();
        }
    }

    /* CONSTANTS */
    private final static Id TAKEMETERREAD_RECORDTYPEID;

    /* CONSTRUCTOR */
    public PortalSubmitMeterRead_Controller() {
        super();
        // then default more case details
        caseRec.Reading_Date__c = System.today();
        caseRec.RecordTypeId = TAKEMETERREAD_RECORDTYPEID;
        caseRec.Description = 'This meter read was submitted by the customer portal';
		
		// DT 12-Nov-2012 - set the case subtype --
		caseRec.Sub_Type__c = 'Submit Meter Read';
		// --
		
		PopulateBillingAccount();
        // default the account
        if (activeBillingAccounts != null && !activeBillingAccounts.isEmpty()) {
            caseRec.Billing_Account__c = activeBillingAccounts[0].id;
            PopulateBillingAccount();   
        }
    }

    /* PUBLIC METHODS */
    public User curUser {get;set;}

    // Check that the user is not a confirmed portal user
    /*public PageReference CheckRedirectConfirmed() {
        curUser = [Select Id, HIDDEN_Confirmed_Portal_User__c from User where Id =: UserInfo.getUserId()];
        if (curUser.HIDDEN_Confirmed_Portal_User__c != true) { 
            return Page.PortalUserConfirmation.setRedirect(true);       
        }
        return null;
    }*/
    
    // submit
    public override PageReference Submit() {

         if(caseRec.Meter1_Serial__c == null){
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, 'Meter: Please select a property with a meter.'));
            return null;
        }
        
        if (caseRec.Reading_Date__c == null ||
                caseRec.Reading_Date__c > system.today()) {
            caseRec.Reading_Date__c.addError('Reading date cannot be greater than today');
            return null;        
        }
        
        if (caseRec.Meter1_Reading__c < 0) {
            caseRec.Meter1_Reading__c.addError('Reading cannot be a negative number');
            return null;
        }
        
        
        caseRec.Billing_Account_SMR__c = caseRec.Billing_Account__c;
        if (selectedBillingAccount != null && selectedBillingAccount.property__c != null) {
            caseRec.Subject = 'Meter reading for property ' + selectedBillingAccount.property__r.cis_property_Id__c;
            caseRec.Property__c = selectedBillingAccount.property__c;
            caseRec.Mode__c = 'Query';
        }   
        
        if (super.submit() != null) {
            submitted=true;
        }
        return null;
    }

    // navigate back
    public PageReference SubmitAnother() {
        return Page.PortalSubmitMeterRead.setRedirect(true);
    }
    
    // override populate billing account
    public override void PopulateBillingAccount() {
        super.PopulateBillingAccount();
        
        // default the meter serial
        if (selectedBillingAccount != null && selectedBillingAccount.property__c != null) {
            List<Meter_Details__c> meters = [Select Name, Id From Meter_Details__c  
                                                where property__c = :selectedBillingAccount.property__c
                                                order by name];

            if (!meters.isEmpty())
                caseRec.Meter1_Serial__c = meters[0].name;
            else
                caseRec.Meter1_Serial__c = null;
        } else
            caseRec.Meter1_Serial__c = null;
    }   
    
    // GetPriorMeterRead
    public Long GetPriorMeterRead() {
        Long read = 0;

        if (caseRec.Meter1_Serial__c != null && selectedBillingAccount != null &&
                    selectedBillingAccount.Property__c != null) {

            List<Meter_Details__c> meters = [select meter_type__c, Pit_Reference__c from Meter_Details__c
                                            where name = :caseRec.Meter1_Serial__c 
                                            order by name];
        
            System.debug('FOO');
            System.debug(meters);
            
            if (meters != null && !meters.isEmpty()) {
                ApexPages.StandardController sc = new ApexPages.StandardController(meters[0]);
                MeterReadingsHistoryExCon meterCon = new MeterReadingsHistoryExCon(sc);
                List<WSUtil_Property.MeterReading> meterReads = meterCon.RetrieveMeterReadings(meters[0].Meter_Type__c, meters[0].Pit_Reference__c, selectedBillingAccount.Name);            
    
                if (meterReads != null && !meterReads.isEmpty()) {
                    //read = Long.valueOf(meterReads[0].reading);
                    WSUtil ws = new WSUtil();   
                    String tempRead = String.valueOf(ws.formatTIBCODecimal(meterReads[0].reading));  
                     System.debug('XXXX -- ' + String.valueOf(meterReads[0].readdate)); 
                    read = Long.valueOf(tempRead);      
                }
            }
        }
        
        return read;
    }

    // GetPriorMeterReadDate
    public Date GetPriorMeterReadDate() {
        Date readdate = Date.today();

        if (caseRec.Meter1_Serial__c != null && selectedBillingAccount != null &&
                    selectedBillingAccount.Property__c != null) {

            List<Meter_Details__c> meters = [select meter_type__c, Pit_Reference__c from Meter_Details__c
                                            where name = :caseRec.Meter1_Serial__c 
                                            order by name];
        
            System.debug('FOO');
            System.debug(meters);
            
            if (meters != null && !meters.isEmpty()) {
                ApexPages.StandardController sc = new ApexPages.StandardController(meters[0]);
                MeterReadingsHistoryExCon meterCon = new MeterReadingsHistoryExCon(sc);
                List<WSUtil_Property.MeterReading> meterReads = meterCon.RetrieveMeterReadings(meters[0].Meter_Type__c, meters[0].Pit_Reference__c, selectedBillingAccount.Name);            
    
                if (meterReads != null && !meterReads.isEmpty()) {
                    //read = Long.valueOf(meterReads[0].reading);
                    WSUtil ws = new WSUtil();   
                    Date tempReadDate = Date.valueOf(meterReads[0].readdate);  
                     System.debug('XXXX -- ' + String.valueOf(meterReads[0].readdate)); 
                    readdate = date.valueof(tempReadDate);      
                }
            }
        }
        
        return readdate;
    }

    /* INITIALIZERS */
    static {
        TAKEMETERREAD_RECORDTYPEID = [select id from RecordType 
                                        where developername = 'Take_Customer_Meter_Read'
                                        and sObjectType = 'Case'].id;
    }


    
}