sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reminder_Method__c</fullName>
        <label>Reminder Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>eBill_Method__c</fullName>
        <label>eBill Method</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BPAY View</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>eBill_Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>eBill Recipient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>eBill Delivery Preferences</relationshipLabel>
        <relationshipName>eBill_Recipients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalBillPreferencesController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class AccountMassBAcctAddressFlagUpdateExCon
    ---------------------------------------------------------------
    History:

    25-Feb-2014 G Tsaousidis			Created
*/

@isTest
private class PortalBillPreferencesController_Test {

/* TEST METHODS */
    /* eBIll recipient is equal to users contact */
    public static testmethod void PortalBillPreferencesController_Test(){
        Account acc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        con.Email = 'dyu@cloudsherpas.com';
        update con;
        User user = PortalTestHelper.createUser(con);
        List<Property__c> properties = PortalTestHelper.createProperties(15, 'BillAcctIn');
        List<Billing_Account__c> billingAccounts = PortalTestHelper.createBillingAccountsWithProperties(acc, properties);
        List<Billing_Account__c> updateBillingAccounts = new List<Billing_Account__c>();
        
        
        for (Billing_Account__c billAcct : billingAccounts) {
            billAcct.eBill_Recipient__c = con.Id;
            billAcct.eBill_Method__c = 'Email';
            billAcct.Reminder_Method__c = 'Email';
            updateBillingAccounts.add(billAcct);
        }
        update updateBillingAccounts;
        
        Test.startTest();
        System.runAs(user) {
            PageReference pageRef = Page.PortalBillPreferences;
            Test.setCurrentPage(pageRef);
            PortalBillPreferencesController billCon = new PortalBillPreferencesController();
            Billing_Account__c ba = [select eBill_Recipient__c from Billing_Account__c where id =: updateBillingAccounts.get(0).id];
            billCon.saveAccountDetails();
            billCon.save();
            billCon.returnToAccountDetailsPage();
            
            System.assertEquals(ba.eBill_Recipient__c, user.ContactId);
        }
        Test.stopTest();
    }
    
    /* eBIll recipient is null */
    public static testmethod void PortalBilleBillRecipientNull_Test(){
        Account acc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        con.Email = 'dyu@cloudsherpas.com';
        update con;
        User user = PortalTestHelper.createUser(con);
        List<Property__c> properties = PortalTestHelper.createProperties(15, 'BillAcctIn');
        List<Billing_Account__c> billingAccounts = PortalTestHelper.createBillingAccountsWithProperties(acc, properties);
        List<Billing_Account__c> updateBillingAccounts = new List<Billing_Account__c>();
        
        Test.startTest();
        System.runAs(user) {
            PageReference pageRef = Page.PortalBillPreferences;
            Test.setCurrentPage(pageRef);
            PortalBillPreferencesController billCon = new PortalBillPreferencesController();
        }
        Test.stopTest();
    }
    
    /* eBIll recipient is different from user contact */
    public static testmethod void PortalBilleBillRecipientNotUserContact_Test(){
        Account acc = PortalTestHelper.createResiCustomer();
        Account userAcc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        Contact userCon = PortalTestHelper.createContact(userAcc);
        userCon.Email = 'dyu@cloudsherpas.com';
        update userCon;
        User user = PortalTestHelper.createUser(con);
        User billAcctUser = PortalTestHelper.createBillingAccountUser(userCon);
        List<Property__c> properties = PortalTestHelper.createProperties(15, 'BillAcctIn');
        List<Billing_Account__c> billingAccounts = PortalTestHelper.createBillingAccountsWithProperties(userAcc, properties);
        List<Billing_Account__c> updateBillingAccounts = new List<Billing_Account__c>();
        
        
        for (Billing_Account__c billAcct : billingAccounts) {
            billAcct.eBill_Recipient__c = userCon.Id;
            billAcct.eBill_Method__c = 'Email';
            billAcct.Reminder_Method__c = 'Email';
            updateBillingAccounts.add(billAcct);
        }
        update updateBillingAccounts;
        
        Test.startTest();
        System.runAs(user) {
            PageReference pageRef = Page.PortalBillPreferences;
            Test.setCurrentPage(pageRef);
            PortalBillPreferencesController billCon = new PortalBillPreferencesController();
        }
        Test.stopTest();
    }
     
    /* eBill method is BPAY view */
    public static testmethod void PortalBillPreferencesBPAYView_Test(){
        Account acc = PortalTestHelper.createResiCustomer();
        Contact con = PortalTestHelper.createContact(acc);
        con.Email = 'dyu@cloudsherpas.com';
        update con;
        User user = PortalTestHelper.createUser(con);
        List<Property__c> properties = PortalTestHelper.createProperties(15, 'BillAcctIn');
        List<Billing_Account__c> billingAccounts = PortalTestHelper.createBillingAccountsWithProperties(acc, properties);
        List<Billing_Account__c> updateBillingAccounts = new List<Billing_Account__c>();
        
        for (Billing_Account__c billAcct : billingAccounts) {
            billAcct.eBill_Recipient__c = con.Id;
            billAcct.eBill_Method__c = 'BPAY View';
            billAcct.Reminder_Method__c = 'Email';
            updateBillingAccounts.add(billAcct);
        }
        update updateBillingAccounts;
        
        Test.startTest();
        System.runAs(user) {
            PageReference pageRef = Page.PortalBillPreferences;
            Test.setCurrentPage(pageRef);
            PortalBillPreferencesController billCon = new PortalBillPreferencesController();
            Billing_Account__c ba = [select eBill_Method__c from Billing_Account__c where id =: updateBillingAccounts.get(0).id];
            
            System.assertEquals(ba.eBill_Method__c, 'BPAY View');
        }
        Test.stopTest();
    }
}