sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Credit_Card_Proxy__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Credit Card Proxies</relationshipLabel>
        <relationshipName>Credit_Card_Proxies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CVN__c</fullName>
        <label>CVN</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_1__c</fullName>
        <label>Credit Card Number 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_2__c</fullName>
        <label>Credit Card Number 2</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_3__c</fullName>
        <label>Credit Card Number 3</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_4__c</fullName>
        <label>Credit Card Number 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Card Proxies</relationshipLabel>
        <relationshipName>Credit_Card_Proxies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiration_Date_Month__c</fullName>
        <label>Expiry Date</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date_Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_on_Card__c</fullName>
        <label>Name on Card</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <label>Credit Card Proxy</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Credit Card Proxy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Card Proxies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/CreditCardPaymentController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class CreditCardPaymentController
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class CreditCardPaymentController_Test {

    //Test Method
    public static testmethod void testCreditCardPaymentController(){
        Account testAcc = new Account(name = 'Test Account');
        Database.insert(testAcc);
        
        Billing_Account__c ba = new Billing_Account__c(name = 'Test Billing Account', Customer__c = testAcc.id);
        Database.insert(ba);
        
        Credit_Card_Proxy__c testInput = new Credit_Card_Proxy__c();
        testInput.Credit_Card_Type__c = 'Visa';
        testInput.Credit_Card_Number_1__c = 'bad number';
        testInput.Credit_Card_Number_2__c = 'bad number';
        testInput.Credit_Card_Number_3__c = 'bad number';
        testInput.Credit_Card_Number_4__c = 'bad number';
        testInput.Expiration_Date_Year__c = '2012';
        testInput.Expiration_Date_Month__c = '06';
        testInput.Amount__c = 5000;
        testInput.Name_on_Card__c = 'Tester';
        testInput.Amount__c = 10000;
        testInput.CVN__c = 'bad CVN';
        
        PageReference pageRef = Page.CreditCardPayment;
        Test.setCurrentPage(pageRef);
        System.currentPageReference().getParameters().put('customerId',testAcc.Id);
        System.currentPageReference().getParameters().put('billAcctId',ba.Id);
        System.currentPageReference().getParameters().put('Id',ba.Id);
        testInput.Customer_Account__c = testAcc.Id;
        CreditCardPaymentController controller = new CreditCardPaymentController();
        controller.userInputFields = testInput;
        controller.isValidData();
        testInput.Credit_Card_Number_1__c = '1234';
        testInput.Credit_Card_Number_2__c = '5678';
        testInput.Credit_Card_Number_3__c = '9012';
        testInput.Credit_Card_Number_4__c = '3456';
        testInput.CVN__c = '888';
        testInput.Customer_Account__c = testAcc.id;
        testInput.Billing_Account__c = ba.id;   
        controller.userInputFields = testInput;
        controller.getAmount();
        testInput.Amount__c = 100;
        controller.userInputFields = testInput; 
        controller.redirect = null;
        controller.getItems();
       
        controller.submit();
        controller.paymentSucceeded = true; 
        controller.paymentMsg = 'Credit Card Payment Successful';
        controller.checkStatus();
        controller.redirect = true;
        controller.Redirect();
        System.assertEquals(controller.redirect, false);
        
        controller.paymentSucceeded = false;
        controller.redirect = false;
        
        Task t = new Task();
        t.Subject = 'Credit Card Payment';
        t.ActivityDate = date.today();
        t.Type = 'Credit Card Payment';
        t.WhatId = ba.Id;
        t.Status = 'Completed';
        Database.insert(t);
        controller.taskRec = t;
        controller.taskId = t.id;
        controller.checkStatus();
        t.Status = 'Failed';
        //Database.update(t);
        controller.taskId = t.id;
        controller.submitPayment();
        controller.checkStatus();
        controller.timeOut = true;
        controller.timeOut();
        controller.userInputFields = testInput;
        // test for time out
        for(Integer i = 0; i < 12; i++){ controller.checkStatus(); }
        controller.Redirect();
        controller.payBill();
    }
}