sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad-Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchaser_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Also applies to Tenant becomes Purchaser situation.</inlineHelpText>
        <label>Purchaser Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (As Purchaser Account)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Settlement_Date__c</fullName>
        <label>Settlement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tenant_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Not required is Non-Tenancy is picked.</inlineHelpText>
        <label>Tenant Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (AsTenant Account)</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Sale__c</fullName>
        <inlineHelpText>Non Tenant is the new purchase of a property where there is no tenancy</inlineHelpText>
        <label>Type of Sale</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Tenancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant is Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchaser, Tenant Stays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchaser, Tenant Leaves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale of Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (As Vendor Account)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/NoticeOfSaleActions_Extension_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class NoticeOfSaleActions_Extension
    ---------------------------------------------------------------
    History:

    24-Feb-2014 G Tsaousidis    Created
*/

@isTest
private class NoticeOfSaleActions_Extension_Test {

 private static testMethod void testNoticeOfSaleExtension(){
        //Setup Test Data
        Account testCustomerPurchaser = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerPurchaser;

        Billing_Account__c testPurchaserBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testPurchaserBillingAccount.Customer__c = testCustomerPurchaser.Id;
        testPurchaserBillingAccount.Role__c = 'Owner Occupier';
        insert testPurchaserBillingAccount;


        Account testCustomerVendor = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerVendor;

        Property__c testProperty = SObjectCreator.createProperty();
        insert testProperty;

        Billing_Account__c testVendorBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testVendorBillingAccount.Customer__c = testCustomerVendor.Id;
        testVendorBillingAccount.Role__c = 'Landlord';
        testVendorBillingAccount.Property__c = testProperty.Id;
        insert testVendorBillingAccount;

        Account testCustomerTenant = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerTenant;

        Billing_Account__c testTenantBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testTenantBillingAccount.Customer__c = testCustomerTenant.Id;
        testTenantBillingAccount.Role__c = 'Tenant';
        testTenantBillingAccount.Property__c = testProperty.Id;
        insert testTenantBillingAccount;

        Case testNOSCase = SObjectCreator.createCaseNoticeOfSale();
        testNOSCase.Property__c = testProperty.Id;
        testNOSCase.Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase.Purchaser_Billing_Account__c = testPurchaserBillingAccount.Id;
        testNOSCase.Vendor_Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase.Tenant_Billing_Account__c = testTenantBillingAccount.Id;
        testNOSCase.Type_of_Sale__c = 'New Purchaser, Tenant Leaves';
        testNOSCase.Settlement_Date__c = system.today()+1;

        testNOSCase.Status = 'New';
        insert testNOSCase;

        testNOSCase = NoticeOfSaleActions_Extension.getCaseDetails(testNOSCase.Id); 

        PageReference pageRef = Page.NoticeOfSaleActions;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(testNOSCase);
        NoticeOfSaleActions_Extension extn = new NoticeOfSaleActions_Extension(stdCon);

        Test.startTest();

        extn.performNoticeOfSale();

        Case validateCase = NoticeOfSaleActions_Extension.getCaseDetails(testNOSCase.Id);
        //system.assert(validateCase.IsClosed);
        //system.assert(validateCase.Complete__c);

        Case testNOSCase2 = SObjectCreator.createCaseNoticeOfSale();
        testNOSCase2.Property__c = testProperty.Id;
        testNOSCase2.Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase2.Purchaser_Billing_Account__c = testPurchaserBillingAccount.Id;
        testNOSCase2.Vendor_Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase2.Tenant_Billing_Account__c = testTenantBillingAccount.Id;
        testNOSCase2.Settlement_Date__c = system.today()-1;
        testNOSCase2.Type_of_Sale__c = 'Sale of Business';
        testNOSCase2.Status = 'New';
        insert testNOSCase2;

        testNOSCase2 = NoticeOfSaleActions_Extension.getCaseDetails(testNOSCase2.Id);

        PageReference pageRef2 = Page.NoticeOfSaleActions;
        Test.setCurrentPage(pageRef2);

        ApexPages.StandardController stdCon2 = new ApexPages.StandardController(testNOSCase2);
        NoticeOfSaleActions_Extension extn2 = new NoticeOfSaleActions_Extension(stdCon2);
        extn2.performNoticeOfSale();

        Case validateCase2 = NoticeOfSaleActions_Extension.getCaseDetails(testNOSCase2.Id);

        //system.assert(validateCase2.IsClosed); // Sale of Business Cases closed by workflow rule
        //system.assert(!validateCase2.Complete__c);
        system.assert(ApexPages.hasMessages());

        extn2.back();
        Test.stopTest();

    }

    private static testMethod void testNoticeOfSaleExtension2(){
        //Setup Test Data
        Account testCustomerPurchaser = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerPurchaser;

        Billing_Account__c testPurchaserBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testPurchaserBillingAccount.Customer__c = testCustomerPurchaser.Id;
        testPurchaserBillingAccount.Role__c = 'Owner Occupier';
        insert testPurchaserBillingAccount;


        Account testCustomerVendor = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerVendor;

        Property__c testProperty = SObjectCreator.createProperty();
        insert testProperty;

        Billing_Account__c testVendorBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testVendorBillingAccount.Customer__c = testCustomerVendor.Id;
        testVendorBillingAccount.Role__c = 'Landlord';
        testVendorBillingAccount.Property__c = testProperty.Id;
        insert testVendorBillingAccount;

        Account testCustomerTenant = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerTenant;

        Billing_Account__c testTenantBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testTenantBillingAccount.Customer__c = testCustomerTenant.Id;
        testTenantBillingAccount.Role__c = 'Tenant';
        testTenantBillingAccount.Property__c = testProperty.Id;
        insert testTenantBillingAccount;

        Case testNOSCase = SObjectCreator.createCaseNoticeOfSale();
        testNOSCase.Property__c = testProperty.Id;
        testNOSCase.Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase.Purchaser_Billing_Account__c = testPurchaserBillingAccount.Id;
        testNOSCase.Vendor_Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase.Tenant_Billing_Account__c = testTenantBillingAccount.Id;
        testNOSCase.Type_of_Sale__c = 'New Purchaser, Tenant Leaves';
        testNOSCase.Settlement_Date__c = system.today()+1;

        testNOSCase.Status = 'Waiting for HiAffinity';
        insert testNOSCase;

        testNOSCase = NoticeOfSaleActions_Extension.getCaseDetails(testNOSCase.Id);

        PageReference pageRef = Page.NoticeOfSaleActions;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(testNOSCase);
        NoticeOfSaleActions_Extension extn = new NoticeOfSaleActions_Extension(stdCon);

        Test.startTest();

        extn.performNoticeOfSale();
        Test.stopTest();
        
        TibcoNoticeOfSale_MessageTypes.ErrorStatus_element err = new TibcoNoticeOfSale_MessageTypes.ErrorStatus_element();
    }
}