sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalMeterReadingsHistoryExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalMeterReadingsHistoryExCon
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/
@isTest
public with sharing class PortalMeterReadingsHistoryExCon_Test {
	public static testmethod void test_PortalMeterReadingsHistoryExCon(){
        Account testAcct = new Account(name='test account');
        insert testAcct;
        
        Property__c testProperty = new Property__c(name='test property');
        insert testProperty;
        
        Billing_Account__c testBa = new Billing_Account__c
                                (name='test',
                                 customer__c=testAcct.Id, 
                                 HiAF_Account_Number__c='1234',
                                 property__c = testProperty.Id);
        insert testBa;
        
        Meter_Details__c testMeter = new Meter_Details__c(name='test meter', property__c = testProperty.Id);
        insert testMeter;
        
        PortalMeterReadingsHistoryExCon excon = new PortalMeterReadingsHistoryExCon(new ApexPages.StandardController(testBa));
        excon.currentMeter = null;
        System.assert(excon.currentMeter!=null);
        excon.currentMeterId = testMeter.Id;
        //excon.meterList = null;

        System.assert(excon.meterList!=null);
        System.assert(excon.meterListNum == 1);
        excon.meterReadings = null;
        System.assert(excon.meterReadings!=null);
        excon.getMeterListOption();
        
        Meter_Details__c testMeter2 = new Meter_Details__c(name='test meter2', property__c = testProperty.Id);
        insert testMeter2;
        
        excon = new PortalMeterReadingsHistoryExCon(new ApexPages.StandardController(testBa));

        System.assert(excon.meterListNum == 2);
        excon.getMeterListOption();
        excon.currentMeterId = null;
        System.assert(excon.meterReadings==null);
    }
}