sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>City__c</fullName>
        <description>Billing Account Address</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Billing Account Address</description>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Address_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Address Available</description>
        <label>Address Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Account_Quoted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing Account Quoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City</description>
        <label>City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country</description>
        <label>Country</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <description>Postcode</description>
        <label>Postcode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recycled_Water_Available__c</fullName>
        <formula>IF(Property__r.Recycled_Water_Available__c, &quot;Available&quot;, &quot;Unavailable&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>If recycled water is available on the property, then specifying an address will issue a welcome home kit.</inlineHelpText>
        <label>Recycled Water Available</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State</description>
        <label>State/Postcode</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street</description>
        <label>Street</label>
        <length>30</length>
        <type>Text</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Recycled_Water_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recycled Water Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/InfoStatementUpdate_Extension_Test.cls
/**
    Type:       Test Class
    Purpose:    Test Class for InfoStatementUpdate 

    Used By:    InfoStatementUpdate_Extension
    ---------------------------------------------------------------
    History:
		   		24-Feb-2014 - G Tsaousidis - Created
		    
 */
@isTest
private class InfoStatementUpdate_Extension_Test {
    
    public static final String CLOSED_CASE_STATUS = 'Closed';
    public static final String CANCELLED_CASE_STATUS = 'Cancelled';
    
	public static testMethod void test_InfoStatementUpdate_Extension_BillAccountNotQuoted(){
        Account testAccount = SObjectCreator.createAccountResidentialCustomer();
        insert testAccount;
        
        Contact testContact = SObjectCreator.createContact();
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        Property__c testProperty = SObjectCreator.createProperty();
        insert testProperty;
        
        Billing_Account__c testBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testBillingAccount.Customer__c = testAccount.Id;
        testBillingAccount.Property__c = testProperty.Id;
        insert testBillingAccount;
        
        Case testInfoStatementUpdateCase = SObjectCreator.createCaseInfoStatementUpdate();
        testInfoStatementUpdateCase.AccountId = testAccount.Id;
        testInfoStatementUpdateCase.Billing_Account__c = testBillingAccount.Id;
        insert testInfoStatementUpdateCase;
        
        ApexPages.Standardcontroller stdCon = new ApexPages.Standardcontroller(testInfoStatementUpdateCase);
        InfoStatementUpdate_Extension extnCon = new InfoStatementUpdate_Extension(stdCon);
        
        Test.startTest();
        extnCon.performInfoStatementUpdate();
        extnCon.back();
        Test.stopTest();
        
        /*testInfoStatementUpdateCase.Billing_Account_Quoted__c = true;
        update testInfoStatementUpdateCase;
        
        ApexPages.Standardcontroller stdCon = new ApexPages.Standardcontroller(testInfoStatementUpdateCase);
        InfoStatementUpdate_Extension extnCon = new InfoStatementUpdate_Extension(stdCon);
        
        Test.startTest();
        extnCon.performInfoStatementUpdate();
        Test.stopTest();
        
        testInfoStatementUpdateCase.Status = CLOSED_CASE_STATUS;
        update testInfoStatementUpdateCase;
        
        ApexPages.Standardcontroller stdCon = new ApexPages.Standardcontroller(testInfoStatementUpdateCase);
        InfoStatementUpdate_Extension extnCon = new InfoStatementUpdate_Extension(stdCon);
        
        Test.startTest();
        extnCon.performInfoStatementUpdate();
        Test.stopTest();*/
    }
    
    public static testMethod void test_InfoStatementUpdate_Extension_CaseAlreadyClosed(){
        Account testAccount = SObjectCreator.createAccountResidentialCustomer();
        insert testAccount;
        
        Contact testContact = SObjectCreator.createContact();
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        Property__c testProperty = SObjectCreator.createProperty();
        insert testProperty;
        
        Billing_Account__c testBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testBillingAccount.Customer__c = testAccount.Id;
        testBillingAccount.Property__c = testProperty.Id;
        insert testBillingAccount;
        
        Case testInfoStatementUpdateCase = SObjectCreator.createCaseInfoStatementUpdate();
        testInfoStatementUpdateCase.AccountId = testAccount.Id;
        testInfoStatementUpdateCase.Billing_Account__c = testBillingAccount.Id;
        testInfoStatementUpdateCase.Status = CLOSED_CASE_STATUS; 
        insert testInfoStatementUpdateCase;
        
        ApexPages.Standardcontroller stdCon = new ApexPages.Standardcontroller(testInfoStatementUpdateCase);
        InfoStatementUpdate_Extension extnCon = new InfoStatementUpdate_Extension(stdCon);
        
        Test.startTest();
        extnCon.performInfoStatementUpdate();
        Test.stopTest();
    }
    
    public static testMethod void test_InfoStatementUpdate_Extension_BillingAccountQuoted(){
        Account testAccount = SObjectCreator.createAccountResidentialCustomer();
        insert testAccount;
        
        Contact testContact = SObjectCreator.createContact();
        testContact.AccountId = testAccount.Id;
        insert testContact;
        
        Property__c testProperty = SObjectCreator.createProperty();
        testProperty.Recycled_Water_Available__c = true;
        insert testProperty;
        
        Billing_Account__c testBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testBillingAccount.Customer__c = testAccount.Id;
        testBillingAccount.Property__c = testProperty.Id;
        insert testBillingAccount;
        
        Case testInfoStatementUpdateCase = SObjectCreator.createCaseInfoStatementUpdate();
        testInfoStatementUpdateCase.AccountId = testAccount.Id;
        testInfoStatementUpdateCase.Billing_Account__c = testBillingAccount.Id;
        testInfoStatementUpdateCase.Billing_Account_Quoted__c = true;
        testInfoStatementUpdateCase.Property__c = testProperty.Id;
        testInfoStatementUpdateCase.Street__c = 'Test Street';
        testInfoStatementUpdateCase.City__c = 'Test City';
        testInfoStatementUpdateCase.State__c = 'TestState';
        testInfoStatementUpdateCase.Postcode__c = '1234';
        testInfoStatementUpdateCase.Country__c = 'Test Country';
        testInfoStatementUpdateCase.Address_Available__c = true;
        insert testInfoStatementUpdateCase;
        
        ApexPages.Standardcontroller stdCon = new ApexPages.Standardcontroller(testInfoStatementUpdateCase);
        InfoStatementUpdate_Extension extnCon = new InfoStatementUpdate_Extension(stdCon);
        
        Test.startTest();
        extnCon.performInfoStatementUpdate();
        Test.stopTest();
        
        Tibco_InfoStatementUpdate_MessageTypes.ErrorStatus_element isu = new  Tibco_InfoStatementUpdate_MessageTypes.ErrorStatus_element();
    }

}