sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Billing Account Address</description>
        <label>Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Billing Account Address</description>
        <label>State</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <description>Billing Account Address</description>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Meter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag field that determines if a property belongs to digital meter trial.</description>
        <label>Digital Meter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Setup_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Profile Setup Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>VIC</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/DMTrialMainCC.cls
/**
* @author Original: Adrian Recio Cloud Sherpas
* @date Original: 2/3/2014
* @description Main page controller for all DM Pages
  28-2-2014		ejandusay		maded adjustments on boolean property to hide alert block
*/
public with sharing class DMTrialMainCC {
	Public boolean pSetup{get;set;}
	/**
	* @author Original: Adrian Recio Cloud Sherpas
	* @date Original: 2/3/2014
	* @description Check method that blocks access to pages if profile setup is not yet complete
	*/
	
	public DMTrialMainCC(){
		profileBlock();
	}
	public pageReference profileBlock(){
    	// Check if profile setup is complete
    	pSetup = getProfileSetup();
		
		if(pSetup == true){
			PageReference pgProfile = Page.DMTrialMyProfile;
			pgProfile.setRedirect(true);
			return pgProfile;
		}// End If
		
		return null;
	}// End profileBlock Method
	
	/**
	* @author Original: Adrian Recio Cloud Sherpas
	* @date Original: 2/3/2014
	* @description Method that pulls user profile setup
	*/
    public boolean getProfileSetup(){
    	    	
    	// Pull user details and parent customer(Account)
    	User mainPortalUser = [Select Id, accountId from User where Id = :UserInfo.getUserId()];
    	
    	// Pull Billing Accounts based on user customer(Account)
    	List<Billing_Account__c> billAccountList = [Select Id, Property__r.Id from Billing_Account__c where Customer__c = :mainPortalUser.AccountId];
    	
    	// Pull property Ids from matching billing accounts
		Set<Id> propIdSet = new Set<Id>();
		for(Billing_Account__c billAccVar:billAccountList){
			propIdSet.add(billAccVar.Property__r.Id);
		}
		
		// Pull property details based on retrieve property ids from billing account
		List<Property__c> propertyList = [Select Id, Name,Street_Address__c,Suburb__c,State__c,Postal_Code__c from Property__c where Id In :propIdSet and Digital_Meter__c=true and Profile_Setup_Complete__c=false];
		
		if(propertyList.size()>0){
			return true;
		}// End If
		return false;
    }// End getgetProfileSetup Method   
    
    public void pSetUpHide(){
    	
    	pSetup = false;
    } 
}// End DMTrialMainCC Class