sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Direct_Debit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct Debit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Payment_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Factor__c</fullName>
        <label>Risk Factor</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Adhoc_First_Payment_Amount__c</fullName>
        <label>First Payment Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adhoc_First_Payment_Date__c</fullName>
        <label>First Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Adhoc_Last_Payment_Amount__c</fullName>
        <label>Last Payment Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adhoc_Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Adhoc_Number_of_Payments__c</fullName>
        <label>Number of Payments</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adhoc_Regular_Payment_Amount__c</fullName>
        <label>Regular Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adhoc_Second_Payment_Amount__c</fullName>
        <label>Second Payment Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Adhoc_Second_Payment_Date__c</fullName>
        <label>Second Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Payment_Date__c</fullName>
        <label>First Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The periodic payment amount required for the payment plan</description>
        <inlineHelpText>The periodic payment amount required for the payment plan</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Easypay Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Easypay Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repayment_Frequency__c</fullName>
        <label>Repayment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <inlineHelpText>Total amount to be paid off over the plan period.</inlineHelpText>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>6 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VF_ONLY_Adhoc_First_Payment_Amount__c</fullName>
        <label>First Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VF_ONLY_Adhoc_Last_Payment_Amount__c</fullName>
        <label>Last Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/ManagePaymentPlanExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class ManagePaymentPlanExCon
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class ManagePaymentPlanExCon_Test {

    /* Test method */
    
    public static testmethod void test_ManagePaymentPlanExCon(){
        Account customer = new Account(Name = 'test');
        insert customer;
        
        Billing_Account__c billAcct = new Billing_Account__c(Name = 'TBD', Status__c = 'Active', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = false,HiAF_Account_Number__c = 'sdfsefr', 
                        Direct_Debit__c = true, Customer__c = customer.id);
        insert billAcct;
        PageReference pageRef = Page.ManagePaymentPlan;
        pageRef.getParameters().put('customerId', customer.id);
        pageRef.getParameters().put('billAcctId', billAcct.id);
        Test.setCurrentPage(pageRef);
        ManagePaymentPlanExCon exCon = new ManagePaymentPlanExCon(new ApexPages.StandardController(new Case()));
        Boolean tempBool = exCon.isSEWCreditUserProfile;
        tempBool = exCon.isModifyPlan;
        tempBool = exCon.isEstimatedOnce;
        exCon.managePaymentPlanMode = null;
        Integer tempInt = exCon.managePaymentPlanStepNo;
        System.AssertEquals(false,exCon.isClosedOrAdHoc);
        exCon.refreshCustomerDetails();
        exCon.setModeToRemove();
        exCon.setModeToAdd();
        exCon.setModeToModify();
        exCon.estimatePaymentPlan();
        exCon.currentCase.Term__c = '24 months';
        exCon.estimatePaymentPlan();
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Repayment_Frequency__c = 'Monthly';
        exCon.currentCase.Payment_Amount__c = 1.0;
        exCon.currentCase.First_Payment_Date__c = Date.today();
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Payment_Method__c = null;
        exCon.confirmPaymentMethod();
        exCon.currentCase.Payment_Method__c = 'test';
        exCon.confirmPaymentMethod();
        exCon.currentCase.Payment_Method__c = 'Direct Debit';
        exCon.confirmPaymentMethod();
        exCon.submitPaymentPlan();
        String tempStr = excon.directDebitURLAmendPrefix;
        tempStr = excon.directDebitURLCancelPrefix;
        exCon.backOneStep();
        exCon.removePaymentPlan();
        
        billAcct.Status__c = 'Closed';
        billAcct.Direct_Debit__c = false;
        update billAcct;
        exCon = new ManagePaymentPlanExCon(new ApexPages.StandardController(new Case()));
        System.AssertEquals(true,exCon.isClosedOrAdHoc);
        exCon.setModeToAdd();
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 1;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_First_Payment_Date__c = Date.today();
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 2;
        exCon.currentCase.Adhoc_First_Payment_Amount__c = null;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Second_Payment_Amount__c = 1.0;
        exCon.currentCase.Adhoc_Second_Payment_Date__c = Date.today();
        exCon.currentCase.Adhoc_First_Payment_Amount__c = 1.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 3;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Last_Payment_Amount__c = 1.0;
        exCon.currentCase.Adhoc_Last_Payment_Date__c = Date.today();
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 5;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Repayment_Frequency__c = 'Monthly';
        exCon.currentCase.Adhoc_Regular_Payment_Amount__c = 1.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.VF_ONLY_Adhoc_First_Payment_Amount__c = -1.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.VF_ONLY_Adhoc_Last_Payment_Amount__c = -1.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.VF_ONLY_Adhoc_First_Payment_Amount__c = 1.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.VF_ONLY_Adhoc_Last_Payment_Amount__c = 1.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 2;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Second_Payment_Amount__c = 25.0;
        exCon.currentCase.Adhoc_Second_Payment_Date__c = Date.today();
        exCon.currentCase.Adhoc_First_Payment_Amount__c = 25.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 3;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Second_Payment_Amount__c = 20.0;
        exCon.currentCase.Adhoc_First_Payment_Amount__c = 20.0;
        exCon.currentCase.Adhoc_Last_Payment_Amount__c = 10.0;
        exCon.currentCase.Adhoc_Last_Payment_Date__c = Date.today();
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Adhoc_Number_of_Payments__c = 5;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Repayment_Frequency__c = 'Monthly';
        exCon.currentCase.Adhoc_Regular_Payment_Amount__c = 10.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.VF_ONLY_Adhoc_First_Payment_Amount__c = 10.0;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.VF_ONLY_Adhoc_Last_Payment_Amount__c = null;
        exCon.confirmPaymentCalculation();
        exCon.currentCase.Payment_Method__c = null;
        exCon.confirmPaymentMethod();
        exCon.currentCase.Payment_Method__c = 'Direct Debit';
        exCon.confirmPaymentMethod();
        exCon.currentCase.Payment_Method__c = 'test';
        exCon.confirmPaymentMethod();
        tempBool = exCon.isCentrePay;
        
    }
}