sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Direct_Debit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct Debit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Payment_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Plan?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Risk_Factor__c</fullName>
        <label>Risk Factor</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Payment_Date__c</fullName>
        <label>First Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FutureStreetAddress__c</fullName>
        <label>Future Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>The periodic payment amount required for the payment plan</description>
        <inlineHelpText>The periodic payment amount required for the payment plan</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Repayment_Frequency__c</fullName>
        <label>Repayment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>The first 255 characters of the full description will be automatically copied here.</description>
        <inlineHelpText>If blank , the first 255 characters of the full description will be automatically copied here.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <inlineHelpText>Total amount to be paid off over the plan period.</inlineHelpText>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>6 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used on Classfication Codes button.</description>
    <label>Classification</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification_Code__c.object
<CustomObject>
    <description>Classification codes for customers</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Identifies if the classification code is active for use</description>
        <inlineHelpText>Identifies if the classification code is active for use</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description for the customer classification</description>
        <inlineHelpText>Short Description for the customer classification</inlineHelpText>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Classification Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Customer_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Warnings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <formula>Billing_Account__r.HiAF_Account_Number__c</formula>
        <label>HiAF Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Identifies if the classification is still active against the Customer/Billing Account</description>
        <inlineHelpText>Identifies if the classification is still active against the Customer/Billing Account</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalPaymentPlanWizard_Controller_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalPaymentPlanWizard_Controller
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/

@isTest
private class PortalPaymentPlanWizard_Controller_Test {

    /* TEST METHOD */
   public static testmethod void processEmailTest(){
   		Account a = PortalTestHelper.createNonResiCustomer();
        Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        	u.FirstName = 'testFirstName';
        //test data for balance and property with value not equal to null
		Property__c p = PortalTestHelper.createProperties(1, 'XYZ')[0]; 
		    
        Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p);
	        ba.Balance__c = 10.00;
	        ba.Direct_Debit__c = true;
        update ba;
        ApexPages.StandardController sc = new ApexPages.StandardController(new Case());
        Test.startTest();
	        System.runAs(u) {
	        	PortalPaymentPlanWizard_Controller con = new PortalPaymentPlanWizard_Controller(sc);
	        	con.paymentPlanEmailName = 'PaymentPlanLoaded';
	        	con.currentCase.Repayment_Frequency__c = 'Monthly';
	        	con.currentCase.First_Payment_Date__c = date.today();
	        	con.currentCase.Payment_Amount__c = 125.00;
	        	con.userVar.FirstName = u.FirstName;
	        	con.paymentPlanProcessEmail();
	        	u.FirstName = null;
	        	con.paymentPlanEmailName = 'PaymentPlanCancelled';
	        	con.paymentPlanProcessEmail();
	        	con.hideEmailNotifPanel();
	        }
	    Test.stopTest();
   }
   public static testmethod void test_PortalSegment_Controller(){
    Account a = PortalTestHelper.createResiCustomer();
    Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        PortalTestHelper.CreateDefaultTaskOwner();
        Billing_Account__c billAcct = new Billing_Account__c(Name = 'TBD', Status__c = 'Active', 
                        Balance__c = 600, Risk_Factor__c = 'H', Is_Payment_Plan__c = true,HiAF_Account_Number__c = 'sdfsefr', 
                        Direct_Debit__c = true, Customer__c = a.id);
      insert billAcct;
      Billing_Account__c billAcct2 = new Billing_Account__c(Name = 'TBD2', Status__c = 'Active', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = false,HiAF_Account_Number__c = 'sdfsefra', 
                        Direct_Debit__c = true, Customer__c = a.id);
      insert billAcct2;
     
      Billing_Account__c billAcct3 = new Billing_Account__c(Name = 'TBD3', Status__c = 'Active', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = false,HiAF_Account_Number__c = 'sdfsefra3', 
                        Direct_Debit__c = false, Customer__c = a.id);
      insert billAcct3;
      Classification_Code__c code1;
      try {
            code1 = [SELECT name, Is_Active__c, Short_Description__c FROM Classification_Code__c WHERE name = 'CL'];
      } catch (QueryException e) {
            code1 = new Classification_Code__c();
            code1.Name = 'CL';
            code1.Is_Active__c = true;
            code1.Short_Description__c = 'Foo';         
            insert code1;
      }
        
      Customer_Classification__c customer_class1 = new Customer_Classification__c(Customer__c = a.id, Billing_Account__c = billAcct.id, Classification__c = code1.Id);
      Database.insert(customer_class1);
        
      PageReference pageRef = Page.PortalPaymentPlan_Select;
      pageRef.getParameters().put('billAcctId', billAcct.id);
      Test.setCurrentPage(pageRef);
      
      ApexPages.StandardController sc = new ApexPages.StandardController(new Case());
      System.runAs(u){
      Test.StartTest();
      PortalPaymentPlanWizard_Controller pc = new PortalPaymentPlanWizard_Controller(sc);   
      pc.setBillingAccount();
      pc.calculatePaymentPlan();
      //valid Account
      pageRef = Page.PortalPaymentPlan_Select;
      pageRef.getParameters().put('billAcctId', billAcct2.id);
      Test.setCurrentPage(pageRef);
      sc = new ApexPages.StandardController(new Case());
      pc = new PortalPaymentPlanWizard_Controller(sc);  
      pc.getPlanDurationList();
        pc.getPlanFrequencyList();
      pc.currentCase.Billing_Account__c = billAcct2.id;
      pc.setBillingAccount();
      pc.currentCase.Term__c = '6 months';
      pc.currentCase.Repayment_Frequency__c = 'Monthly';
      
      pc.calculatePaymentPlan();
      System.assertEquals(true,pc.isValidForEstimate());
      pc.setPAmount();
      pc.currentCase.Payment_Amount__c = 1.0;
      //invalid payment date
        pc.currentCase.First_Payment_Date__c = Date.today()+22;
        pc.currentCase.FutureStreetAddress__c = 'test';
      pc.selectPaymentMethod();
      //errorMessagePaymentDate
      System.assertEquals(false,pc.confirmPaymentPlan());
      pc.currentCase.First_Payment_Date__c = Date.today();
      System.assertEquals(false,pc.confirmPaymentPlan());
      pc.currentCase.First_Payment_Date__c = null;
      System.assertEquals(false,pc.confirmPaymentPlan());
      
      pc.currentCase.First_Payment_Date__c = Date.today()+1;
      pc.selectPaymentMethod();
      //validMessagePaymentDate
      System.assertEquals(true,pc.confirmPaymentPlan());
      pc.DDCon.userInputFields.DD_Account_Type__c = 'Bank Account';
      pc.DDCon.userInputFields.DD_Financial_Institution__c = 'testName';
      pc.DDCon.userInputFields.DD_BSB_No__c = '123456';
      pc.DDCon.userInputFields.DD_Account_No__c = '123456';
      pc.DDCon.userInputFields.DD_Account_Name__c = 'Test User';
      pc.DDCon.agreedTerms = true;
      pc.confirmDirectDebit();
      pc.registerDeregisterCustomer();
      
        pc.fullCancel();
      }
      
      
   }
   
   public static testmethod void test_PortalSegment_Controller2(){
    Account a = PortalTestHelper.createResiCustomer();
    Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        
        Property__c p = PortalTestHelper.createProperties(1, 'XYZ')[0];
      Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p);
      ba.Direct_Debit__c = true;
      update ba;
        PortalTestHelper.CreateDefaultTaskOwner();
        
      Billing_Account__c billAcct3 = new Billing_Account__c(Name = 'TBD3', Status__c = 'Closed', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = false,HiAF_Account_Number__c = 'sdfsefra3', 
                        Direct_Debit__c = false, Customer__c = a.id);
      insert billAcct3;
      Classification_Code__c code1;
      try {
            code1 = [SELECT name, Is_Active__c, Short_Description__c FROM Classification_Code__c WHERE name = 'CL'];
      } catch (QueryException e) {
            code1 = new Classification_Code__c();
            code1.Name = 'CL';
            code1.Is_Active__c = true;
            code1.Short_Description__c = 'Foo';         
            insert code1;
      }
        
      
      PageReference pageRef = Page.PortalPaymentPlan_Select;
      Test.setCurrentPage(pageRef);
      
      ApexPages.StandardController sc = new ApexPages.StandardController(new Case());
      System.runAs(u){
      Test.StartTest();
      PortalPaymentPlanWizard_Controller pc = new PortalPaymentPlanWizard_Controller(sc);   
      pc.setBillingAccount();
      pageRef.getParameters().put('billAcctId', billAcct3.id);
      pc.setBillingAccount();
      System.assertEquals(0,pc.paymentAmount);
        System.assertEquals(0,pc.paymentAmountMonthly);
        System.assertEquals(0,pc.paymentAmountFortnight);
      pc.currentCase.Term__c = '6 months';
      pc.currentCase.Repayment_Frequency__c = 'Fortnightly';
      pc.calculatePaymentPlan();
      pc.setPAmount();
      pc.currentCase.Payment_Amount__c = 1.0;
      //invalid payment date
        pc.currentCase.First_Payment_Date__c = Date.today()+1;
        pc.currentCase.FutureStreetAddress__c = 'test';
      pc.selectPaymentMethod();
      pc.selectFirstPage();
      pc.DDCon.userInputFields.DD_Account_Type__c = 'Bank Account';
      pc.DDCon.userInputFields.DD_Financial_Institution__c = 'testName';
      pc.DDCon.userInputFields.DD_BSB_No__c = '123456';
      pc.DDCon.userInputFields.DD_Account_No__c = '123456';
      pc.DDCon.userInputFields.DD_Account_Name__c = 'Test User';
      pc.DDCon.agreedTerms = true;
      pc.confirmDirectDebit();
      pc.registerDeregisterCustomer();
      pc.submitPaymentPlanCall();
      System.assertEquals(true, pc.submitPaymentPlanResult);
      }
   }
   
   public static testmethod void test_PortalSegment_Controller3(){
    Account a = PortalTestHelper.createResiCustomer();
    Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        PortalTestHelper.CreateDefaultTaskOwner();
        Billing_Account__c billAcct = new Billing_Account__c(Name = 'TBD', Status__c = 'Active', 
                        Balance__c = 600, Risk_Factor__c = 'H', Is_Payment_Plan__c = true,HiAF_Account_Number__c = 'sdfsefr', 
                        Direct_Debit__c = true, Customer__c = a.id);
      insert billAcct;
      Billing_Account__c billAcct2 = new Billing_Account__c(Name = 'TBD2', Status__c = 'Active', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = false,HiAF_Account_Number__c = 'sdfsefra', 
                        Direct_Debit__c = true, Customer__c = a.id);
      insert billAcct2;
     
      Billing_Account__c billAcct3 = new Billing_Account__c(Name = 'TBD3', Status__c = 'Active', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = false,HiAF_Account_Number__c = 'sdfsefra3', 
                        Direct_Debit__c = false, Customer__c = a.id);
      insert billAcct3;
      Classification_Code__c code1;
      try {
            code1 = [SELECT name, Is_Active__c, Short_Description__c FROM Classification_Code__c WHERE name = 'CL'];
      } catch (QueryException e) {
            code1 = new Classification_Code__c();
            code1.Name = 'CL';
            code1.Is_Active__c = true;
            code1.Short_Description__c = 'Foo';         
            insert code1;
      }
        
      Customer_Classification__c customer_class1 = new Customer_Classification__c(Customer__c = a.id, Billing_Account__c = billAcct.id, Classification__c = code1.Id);
      Database.insert(customer_class1);
        
      PageReference pageRef = Page.PortalPaymentPlan_Select;
      pageRef.getParameters().put('billAcctId', billAcct.id);
      Test.setCurrentPage(pageRef);
      
      ApexPages.StandardController sc = new ApexPages.StandardController(new Case());
      System.runAs(u){
      Test.StartTest();
      PortalPaymentPlanWizard_Controller pc = new PortalPaymentPlanWizard_Controller(sc);   
      pc.setBillingAccount();
      pc.calculatePaymentPlan();
      //valid Account
      pageRef = Page.PortalPaymentPlan_Select;
      pageRef.getParameters().put('billAcctId', billAcct2.id);
      Test.setCurrentPage(pageRef);
      sc = new ApexPages.StandardController(new Case());
      pc = new PortalPaymentPlanWizard_Controller(sc);  
      pc.getPlanDurationList();
        pc.getPlanFrequencyList();
      pc.currentCase.Billing_Account__c = billAcct2.id;
      pc.setBillingAccount();
      pc.currentCase.Term__c = '12 months';
      pc.currentCase.Repayment_Frequency__c = 'Monthly';
      
      pc.calculatePaymentPlan();
      System.assertEquals(true,pc.isValidForEstimate());
      pc.setPAmount();
      pc.currentCase.Payment_Amount__c = 22.0;
      //invalid payment date
        pc.currentCase.First_Payment_Date__c = Date.today()+22;
        pc.currentCase.FutureStreetAddress__c = 'test';
      pc.selectPaymentMethod();
      //errorMessagePaymentDate
      System.assertEquals(false,pc.confirmPaymentPlan());
      pc.currentCase.First_Payment_Date__c = Date.today();
      System.assertEquals(false,pc.confirmPaymentPlan());
      pc.currentCase.First_Payment_Date__c = null;
      System.assertEquals(false,pc.confirmPaymentPlan());
      
      pc.currentCase.First_Payment_Date__c = Date.today()+1;
      pc.selectPaymentMethod();
      //validMessagePaymentDate
      System.assertEquals(true,pc.confirmPaymentPlan());
      pc.DDCon.userInputFields.DD_Account_Type__c = 'Credit Card';
      pc.DDCon.userInputFields.Credit_Card_Type__c = 'Visa';
      pc.DDCon.userInputFields.Credit_Card_Number_1__c = '4005';
      pc.DDCon.userInputFields.Credit_Card_Number_2__c = '5500';
      pc.DDCon.userInputFields.Credit_Card_Number_3__c = '0000';
      pc.DDCon.userInputFields.Credit_Card_Number_4__c = '0001';
      pc.DDCon.userInputFields.Expiration_Date_Month__c = '12';
      pc.DDCon.userInputFields.Expiration_Date_Year__c = Date.today().addYears(1).year() + '';
      pc.DDCon.userInputFields.Name_on_Card__c = 'Test User';
      pc.DDCon.userInputFields.CVN__c = '123';
      pc.DDCon.agreedTerms = true;
      pc.confirmDirectDebit();
      Test.stopTest();
      pc.registerDeregisterCustomer();
      pc.submitPaymentPlanCall();
      System.assertEquals(true, pc.submitPaymentPlanResult);
      }
      
      
   }
   
   public static testmethod void test_PortalSegment_ControllerRemove(){
    Account a = PortalTestHelper.createResiCustomer();
    Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        PortalTestHelper.CreateDefaultTaskOwner();
        
      Billing_Account__c billAcct3 = new Billing_Account__c(Name = 'TBD3', Status__c = 'Active', 
                        Balance__c = 50, Risk_Factor__c = 'L', Is_Payment_Plan__c = true,HiAF_Account_Number__c = 'sdfsefra3', 
                        Direct_Debit__c = false, Customer__c = a.id);
      insert billAcct3;
      Classification_Code__c code1;
      try {
            code1 = [SELECT name, Is_Active__c, Short_Description__c FROM Classification_Code__c WHERE name = 'CL'];
      } catch (QueryException e) {
            code1 = new Classification_Code__c();
            code1.Name = 'CL';
            code1.Is_Active__c = true;
            code1.Short_Description__c = 'Foo';         
            insert code1;
      }
        
      
      PageReference pageRef = Page.PortalPaymentPlan_Select;
      pageRef.getParameters().put('billAcctId', billAcct3.id);
      Test.setCurrentPage(pageRef);
      
      ApexPages.StandardController sc = new ApexPages.StandardController(new Case());
      System.runAs(u){
      Test.StartTest();
      PortalPaymentPlanWizard_Controller pc = new PortalPaymentPlanWizard_Controller(sc);  
      pc.CheckRedirectConfirmed(); 
      pc.setBillingAccount();
      pc.removePaymentPlanCall();
      System.assertEquals(true,pc.removePaymentPlanResult);
      
      PortalPaymentPlanWizard_Controller con = new PortalPaymentPlanWizard_Controller(sc, true, billAcct3.id);
      }
   }
}