sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Concession_Holder__c</fullName>
        <inlineHelpText>Relationship to the Billing Account holder.</inlineHelpText>
        <label>Concession Holder</label>
        <picklist>
            <picklistValues>
                <fullName>Account Holder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/C Holder Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Valid_Concession__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Concession</label>
        <type>Checkbox</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Alerts_Int_Long__c</fullName>
        <label>Alerts</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Authority_to_Transact__c</fullName>
        <label>Authority to Transact?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <inlineHelpText>What is the case or activity about?</inlineHelpText>
        <label>What</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Payments &amp; Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Reform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_2__c</fullName>
        <inlineHelpText>Why is the case or activity occurring?</inlineHelpText>
        <label>Why</label>
        <picklist>
            <controllingField>Category_Level_1__c</controllingField>
            <picklistValues>
                <fullName>Account/Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns &amp; Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Recovery Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Receive Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficiency Programs &amp; Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Explanation of Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot Issues - Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Statement Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Readings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In / Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Customer/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Off/On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Restrictions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Injury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tappings/Pluggings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_3__c</fullName>
        <inlineHelpText>The solution, the response, the process - the case creation</inlineHelpText>
        <label>How</label>
        <picklist>
            <controllingField>Category_Level_2__c</controllingField>
            <picklistValues>
                <fullName>Acceptance of Works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access to Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Balance/Due Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Amend Concession Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Hoc Billing Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Meter Reading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Property Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog Sewer Charges Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Debt Recommendation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy and  Liquidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build overs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Opt In/Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caveat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Occupier Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check for Tampering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent to connect Water or Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Classifaction Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read Taken</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Concession_Holder__c</fullName>
        <label>Concession Holder</label>
        <picklist>
            <picklistValues>
                <fullName>Account Holder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/C Holder Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Information_Int_Long__c</fullName>
        <label>Information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Privacy_Statement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Privacy Statement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Received_Application_Form__c</fullName>
        <inlineHelpText>Has application form been received?</inlineHelpText>
        <label>Received Application Form?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Concession__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid Concession</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Concession</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Create and Update Concession</description>
        <label>Concession</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/SystemSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Disable_Web_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check to stop web service callout and use test code instead</inlineHelpText>
        <label>Disable Web Services</label>
        <type>Checkbox</type>
    </fields>
    <label>SystemSettings</label>
</CustomObject>

sample/retrieveUnpackaged/classes/ConcessionExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class ConcessionExCon
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class ConcessionExCon_Test {

    /* Test Method */
    public static testmethod void test_ConcessionExConAcctHolder(){
        Account acc = new Account(name='test parent');
        insert acc;
        Billing_Account__c ba = new Billing_Account__c(name='test', customer__c=acc.Id, HiAF_Account_Number__c='1234');
        insert ba;

        // concession senarios
        Case c = new Case(account=acc, Billing_Account__c=ba.Id);
        c.Category_Level_3__c = 'Bookings';
        c.Category_Level_1__c = 'Billing';
        c.Category_Level_2__c = 'Billing';
        insert c;

        // get custom settings, update if already there
        SystemSettings__c cs;
        try {
            cs = [select id, setupOwnerId, Disable_Web_Services__c from SystemSettings__c limit 1];
        } catch (QueryException e) {
            cs = new SystemSettings__c();
            insert cs;
        }

        ApexPages.StandardController con = new ApexPages.StandardController(c);
        ConcessionExCon excon = new ConcessionExCon(con);

        excon.submitConcession();   // privacy statement = false
        System.assertEquals(true, ApexPages.hasMessages());

        // concession senarios - Account Holder
        c.Concession_Holder__c = 'Account Holder';
        c.Privacy_Statement__c = true;
        update c;
        con = new ApexPages.StandardController(c);
        excon = new ConcessionExCon(con);
        excon.submitConcession();

        Case cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(cse.Valid_Concession__c);

        // test submitConcession exception
        cs.Disable_Web_Services__c = true;
        update cs;
        excon.submitConcession();

        cs.Disable_Web_Services__c = false;
        update cs;
    }

    public static testmethod void test_ConcessionExConAcctHolderPartner(){
        Account acc = new Account(name='test parent');
        insert acc;
        Billing_Account__c ba = new Billing_Account__c(name='test', customer__c=acc.Id, HiAF_Account_Number__c='1234');
        insert ba;

        // concession senarios
        Case c = new Case(account=acc, Billing_Account__c=ba.Id);
        // concession senarios - A/C Holder Partner
        c.Concession_Holder__c = 'A/C Holder Partner';
        c.Privacy_Statement__c = true;
        c.Category_Level_3__c = 'Bookings';
        c.Category_Level_1__c = 'Billing';
        c.Category_Level_2__c = 'Billing';
        insert c;

        // get custom settings, update if already there
        SystemSettings__c cs;
        try {
            cs = [select id, setupOwnerId, Disable_Web_Services__c from SystemSettings__c limit 1];
        } catch (QueryException e) {
            cs = new SystemSettings__c();
            insert cs;
        }

        ApexPages.StandardController con = new ApexPages.StandardController(c);
        ConcessionExCon excon = new ConcessionExCon(con);

        excon.submitConcession();
        Case cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(cse.Valid_Concession__c);

        // concession senario - A/C Holder Partner, no authority to transact
        c.Authority_to_Transact__c = 'No';
        update c;
        con = new ApexPages.StandardController(c);
        excon = new ConcessionExCon(con);
        excon.CloseCase();
        cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(!cse.Valid_Concession__c);
    }

    public static testmethod void test_ConcessionExConThirdParty(){
        Account acc = new Account(name='test parent');
        insert acc;
        Billing_Account__c ba = new Billing_Account__c(name='test', customer__c=acc.Id, HiAF_Account_Number__c='1234');
        insert ba;

        // concession senarios
        Case c = new Case(account=acc, Billing_Account__c=ba.Id);
        // concession senario - Third Party, received application form, submit concession
        c.Concession_Holder__c = 'Third Party';
        c.Received_Application_Form__c = 'Yes';
        c.Privacy_Statement__c = true;
        c.Category_Level_3__c = 'Bookings';
        c.Category_Level_1__c = 'Billing';
        c.Category_Level_2__c = 'Billing';
        insert c;

        // get custom settings, update if already there
        SystemSettings__c cs;
        try {
            cs = [select id, setupOwnerId, Disable_Web_Services__c from SystemSettings__c limit 1];
        } catch (QueryException e) {
            cs = new SystemSettings__c();
            insert cs;
        }

        ApexPages.StandardController con = new ApexPages.StandardController(c);
        ConcessionExCon excon = new ConcessionExCon(con);

        excon.submitConcession();
        Case cse = [select Valid_Concession__c, Information_Int_Long__c, Alerts_Int_Long__c from Case where Id = :c.Id];
        Test.startTest();
        System.assert(cse.Valid_Concession__c);
        // concession senario - Third Party, submit concession
        c.Concession_Holder__c = 'Third Party';
        c.Received_Application_Form__c = 'No';
        c.Received_Evidence_of_Responsibility__c = 'Yes';
        c.Privacy_Statement__c = true;
        update c;
        con = new ApexPages.StandardController(c);
        excon = new ConcessionExCon(con);
        excon.submitConcession();
        cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(cse.Valid_Concession__c);

        // concession senario - Third Party, send application form, billing account address
        c.Concession_Holder__c = 'Third Party';
        c.Received_Application_Form__c = 'No';
        c.Received_Evidence_of_Responsibility__c = 'No';
        c.Send_Application_Form__c = 'Yes';
        update c;
        con = new ApexPages.StandardController(c);
        excon = new ConcessionExCon(con);
        excon.bBillAddr = true;
        excon.bPropAddr = false;
        excon.submitAppForm();
        cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(!cse.Valid_Concession__c);
        // concession senario - Third Party, send application form, property address
        c.Concession_Holder__c = 'Third Party';
        c.Received_Application_Form__c = 'No';
        c.Received_Evidence_of_Responsibility__c = 'No';
        c.Send_Application_Form__c = 'Yes';
        update c;
        con = new ApexPages.StandardController(c);
        excon = new ConcessionExCon(con);
        excon.bPropAddr = true;
        excon.bBillAddr = false;
        excon.submitAppForm();
        cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(!cse.Valid_Concession__c);
        // test submitAppForm exception
        cs.Disable_Web_Services__c = true;
        update cs;
        excon.submitAppForm();

        cs.Disable_Web_Services__c = false;
        update cs;
        Test.stopTest();
    }

    public static testmethod void test_ConcessionExConOther(){
        Account acc = new Account(name='test parent');
        insert acc;
        Billing_Account__c ba = new Billing_Account__c(name='test', customer__c=acc.Id, HiAF_Account_Number__c='1234');
        insert ba;

        // concession senarios
        Case c = new Case(account=acc, Billing_Account__c=ba.Id);
        c.Category_Level_3__c = 'Bookings';
        c.Category_Level_1__c = 'Billing';
        c.Category_Level_2__c = 'Billing';
        insert c;

        // get custom settings, update if already there
        SystemSettings__c cs;
        try {
            cs = [select id, setupOwnerId, Disable_Web_Services__c from SystemSettings__c limit 1];
        } catch (QueryException e) {
            cs = new SystemSettings__c();
            insert cs;
        }

        ApexPages.StandardController con = new ApexPages.StandardController(c);
        ConcessionExCon excon = new ConcessionExCon(con);
        excon.SelectAccount();

        // delete concession
        c.Delete_Reason__c = 'test';
        update c;
        excon.deleteConcession();
        Case cse = [select Valid_Concession__c from Case where Id = :c.Id];
        System.assert(!cse.Valid_Concession__c);

        // test deleteConcession exception
        cs.Disable_Web_Services__c = true;
        update cs;
        excon.deleteConcession();

        // general exceptions
        Account acc1 = new Account(name='test parent');
        insert acc1;
        Billing_Account__c ba1 = new Billing_Account__c(name='test', customer__c=acc1.Id, HiAF_Account_Number__c='9876');
        insert ba1;

        Case c1 = new Case(account=acc1, Billing_Account__c=ba1.Id);
        c1.Category_Level_3__c = 'Bookings';
        c1.Category_Level_1__c = 'Billing';
        c1.Category_Level_2__c = 'Billing';
        insert c1;
        ApexPages.StandardController con1 = new ApexPages.StandardController(c1);
        ConcessionExCon excon1 = new ConcessionExCon(con1);
        excon1.submitConcession();
        System.assertEquals(true, ApexPages.hasMessages());
        excon1.submitAppForm();
        System.assertEquals(true, ApexPages.hasMessages());
        excon1.deleteConcession();
        System.assertEquals(true, ApexPages.hasMessages());
    }
    
    private static TestMethod void testMe2() {
        ApexPages.StandardController con = new ApexPages.StandardController(new Case());
        ConcessionExCon excon = new ConcessionExCon(con);   
    }
}