sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Livelink__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Livelink Document</label>
    <nameField>
        <label>Filename</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livelink Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/LiveLink_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class LiveLink
    ---------------------------------------------------------------
    History:

    24-Feb-2014 G Tsaousidis	   Created
*/

@isTest
private class LiveLink_Test {

	private static TestMethod void TestMe() {
		Profile profile = [select id from profile where name='SEW CSO (Customer Service Officer)'];
		User u = new User(alias = 'fgjdf', email='dfjdfh@dfhxfgh.com',
		
        emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
        localesidkey='en_US', profileid = profile.Id,
        timezonesidkey='America/Los_Angeles', username='djgf@hjgfhj.com');
       	insert u;

       	System.runAs(u) {

            Account a = SObjectCreator.createAccountNonResidentialCompany();
            insert a;
            Property__c p = SObjectCreator.createProperty();
            insert p;

            // create billing account
            Billing_Account__c ba = new Billing_Account__c();
            ba.Customer__c = a.id;
            ba.Property__c = p.id;
            insert ba;

            // create the livelink object
            Livelink__c ll = new LiveLink__c(name='x', billing_account__c=ba.id);
            insert ll;

            system.assert([select customer__c from livelink__c where id = :ll.id].customer__c == a.id);
            system.assert([select property__c from livelink__c where id = :ll.id].property__c == p.id);

       }

    }
}