sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/SystemSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Disable_Web_Services__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check to stop web service callout and use test code instead</inlineHelpText>
        <label>Disable Web Services</label>
        <type>Checkbox</type>
    </fields>
    <label>SystemSettings</label>
</CustomObject>

sample/retrieveUnpackaged/classes/PaymentHistoryExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PaymentHistoryExCon_Test
    ---------------------------------------------------------------
    History:

    25-Feb-2014 G Tsaousidis   Created
*/

@isTest
private class PaymentHistoryExCon_Test {

 /* Test Method */
    public static testmethod void test_PaymentHistoryExCon(){
        Account acc = new Account(name='test parent');
        insert acc;
        
        Billing_Account__c ba = new Billing_Account__c(name='test', customer__c=acc.Id, HiAF_Account_Number__c='1234');
        insert ba;
        
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(ba);
        PaymentHistoryExCon excon = new PaymentHistoryExCon(sc);
        System.assertEquals(excon.billingAcc.HiAF_Account_Number__c, '1234');
        if (excon.payments!=null) {
            System.assert(excon.payments.size() > 0);
            System.assert(excon.paymentNum > 0);
        }
        
        // get custom settings, update if already there
        SystemSettings__c cs;
        try {
            cs = [select id, setupOwnerId, Disable_Web_Services__c from SystemSettings__c limit 1];
        } catch (QueryException e) {
            cs = new SystemSettings__c();
            insert cs;
        }
        cs.Disable_Web_Services__c = true;
        update cs;          
        PaymentHistoryExCon excon1 = new PaymentHistoryExCon(sc);
        System.assertEquals(true, ApexPages.hasMessages());
        
        TibcoPaymentHistory_MessageTypes.Billing_element be = new  TibcoPaymentHistory_MessageTypes.Billing_element();
        TibcoPaymentHistory_MessageTypes.ProcessInputData_element pid = new TibcoPaymentHistory_MessageTypes.ProcessInputData_element();
        
        test.stopTest();        
    }  
}