sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Livelink__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Livelink_Records</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Livelink Document</label>
    <nameField>
        <label>Filename</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livelink Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/LiveLink.cls
public with sharing class LiveLink {

/*
    Type:       Utility Class
    Purpose:    DefaultFieldsFromBAcct ()
                - default the property and customer from bacct

    Used By:    LiveLinkTrigger
    ---------------------------------------------------------------
    History:
        27-Sep-2011 - 	D.Thong (SFDC)   	Created
        24-Feb-2014 	G Tsaousidis	   	Created
*/

    // Default the customer from the billing account
    public static void DefaultFieldsFromBAcct(List<LiveLink__c> lls) {
        Set<Id> bAcctIds = new Set<Id>();
        Map<Id, Billing_Account__c> bAcctIdMap = new Map<Id, Billing_Account__c>();

        // get a set of unique billing account its from the Livelink records
        for (LiveLink__c ll : lls) {
            if (ll.Billing_Account__c != null)
                bAcctIds.add(ll.Billing_Account__c);
        }

        // generate a map of bacct id to customer id
        for (Billing_Account__c ba : [select customer__c, property__c from billing_account__c where id in :bAcctIds]) {
            bAcctIdMap.put(ba.id, ba);
        }

        // update the case to the new customer
        for (LiveLink__c ll : lls) {
            if (ll.Billing_Account__c != null) {
                if (ll.Customer__c == null)
                    ll.Customer__c = bAcctIdMap.get(ll.Billing_Account__c).customer__c;
                if (ll.Property__c == null)
                    ll.Property__c = bAcctIdMap.get(ll.Billing_Account__c).Property__c;
            }
        }
    }

}