sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalPageWithCase_Virtual_Con_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalPageWithCase_Virtual_Con
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/
@isTest
private class PortalPageWithCase_Virtual_Con_Test {

    private static TestMethod void TestMe() {
        Account a = PortalTestHelper.createResiCustomer();
        Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        Property__c p = PortalTestHelper.createProperty();
        Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p);
        PortalTestHelper.CreateDefaultTaskOwner();
        
        System.runAs(u) {
            PortalPageWithCase_Virtual_Con con = new PortalPageWithCase_Virtual_Con();
            
            system.assertequals(con.selectedBillingAccount.id, con.caseRec.Billing_Account__c);
            // submit is ok
            system.assert(con.submit() != null);

            // go home
            system.assert(con.home() != null);
            
            System.assert(con.defaultErrorMsg != null);

        }
    }
}