sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Consumption_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Account_Periodic_Consumption_and_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Year__c</fullName>
        <label>Financial Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <description>Number of days in the consumption period (based on meter read dates)</description>
        <inlineHelpText>Number of days in the consumption period (based on meter read dates)</inlineHelpText>
        <label>Number of Days</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recycled_Water_Volume__c</fullName>
        <label>Recycled Water Volume (KL)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Water_Volume__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Water Volume (KL)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Consumption and Charge</label>
    <nameField>
        <label>Consumption Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumption and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalWaterUsageList_Controller_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalWaterUsageList_Controller
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/
@isTest
private class PortalWaterUsageList_Controller_Test {

    private static TestMethod void TestMeMeterReads() {
        Account a = PortalTestHelper.createResiCustomer();
        Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        Property__c p = PortalTestHelper.createProperty();
        Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p);
        Meter_Details__c m = PortalTestHelper.createMeter(p, 'FOOBARMETER');
        Meter_Details__c m2 = PortalTestHelper.createMeter(p, 'RFOOBARMETER');

        
        System.runAs(u) {
            Test.setCurrentPage(Page.PortalWaterUsageList);
            System.currentPageReference().getParameters().put('billAcctId',ba.Id);
            PortalWaterUsageList_Controller con = new PortalWaterUsageList_Controller();
            // test that the selected accounts are correct
            system.assertEquals(con.selectedBillingAccountId, ba.id);
            system.assert(con.noMeterReads);
            
            // test default meter
            con.PopulateSelectedBillingAccountandMeter();
            system.assertEquals(con.selectedMeterId, m.id);
            system.assertEquals(con.selectedMeter.id, m.id);
            
            // test options
            system.assert(con.meterOptions.size() > 1);
            
            // test avg
            system.assert(con.selectedAvgDailyConsumptionAry.size() == 6);
            system.assert(!con.noMeterReads);
            
            // test usage types
            system.assert(con.usageTypes.size() == 2);
            
            // no real data here, so test coverage
            String s1 = con.meterReads[0].billingPeriod;
            String s2 = con.meterReads[0].typeOfReading;
            Decimal d1 = con.meterReads[0].averageDailyConsumption;
            
            system.assert(con.selectedPeriod != null);
            
            con.NoOp();
            
        }   
    }

    private static TestMethod void TestMeUsageChart() {
        Account a = PortalTestHelper.createResiCustomer();
        Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        Property__c p = PortalTestHelper.createProperty();
        Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p);
        Meter_Details__c m = PortalTestHelper.createMeter(p, 'FOOBARMETER');
        Meter_Details__c m2 = PortalTestHelper.createMeter(p, 'RFOOBARMETER');

        Consumption_and_Charge__c charge = new Consumption_and_Charge__c();
        charge.Water_Volume__c = 100;
        charge.Recycled_Water_Volume__c = 5;
        charge.End_Date__c = Date.newInstance(2010, 3, 31);
        charge.Billing_Account__c = ba.id;
        charge.Name = 'Jan-Mar 2010';
        charge.Financial_Year__c = '2009/10';
        charge.Number_of_Days__c = 93;
        insert charge;

        Consumption_and_Charge__c charge2 = new Consumption_and_Charge__c();
        charge2.Water_Volume__c = 200;
        charge2.Recycled_Water_Volume__c = 10;
        charge2.End_Date__c = Date.newInstance(2010, 6, 30);
        charge2.Billing_Account__c = ba.id;
        charge2.Name = 'Apr-Jun 2010';
        charge2.Financial_Year__c = '2009/10';
        charge2.Number_of_Days__c = 93;
        insert charge2;
        
        System.runAs(u) {
            Test.setCurrentPage(Page.PortalWaterUsageChart);
            System.currentPageReference().getParameters().put('billAcctId',ba.Id);
            PortalWaterUsageList_Controller con = new PortalWaterUsageList_Controller();
            // test that the selected accounts are correct
            system.assertEquals(con.selectedBillingAccountId, ba.id);
            system.assert(con.noMeterReads);
            
            // set date ranges
            con.StartYear = '2009/10';
            con.EndYear = '2009/10';
            
            // populate consumption
            con.PopulateSelectedBillingAccountandConsumption();
            
            // test usage types
            system.assert(con.usageTypes.size() == 2);
            
            // test url
            system.assert(con.avgDailyUsageChartURL != null);
            
            // test displayed records
            system.assert(con.displayedConsumptionRecords.size() == 2);
            
            system.assert(con.availableFinYears.size() > 1);
            
        }   
    }
    
    private static TestMethod void TestMeNegative() {
        Account a = PortalTestHelper.createResiCustomer();
        Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        Property__c p = PortalTestHelper.createProperty();
        Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p);
        
        System.runAs(u) {
            Test.setCurrentPage(Page.PortalWaterUsageList);
            PortalWaterUsageList_Controller con = new PortalWaterUsageList_Controller();
            // test that the selected accounts are correct
            system.assertEquals(con.selectedBillingAccountId, ba.id);
            
            // test default meter
            con.PopulateSelectedBillingAccountandMeter();
            system.assert(con.noMeterReads);
            system.assert(con.noConsumptionRecords);
            system.assert(con.meterOptions.size() == 1);
        }
    }
}