sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Consumption_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Account_Periodic_Consumption_and_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Year__c</fullName>
        <label>Financial Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <description>Number of days in the consumption period (based on meter read dates)</description>
        <inlineHelpText>Number of days in the consumption period (based on meter read dates)</inlineHelpText>
        <label>Number of Days</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recycled_Water_Volume__c</fullName>
        <label>Recycled Water Volume (KL)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Water_Volume__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Water Volume (KL)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Consumption and Charge</label>
    <nameField>
        <label>Consumption Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumption and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalWaterUsageComparison_Controll_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalWaterUsageComparison_Controller
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/
@isTest
private class PortalWaterUsageComparison_Controll_Test {

    private static TestMethod void TestMeUsageChart() {
        Account a = PortalTestHelper.createResiCustomer();
        Contact c = PortalTestHelper.createContact(a);
        User u = PortalTestHelper.createUser(c);
        Property__c p = PortalTestHelper.createProperty();
        Property__c p2 = PortalTestHelper.createProperty();
        Billing_Account__c ba = PortalTestHelper.createBillingAccount(a, p, '9999999999');
        Billing_Account__c ba2 = PortalTestHelper.createBillingAccount(a, p2, '9999999998');

        Consumption_and_Charge__c charge = new Consumption_and_Charge__c();
        charge.Water_Volume__c = 100;
        charge.Recycled_Water_Volume__c = 5;
        charge.End_Date__c = Date.newInstance(2010, 3, 31);
        charge.Billing_Account__c = ba.id;
        charge.Name = 'Jan-Mar 2010';
        charge.Financial_Year__c = '2009/10';
        charge.Number_of_Days__c = 93;
        insert charge;

        Consumption_and_Charge__c charge2 = new Consumption_and_Charge__c();
        charge2.Water_Volume__c = 200;
        charge2.Recycled_Water_Volume__c = 10;
        charge2.End_Date__c = Date.newInstance(2010, 6, 30);
        charge2.Billing_Account__c = ba.id;
        charge2.Name = 'Apr-Jun 2010';
        charge2.Financial_Year__c = '2009/10';
        charge2.Number_of_Days__c = 93;
        insert charge2;

        Consumption_and_Charge__c charge3 = new Consumption_and_Charge__c();
        charge3.Water_Volume__c = 999;
        charge3.Recycled_Water_Volume__c = 8;
        charge3.End_Date__c = Date.newInstance(2010, 3, 31);
        charge3.Billing_Account__c = ba2.id;
        charge3.Name = 'Jan-Mar 2010';
        charge3.Financial_Year__c = '2009/10';
        charge3.Number_of_Days__c = 93;
        insert charge3;
        
        System.runAs(u) {
            Test.setCurrentPage(Page.PortalWaterUsageChart);
            PortalWaterUsageComparison_Controller con = new PortalWaterUsageComparison_Controller();

            // negative test
            con.GenerateChart();
            system.assert(con.noConsumptionRecords);
                                    
            // positive test
            con.activeAccountsWithCheckBox[0].isChecked = true;
            con.activeAccountsWithCheckBox[1].isChecked = true;
            con.startYear = '2009/10';
            con.endYear = '2010/11';
            con.GenerateChart();
            system.assert(!con.noConsumptionRecords);
            
            
        }   
    }
}