sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <inlineHelpText>What is the case or activity about?</inlineHelpText>
        <label>What</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Payments &amp; Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Reform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_2__c</fullName>
        <inlineHelpText>Why is the case or activity occurring?</inlineHelpText>
        <label>Why</label>
        <picklist>
            <controllingField>Category_Level_1__c</controllingField>
            <picklistValues>
                <fullName>Account/Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns &amp; Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Recovery Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Receive Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficiency Programs &amp; Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Explanation of Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot Issues - Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Statement Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Readings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In / Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Customer/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Off/On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Restrictions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Injury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tappings/Pluggings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_3__c</fullName>
        <inlineHelpText>The solution, the response, the process - the case creation</inlineHelpText>
        <label>How</label>
        <picklist>
            <controllingField>Category_Level_2__c</controllingField>
            <picklistValues>
                <fullName>Acceptance of Works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access to Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Balance/Due Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Amend Concession Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Hoc Billing Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Meter Reading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Property Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog Sewer Charges Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Debt Recommendation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy and  Liquidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build overs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Opt In/Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caveat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Occupier Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check for Tampering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent to connect Water or Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Classifaction Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read Taken</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suspend_To_Date__c</fullName>
        <label>Suspend To Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/SuspendRecovery_View_Extension_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class SuspendRecovery_View_Extension
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class SuspendRecovery_View_Extension_Test {

    /* TEST METHOD */
    public static testmethod void test_SuspendRecovery_View_Extension(){
        // create test data
        Account account = new Account();
        account.name = 'foo';
        insert account;

        Contact contact = new Contact();
        contact.LastName = 'Foo';
        contact.AccountId = account.id;
        contact.Title = 'x';
        contact.Phone = '0412345678';
        contact.Email = 'x@x.com';
        insert contact;

        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        insert prop;

        Billing_Account__c billAcc = new Billing_Account__c();
        billAcc.Name = 'asetwetwrt';
        billAcc.Customer__c = account.id;
        billAcc.Property__c = prop.id;
        insert billAcc;
        
        billAcc = new Billing_Account__c();
        billAcc.Name = 'asetwetwrt';
        billAcc.Customer__c = account.id;
        billAcc.Property__c = prop.id;
        insert billAcc;
        
        Case suspendRecoveryCase = new Case();
        suspendRecoveryCase.AccountId = account.id;
        suspendRecoveryCase.Billing_Account__c = billAcc.id;
        suspendRecoveryCase.Category_Level_3__c = 'Bookings';
		suspendRecoveryCase.Category_Level_1__c = 'Billing';
		suspendRecoveryCase.Category_Level_2__c = 'Billing';
        
        insert suspendRecoveryCase;
        ApexPages.StandardController stdCon = new ApexPages.StandardController(suspendRecoveryCase);
        SuspendRecovery_View_Extension excon = new SuspendRecovery_View_Extension(stdCon);
        Test.startTest();
        // perform b4 validate
        excon.perform();
        
        // validate without date
        excon.validate();
        
        // validate with date > 14 days
        suspendRecoveryCase.Suspend_To_Date__c = System.today().addDays(15);
        excon.validate();

        // validate < 14 days
        suspendRecoveryCase.Suspend_To_Date__c = System.today();
        excon.validate();
        excon.perform();
        
        excon.back();
        
        TibcoSuspendRecovery_MessageTypes.ErrorStatus_element err = new TibcoSuspendRecovery_MessageTypes.ErrorStatus_element();
        
        Test.StopTest();
        //@10680 - [GT] 30-Sep 
        User intUser = [Select Id from User Where name = 'Integration'];		// This is required to work around the MIXED_DML_EXCEPTION
        User usrExternalUser;
        
        System.RunAs(intUser){    
        Profile pflExternalUser = [SELECT Id FROM Profile WHERE Name = :UserProfileUtil.PROFILE_MERCANTILE_AGENT];
		UserRole rolExternalUser = [SELECT Id FROM UserRole WHERE Name='Mercantile Agency'];
       	usrExternalUser = new User(Alias = 'testExt', Email='external@sew.testmethods.com',
                        EmailEncodingKey='UTF-8', LastName='TestMercAgent', LanguageLocaleKey='en_US',
                        LocaleSidKey='en_US', ProfileId = pflExternalUser.Id, UserRoleId = rolExternalUser.id, 
                        isActive = true, TimeZoneSidKey='America/Los_Angeles', UserName='external@sewl.i.pity.the.foo.com.testmethod');
             
                       
        insert usrExternalUser;
        }
        
        System.RunAs(usrExternalUser){
      
        // perform b4 validate
        excon.perform();
        
        // validate without date
        excon.validate();
        
        // validate with date > 14 days
        suspendRecoveryCase.Suspend_To_Date__c = System.today().addDays(15);
        excon.validate();

        // validate < 14 days
        suspendRecoveryCase.Suspend_To_Date__c = System.today();
        excon.validate();
        excon.perform();
        
        excon.back();
        
        err = new TibcoSuspendRecovery_MessageTypes.ErrorStatus_element();
        
        
        }
        
        
    }
}