sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad-Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <inlineHelpText>What is the case or activity about?</inlineHelpText>
        <label>What</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Payments &amp; Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Reform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_3__c</fullName>
        <inlineHelpText>The solution, the response, the process - the case creation</inlineHelpText>
        <label>How</label>
        <picklist>
            <controllingField>Category_Level_2__c</controllingField>
            <picklistValues>
                <fullName>Acceptance of Works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access to Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Balance/Due Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Amend Concession Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Hoc Billing Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Meter Reading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Property Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog Sewer Charges Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Debt Recommendation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy and  Liquidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build overs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Opt In/Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caveat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Occupier Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check for Tampering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent to connect Water or Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Classifaction Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read Taken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notice of Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Contact Type</description>
        <inlineHelpText>This field contains information that is parsed to BRE for SMR Cases.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchaser_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Also applies to Tenant becomes Purchaser situation.</inlineHelpText>
        <label>Purchaser Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (As Purchaser Account)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Settlement_Date__c</fullName>
        <label>Settlement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tenant_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Not required is Non-Tenancy is picked.</inlineHelpText>
        <label>Tenant Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (AsTenant Account)</relationshipLabel>
        <relationshipName>Cases3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type_of_Read__c</fullName>
        <label>Type of Read</label>
        <picklist>
            <controllingField>Contact_Type__c</controllingField>
            <picklistValues>
                <fullName>Tenant Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Reading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Sale__c</fullName>
        <inlineHelpText>Non Tenant is the new purchase of a property where there is no tenancy</inlineHelpText>
        <label>Type of Sale</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Tenancy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant is Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchaser, Tenant Stays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchaser, Tenant Leaves</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale of Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vendor_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (As Vendor Account)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/SFDCWS_COOTS_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class SFDCWS_COOTS
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class SFDCWS_COOTS_Test {

    /* TEST METHODS */
    public static testmethod void test_SFDCWS_NOS(){

        SFDCWS_COOTS.COOTSOutput output = SFDCWS_COOTS.completeNOS('Crap', 'Crap', false, /*'Crap',*/ 'Crap', new List<SFDCWS_COOTS.ErrorStatus>());
        System.assertEquals(false, output.isSuccess);
        System.assertEquals('Case number not found',output.outputMessages[0].messageDescription);

        //Setup Test Data
        Account testCustomerPurchaser = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerPurchaser;

        Billing_Account__c testPurchaserBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testPurchaserBillingAccount.Customer__c = testCustomerPurchaser.Id;
        testPurchaserBillingAccount.Role__c = 'Owner Occupier';
        insert testPurchaserBillingAccount;


        Account testCustomerVendor = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerVendor;

        Property__c testProperty = SObjectCreator.createProperty();
        insert testProperty;

        Billing_Account__c testVendorBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testVendorBillingAccount.Customer__c = testCustomerVendor.Id;
        testVendorBillingAccount.Role__c = 'Landlord';
        testVendorBillingAccount.Property__c = testProperty.Id;
        insert testVendorBillingAccount;

        Account testCustomerTenant = SObjectCreator.createAccountResidentialCustomer();
        insert testCustomerTenant;

        Billing_Account__c testTenantBillingAccount = SObjectCreator.createBillingAccountBillingAccount();
        testTenantBillingAccount.Customer__c = testCustomerTenant.Id;
        testTenantBillingAccount.Role__c = 'Tenant';
        testTenantBillingAccount.Property__c = testProperty.Id;
        insert testTenantBillingAccount;

        Case testNOSCase = SObjectCreator.createCaseNoticeOfSale();
        testNOSCase.Property__c = testProperty.Id;
        testNOSCase.Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase.Purchaser_Billing_Account__c = testPurchaserBillingAccount.Id;
        testNOSCase.Vendor_Billing_Account__c = testVendorBillingAccount.Id;
        testNOSCase.Tenant_Billing_Account__c = testTenantBillingAccount.Id;
        testNOSCase.Type_of_Sale__c = 'New Purchaser, Tenant Leaves';
        testNOSCase.Settlement_Date__c = system.today()+1;

        testNOSCase.Status = 'Waiting for HiAffinity';
        insert testNOSCase;

        String caseNumber = [Select CaseNumber from Case where id = :testNOSCase.id][0].CaseNumber;

        output = SFDCWS_COOTS.completeNOS(caseNumber, 'Owner Occupier', false, 'Bad Error', new List<SFDCWS_COOTS.ErrorStatus>());
        System.assertEquals(true, output.isSuccess);
        System.assertEquals([Select Status from Case where id = :testNOSCase.id][0].Status, 'Pending');

        output = SFDCWS_COOTS.completeNOS(caseNumber, 'Owner Occupier', true, null, new List<SFDCWS_COOTS.ErrorStatus>());
        System.assertEquals(true, output.isSuccess);
        System.assertEquals([Select Status from Case where id = :testNOSCase.id][0].Status, 'Closed');
    }

    public static testmethod void test_SFDCWS_COOTS_SMR(){
        // create test data
        Account account = new Account();
        account.name = 'foo';
        insert account;

        Contact contact = new Contact();
        contact.LastName = 'Foo';
        contact.AccountId = account.id;
        contact.Title = 'x';
        contact.Phone = '1234567890';
        contact.Email = 'x@x.com';
        insert contact;

        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        insert prop;

        Billing_Account__c billAcc1 = new Billing_Account__c();
        billAcc1.Name = 'TBD';
        billAcc1.Customer__c = account.id;
        billAcc1.Property__c = prop.id;
        billAcc1.Role__c = 'Tenant';
        billAcc1.Status__c = 'Pending';
        billAcc1.HiAF_Account_Number__c = 'dfvtserb';
        insert billAcc1;

        Billing_Account__c billAcc2 = new Billing_Account__c();
        billAcc2.Name = 'TBD';
        billAcc2.Customer__c = account.id;
        billAcc2.Property__c = prop.id;
        billAcc2.Role__c = 'Owner Occupier';
        billAcc2.Status__c = 'Active';
        billAcc2.HiAF_Account_Number__c = 'sdvrysey';
        insert billAcc2;

        Billing_Account__c billAcc4 = new Billing_Account__c();
        billAcc4.Name = 'TBD';
        billAcc4.Customer__c = account.id;
        billAcc4.Property__c = prop.id;
        billAcc4.Role__c = 'Tenant';
        billAcc4.Status__c = 'Active';
        billAcc4.HiAF_Account_Number__c = 'fdhbrny';
        insert billAcc4;

        RecordType smrRt = [Select id from RecordType where Name = 'Special Meter Read' and SobjectType = 'Case'];
        RecordType nosRt = [Select id from RecordType where Name = 'Notice of Sale' and SobjectType = 'Case'];
        Test.startTest();
        SFDCWS_COOTS.COOTSOutput output = SFDCWS_COOTS.completeSMR('Crap');
        System.assertEquals(false, output.isSuccess);
        System.assertEquals('Case number not found',output.outputMessages[0].messageDescription);
        
        Case case1 = new Case(AccountId = account.id, Property__c = prop.id, Billing_Account__c = billAcc1.id,
            Contact_Type__c = 'Crap', Status = 'New', Type_of_Read__c = 'Information Read',Category_Level_3__c = 'Bookings',Category_Level_1__c = 'Billing',Category_Level_2__c = 'Billing');
        insert case1;
        case1 = [Select id, CaseNumber from Case where id = :case1.id];
        output = SFDCWS_COOTS.completeSMR(case1.CaseNumber);
        System.assertEquals(false, output.isSuccess);
        
        Case case2 = new Case(recordTypeId = smrRt.id, AccountId = account.id, Property__c = prop.id, Billing_Account__c = billAcc1.id,
            Contact_Type__c = 'Agent', Status = 'Waiting for HiAffinity', Type_of_Read__c = 'Tenant Move In', Reading_Date__c = Date.newInstance(2050, 1, 3),Category_Level_3__c = 'Bookings',Category_Level_1__c = 'Billing',Category_Level_2__c = 'Billing');
        insert case2;
        case2 = [Select id, CaseNumber from Case where id = :case2.id];
        output = SFDCWS_COOTS.completeSMR(case2.CaseNumber); 
        System.assertEquals(true, output.isSuccess);
        //System.assertEquals(3, output.accountsChanged.size());
        billAcc1 = [Select Status__c, Role__c from Billing_Account__c where id = :billAcc1.id ];
        System.assertEquals('Active', billAcc1.Status__c);
        billAcc2 = [Select Status__c, Role__c from Billing_Account__c where id = :billAcc2.id ];
        System.assertEquals('Active', billAcc2.Status__c);
        System.assertEquals('Landlord', billAcc2.Role__c);
        billAcc4 = [Select Status__c, Role__c from Billing_Account__c where id = :billAcc4.id ];
        System.assertEquals('Closed', billAcc4.Status__c);

        Case case3 = new Case(recordTypeId = smrRt.id, AccountId = account.id, Property__c = prop.id, Billing_Account__c = billAcc1.id,
            Contact_Type__c = 'Agent', Status = 'Waiting for HiAffinity', Type_of_Read__c = 'Tenant Move Out', Reading_Date__c = Date.newInstance(2050, 1, 3),Category_Level_3__c = 'Bookings',Category_Level_1__c = 'Billing',Category_Level_2__c = 'Billing');
        insert case3;
        case3 = [Select id, CaseNumber from Case where id = :case3.id];
        output = SFDCWS_COOTS.completeSMR(case3.CaseNumber);
        System.assertEquals(true, output.isSuccess);
        //System.assertEquals(2, output.accountsChanged.size());
        billAcc1 = [Select Status__c, Role__c from Billing_Account__c where id = :billAcc1.id ];
        System.assertEquals('Closed', billAcc1.Status__c);
        billAcc2 = [Select Status__c, Role__c from Billing_Account__c where id = :billAcc2.id ];
        System.assertEquals('Active', billAcc2.Status__c);
        System.assertEquals('Owner Occupier', billAcc2.Role__c);
        Test.stopTest();
    }

    public static testmethod void test_SFDCWS_COOTS_Apportion(){
        // create test data
        Account account = new Account();
        account.name = 'foo';
        insert account;

        Contact contact = new Contact();
        contact.LastName = 'Foo';
        contact.AccountId = account.id;
        contact.Title = 'x';
        contact.Phone = '1234567890';
        contact.Email = 'x@x.com';
        insert contact;

        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.CIS_Property_Id__c= 'sfgsdgsg';
        prop.Name = 'Test Property';
        insert prop;

        Billing_Account__c billAcc1 = new Billing_Account__c();
        billAcc1.Name = 'TBD';
        billAcc1.Customer__c = account.id;
        billAcc1.Property__c = prop.id;
        billAcc1.Role__c = 'Tenant';
        billAcc1.Status__c = 'Active';
        billAcc1.HiAF_Account_Number__c = 'dfvtserb';
        insert billAcc1;

        Billing_Account__c billAcc2 = new Billing_Account__c();
        billAcc2.Name = 'TBD';
        billAcc2.Customer__c = account.id;
        billAcc2.Role__c = 'Owner Occupier';
        billAcc2.Status__c = 'Active';
        billAcc2.HiAF_Account_Number__c = 'sdvrysey';
        insert billAcc2;
        
        //COOTSOutput output = SFDCWS_COOTS.apportion(String purchaserRole, String hiAfAccNo, String cisPropRef, String source, String moveInType);
        SFDCWS_COOTS.COOTSOutput output = SFDCWS_COOTS.apportion(null, null, null, null, null);
        System.assertEquals(false, output.isSuccess);
        output = SFDCWS_COOTS.apportion(null, null, null, null, 'in');
        System.assertEquals(false, output.isSuccess);
        System.debug('##FOOHERE');
        output = SFDCWS_COOTS.apportion('Tenant', 'dfvtserb', null, 'Test', 'out');
        System.assertEquals(true, output.isSuccess);
        output = SFDCWS_COOTS.apportion('Owner Occupier', 'sdvrysey', 'sfgsdgsg', 'Test', 'in');
        for(SFDCWS_COOTS.OutputMessage msg: output.outputMessages){
            System.debug('**** '+msg.messageDescription);
        }
        System.assertEquals(true, output.isSuccess);
        output = SFDCWS_COOTS.apportion('Tenant', 'dfvtserb', 'sfgsdgsg', 'Test', 'in');
        //System.assertEquals(false, output.isSuccess);
    }
    public static testmethod void test_SFDCWS_COOTS_Other(){
        Case c = SobjectCreator.createCaseInfoStatementUpdate();
        insert c;
        String caseNumber = [Select CaseNumber from Case where id = :c.id][0].CaseNumber;
        SFDCWS_COOTS.CootsOutput output = SFDCWS_COOTS.completeNOS(caseNumber, 'Owner Occupier', true, null, new List<SFDCWS_COOTS.ErrorStatus>());

        SFDCWS_COOTS.ErrorStatus es = new SFDCWS_COOTS.ErrorStatus();

    }
}