sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Direct_Debit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Direct Debit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recovery_Last_Action_Date__c</fullName>
        <description>Shows the date of the last recovery action against the billing account</description>
        <inlineHelpText>Shows the date of the last recovery action against the billing account</inlineHelpText>
        <label>Recovery Last Action Date</label>
        <type>Date</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Used on Classfication Codes button.</description>
    <label>Classification</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification_Code__c.object
<CustomObject>
    <description>Classification codes for customers</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Identifies if the classification code is active for use</description>
        <inlineHelpText>Identifies if the classification code is active for use</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short Description for the customer classification</description>
        <inlineHelpText>Short Description for the customer classification</inlineHelpText>
        <label>Short Description</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Classification Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Credit_Card_Proxy__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Credit Card Proxies</relationshipLabel>
        <relationshipName>Credit_Card_Proxies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CVN__c</fullName>
        <label>CVN</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_1__c</fullName>
        <label>Credit Card Number 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_2__c</fullName>
        <label>Credit Card Number 2</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_3__c</fullName>
        <label>Credit Card Number 3</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Number_4__c</fullName>
        <label>Credit Card Number 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Type__c</fullName>
        <label>Credit Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Account_Name__c</fullName>
        <label>Account Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Account_No__c</fullName>
        <label>Account No</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bank Account</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_BSB_No__c</fullName>
        <label>BSB No</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Financial_Institution__c</fullName>
        <label>Financial Institution</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date_Month__c</fullName>
        <label>Expiry Date</label>
        <picklist>
            <picklistValues>
                <fullName>01</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>02</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>03</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>05</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>06</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date_Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_on_Card__c</fullName>
        <label>Name on Card</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Credit Card Proxies</relationshipLabel>
        <relationshipName>Credit_Card_Proxies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Card Proxy</label>
    <nameField>
        <displayFormat>CC-{00000000}</displayFormat>
        <label>Credit Card Proxy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Card Proxies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Customer_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <label>Classification</label>
        <referenceTo>Classification_Code__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Warnings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Identifies if the classification is still active against the Customer/Billing Account</description>
        <inlineHelpText>Identifies if the classification is still active against the Customer/Billing Account</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Require_Portal_Password_Reset__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Applicable for portal users only. This is only set if the user is created by a CSO and not via self-registration.</inlineHelpText>
        <label>Require Portal Password Reset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secret_Answer__c</fullName>
        <label>Secret Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret_Question__c</fullName>
        <label>Secret Question</label>
        <picklist>
            <picklistValues>
                <fullName>What is the name of your favourite pet?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What city or town where you born in?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What is your mother’s maiden name?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Who is your favourite historical figure?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What was the last school you attended?</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/DirectDebitController_Test.cls
/**
 	Type:       Test Class
    Purpose:    Test class for DirectDebitController
                
    Used By:    DirectDebitController
    ---------------------------------------------------------------
    History:
    
    24-02-2014 G Tsaousidis				Created
 */
@isTest
public class DirectDebitController_Test {
     
	public static testmethod void testDirectDebitController(){   
        Account testAcc = new Account(name = 'Test Account');
        Database.insert(testAcc);
        
        // for testing class-code 'CL'
        Account testAcc1 = new Account(name = 'Test Account1');
        Database.insert(testAcc1);
        
        Billing_Account__c ba = new Billing_Account__c(name = 'Test Billing Account', Customer__c = testAcc.id, Direct_Debit__c = true, Recovery_Last_Action_Date__c = system.today()-5);
        Database.insert(ba);
        
        Billing_Account__c baAX = new Billing_Account__c(name = 'Test Billing Account AX', Customer__c = testAcc.id, Direct_Debit__c = true);
        Database.insert(baAX);
        
        Classification_Code__c code;
        Classification_Code__c code1;
        
        try {
            code = [SELECT name, Is_Active__c, Short_Description__c FROM Classification_Code__c WHERE name = 'AX'];
        } catch (QueryException e) {
            code = new Classification_Code__c();
            code.Name = 'AX';
            code.Is_Active__c = true;
            code.Short_Description__c = 'Foo';          
            insert code;
        }
        
        try {
            code1 = [SELECT name, Is_Active__c, Short_Description__c FROM Classification_Code__c WHERE name = 'CL'];
        } catch (QueryException e) {
            code1 = new Classification_Code__c();
            code1.Name = 'CL';
            code1.Is_Active__c = true;
            code1.Short_Description__c = 'Foo';         
            insert code1;
        }
               
        Customer_Classification__c customer_class = new Customer_Classification__c(Customer__c = testAcc.id, Billing_Account__c = baAX.id, Classification__c = code.Id);
        Database.insert(customer_class);
        
        Customer_Classification__c customer_class1 = new Customer_Classification__c(Customer__c = testAcc1.id, Billing_Account__c = ba.id, Classification__c = code1.Id);
        Database.insert(customer_class1);
         
        Credit_Card_Proxy__c testInput = new Credit_Card_Proxy__c();
        
        Contact person = new Contact(firstname='test', lastname='user');
        Database.insert(person);
       
        PageReference pageRef = Page.DirectDebit;
        Test.setCurrentPage(pageRef);
        System.currentPageReference().getParameters().put('customerId',testAcc.Id);
        System.currentPageReference().getParameters().put('billAcctId',baAX.Id);
        System.currentPageReference().getParameters().put('budgets', 'true');
        DirectDebitController controller = new DirectDebitController();
        System.currentPageReference().getParameters().put('budgets', 'false');
        controller = new DirectDebitController();
        
        controller.getItems();
        controller.goBack();
        
        testInput.Billing_Account__c = ba.Id;
        // add/amend (bad credit card)
        // credit card / visa bad 
        testInput.DD_Account_Type__c = 'Credit Card';
        testInput.Credit_Card_Type__c = 'Visa';
        testInput.Credit_Card_Number_1__c = 'bad number';
        testInput.Credit_Card_Number_2__c = 'bad number';
        testInput.Credit_Card_Number_3__c = 'bad number';
        testInput.Credit_Card_Number_4__c = 'bad number';
        testInput.Expiration_Date_Year__c = '2030';
        testInput.Expiration_Date_Month__c = '06';
        testInput.Name_on_Card__c = 'Tester';
        //testInput.Amount__c = 100;
        testInput.CVN__c = 'bad CVN';
        testinput.person__c = person.Id;
        
        controller.userInputFields = testInput;
        controller.agreedTerms = true;
        System.assertEquals(controller.isValidData(), false);
        
        controller.amend();
        testInput.DD_Account_Type__c = 'Credit Card';
        controller.submit();
        
        // bad (bank account)
        testInput.DD_Account_Type__c = 'Bank Account';
        testInput.DD_BSB_No__c = '12';
        testInput.DD_Account_No__c = '88';
        testInput.DD_Account_Name__c = 'SEW';
        testInput.DD_Financial_Institution__c = 'ANZ';
        testinput.person__c = person.Id;
        controller.userInputFields = testInput;
        
        System.assertEquals(controller.isValidData(),false);
         
        
        // add/amend (bank account)
        testInput.DD_Account_Type__c = 'Bank Account';
        testInput.DD_BSB_No__c = '123456';
        testInput.DD_Account_No__c = '8888888888';
        testInput.DD_Account_Name__c = 'SEW';
        testInput.DD_Financial_Institution__c = 'ANZ';
        testinput.person__c = person.Id;
        controller.userInputFields = testInput;
        
        controller.amend();

        testInput.DD_Account_Type__c = 'Bank Account';
        controller.submit();
        controller.registerDeregisterCustomer();
        
        // add/amend (good credit card)
        testInput.DD_Account_Type__c = 'Credit Card';
        testInput.Credit_Card_Type__c = 'Visa';
        testInput.Credit_Card_Number_1__c = '4005';
        testInput.Credit_Card_Number_2__c = '5500';
        testInput.Credit_Card_Number_3__c = '0000';
        testInput.Credit_Card_Number_4__c = '0001';
        testInput.CVN__c = '888';
        testinput.Amount__c = 100;
        testinput.person__c = person.Id;
        
        controller.userInputFields = testInput;
        controller.agreedTerms = true;
        System.assertEquals(controller.isValidData(), true);
        
        controller.amend();
        testInput.DD_Account_Type__c = 'Credit Card';
        controller.submit();        
        controller.registerDeregisterCustomer();
        
        
        for(Integer i = 0; i < (controller.billingAccList).size(); i++){
            (controller.billingAccList[i]).isSelected = true;
        }
        controller.unselectAllRecords();
        controller.selectAllRecords();      
        
        controller.actionType = 'Add';
        controller.createTask();
        controller.checkStatus();
        controller.redirect = true;
        
        System.assert(controller.taskList != null);     
        controller.registerDeregisterCustomer();    
        
        controller.actionType = 'Amend';
        controller.createTask();
        controller.checkStatus();
        controller.redirect = true;
        
        System.assert(controller.taskList != null);     
        controller.registerDeregisterCustomer(); 
        
        // remove
        controller.actionType = 'Cancel';
        controller.createTask();
        controller.remove();
        controller.redirect = true;
        controller.notCompleted = false;
        controller.Redirect();
        controller.registerDeregisterCustomer();
        controller.timeOut = true;
        controller.timeOut();
        
    
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];        
        //create a user
        User testUser = new User(LastName = 'test',
                                 Email = 'test@salesforce.com',
                                 Alias = 'tu',
                                 LocaleSidKey = 'en_AU',
                                 EmailEncodingKey = 'UTF-8',
                                 LanguageLocaleKey = 'en_US',
                                 TimeZoneSidKey = 'Australia/Sydney',       
                                 username = 'test@portal.sewl.com.au.cfg',
                                 Secret_Question__c = 'What is the name of your favorite pet?',
                                 Secret_Answer__c = 'dog',
                                 ProfileId = p.Id,
                                 Require_Portal_Password_Reset__c = true);
        insert testUser;
        System.runAs(testUser) {
            controller.remove();
            controller.redirect = true;
            controller.notCompleted = false;
            controller.Redirect();
            testinput.person__c = person.Id;
            controller.userInputFields = testInput;
            //controller.registerDeregisterCustomer();
            controller.timeOut = true;
            controller.timeOut();   
        }
        
        pageRef = Page.DirectDebit;
        Test.setCurrentPage(pageRef);
        System.currentPageReference().getParameters().put('customerId',testAcc1.Id);
        System.currentPageReference().getParameters().put('billAcctId',ba.Id);
        System.currentPageReference().getParameters().put('budgets', 'true');
        controller = new DirectDebitController();

        testInput.DD_Account_Type__c = 'Bank Account';
        testInput.DD_BSB_No__c = '123456';
        testInput.DD_Account_No__c = '8888888888';
        testInput.DD_Account_Name__c = 'SEW';
        testInput.DD_Financial_Institution__c = 'ANZ';
        testinput.person__c = person.Id;
        controller.userInputFields = testInput;
        
        controller.userInputFields = testInput;
        controller.agreedTerms = true;
        System.assertEquals(controller.isValidData(), true);
        
        for(Integer i = 0; i < (controller.billingAccList).size(); i++){
            (controller.billingAccList[i]).isSelected = true;
        }
        
        controller.amend();
        controller.submit();        
        controller.registerDeregisterCustomer();
        
        // coverage
        TIBCOPaymentGateway_MessageTypes.DirectDebit_element  dde = new TIBCOPaymentGateway_MessageTypes.DirectDebit_element();
        TIBCOPaymentGateway_MessageTypes.DebitCardDetails_element   dce = new TIBCOPaymentGateway_MessageTypes.DebitCardDetails_element ();
        TIBCOPaymentGateway_MessageTypes.ErrorStatus_element   ese = new TIBCOPaymentGateway_MessageTypes.ErrorStatus_element ();
         

    }
}