sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account_SMR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field has the property filter on and will be displayed only on SMR page.</description>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases (Billing Account)</relationshipLabel>
        <relationshipName>Cases4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Contact Type</description>
        <inlineHelpText>This field contains information that is parsed to BRE for SMR Cases.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Future_Address_Process__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag which is set by time based workflow to check the box when the &apos;Applicable Date&apos; is reached. This will fire a trigger to copy the Future Address to the Billing Account</description>
        <label>Future Address Process</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suspend_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, Billing Account will be suspended.</inlineHelpText>
        <label>Suspend Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_Read__c</fullName>
        <label>Type of Read</label>
        <picklist>
            <controllingField>Contact_Type__c</controllingField>
            <picklistValues>
                <fullName>Tenant Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Reading</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Notice_of_Sale</fullName>
        <active>true</active>
        <businessProcess>Default</businessProcess>
        <description>Case to track Notice of Sale process.</description>
        <label>Notice of Sale</label>
    </recordTypes>
</CustomObject>

sample/retrieveUnpackaged/objects/Non_Residential_Tariff_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Non Residential Tariff Codes</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tariff__c</fullName>
        <label>Tariff</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/CaseInsertTest.cls
/*
 *  Author: ICastillo
 *  Description:Test class for CaseInsert Class
 *  -------------------------------------------------
 *  -------------------------------------------------
 *  HISTORY:
 *  28/08/2012  Created
 *  
 */


public class CaseInsertTest {

    static testMethod void myUnitTest() {
    	// Query the recordtype
    	RecordType recType = [Select name from RecordType where name='Special Meter Read'];
    	//RecordType recType2 = [Select name from RecordType where name='Notice_of_Sale'];
    	
    	// Insert a dummy Non_Residential_Tariff_Codes__c    	
        Non_Residential_Tariff_Codes__c NonRes1 = new Non_Residential_Tariff_Codes__c(name='U03');
        insert NonRes1;
        
        Non_Residential_Tariff_Codes__c NonRes2 = new Non_Residential_Tariff_Codes__c(name='U04');
        insert NonRes2;
        
        Non_Residential_Tariff_Codes__c NonRes3 = new Non_Residential_Tariff_Codes__c(name='U05');
        insert NonRes3;
        
        Non_Residential_Tariff_Codes__c NonRes4 = new Non_Residential_Tariff_Codes__c(name='U06');
        insert NonRes4;
        
        Non_Residential_Tariff_Codes__c NonRes5 = new Non_Residential_Tariff_Codes__c(name='U018');
        insert NonRes5;
        
        Non_Residential_Tariff_Codes__c NonRes7 = new Non_Residential_Tariff_Codes__c(name='U021');
        insert NonRes7;
        
        List<Non_Residential_Tariff_Codes__c> NonResList = [Select name from Non_Residential_Tariff_Codes__c];
        system.debug('@NonResList'+NonResList);
        
        system.debug('@recType'+recType);
        
        // Insert a dummy Property
                
        Property__c prop1 = new Property__c(name='TestProp1');
        insert prop1;
        
        // Insert a dummy Service 
        
        Service__c service1 = new Service__c(name='TestService1', Property__c = prop1.Id, Tariff__c='U03');
        insert service1;
        
        Account acc1 = new Account(name='test Acc');
        insert acc1;
        
        Account acc2 = new Account(name='test Acc2');
        insert acc2;
        
        Billing_Account__c billingAcc1 = new Billing_Account__c(name='test Billing 1', Customer__c = acc1.Id);
        insert billingAcc1;
        
        Billing_Account__c billingAcc2 = new Billing_Account__c(name='test Billing 2', Customer__c =  acc2.Id);
        insert billingAcc2;
        
        
        // Insert a dummy Case that will get an error
        
        Case case1;
        
        try{
        
	        case1 = new Case(Contact_Type__c='Agent', Type_of_Read__c ='Tenant Move In',RecordTypeId=recType.Id, Property__c=prop1.Id );
	        
	        Insert case1;
        }
        catch(exception e){
        	system.debug(e);
        } 
        
        System.assertNotEquals(case1, null);
        
        
        // Insert a dummy Case that will not get an error
        
        Case case2;      
        
       try{
        
	        case2 = new Case(Contact_Type__c='Agent', Type_of_Read__c ='Tenant Move Out',RecordTypeId=recType.Id, Property__c=prop1.Id, Billing_Account_SMR__c = billingAcc1.Id, Billing_Account__c = billingAcc2.Id, Suspend_Billing__c = true, Future_Address_Process__c=true);
	        
	        Insert case2;	        
	       
        }
        catch(exception e){
        	system.debug(e);
        } 
        
        List<Case> caseList = [Select Id from Case where Id =:case2.Id];
        
        System.assertEquals(caseList.size(), 1);
                
      
    }
}