sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Classification_Code__c.object
<CustomObject>
    <description>Classification codes for customers</description>
    <label>Classification Code</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classification Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Customer_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Classifications</relationshipLabel>
        <relationshipName>Customer_Warnings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Classification</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Classifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Financial_Hardship__c.object
<CustomObject>
    <description>Financial Hardship Stream

Represents Financial Hardship information for customers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Signifies that the Financial Hardship Program is Active for the Customer</inlineHelpText>
        <label>Program Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>SCRUM 2013 - Vulnerable Customer Stream</description>
        <inlineHelpText>Represents a Customer under a Financial Hardship program</inlineHelpText>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Hardship</relationshipLabel>
        <relationshipName>Financial_Hardship</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hardship_Status__c</fullName>
        <inlineHelpText>Represents the level of financial hardship status for the related customer</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hardship_Story__c</fullName>
        <inlineHelpText>The initial story for the Financial Hardship Customer.</inlineHelpText>
        <label>Hardship Story</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Review_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Represents the last time the date was reviewed. When record created, default to record create date</description>
        <inlineHelpText>Represents the last time the date was reviewed. For new Financial Hardship applications, default to the created date</inlineHelpText>
        <label>Last Review Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Next_Review_Action__c</fullName>
        <inlineHelpText>TO BE DEFINED</inlineHelpText>
        <label>Next Review Action</label>
        <picklist>
            <picklistValues>
                <fullName>Check URGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Centrepay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Plumbing Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Negotiated Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Water usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send URGS Application</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <defaultValue>TODAY() + 56</defaultValue>
        <inlineHelpText>The next review date. Defaulted to eight weeks from today, however SAO&apos;s can change this (except for setting it to a past date on creation).</inlineHelpText>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nominated_Financial_Hard_Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The nominated Financial Hardship Billing Account</inlineHelpText>
        <label>Nominated Billing Account Number</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Financial Hardship</relationshipLabel>
        <relationshipName>Financial_Hardship</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Hardship</label>
    <nameField>
        <displayFormat>FHA-{000000}</displayFormat>
        <label>Hardship Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Hardship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/FinancialHardshipActionController_Test.cls
/*
    Author: Eugene Jandusay
    Company: Cloud Sherpas 
    Description: (US-489 ) Test class for FinancialHardshipActionController
    History
    01/07/2014 Eugene Jandusay Created

*/
@isTest
private class FinancialHardshipActionController_Test {
public static Account fhCustomer;
public static List<Billing_Account__c> fhBillingAccount;
public static Classification_Code__c fhClass;
public static Customer_Classification__c fhCustomerClass; 
public static Financial_Hardship__c financialHardship;
	
	 //create test data method
	 static testMethod void createTestData() {
	 	
        
		fhCustomer = PortalTestHelper.createResiCustomer();
    	fhBillingAccount = PortalTestHelper.createAccounts(fhCustomer,1);
    	fhClass = PortalTestHelper.createClassificationCode('FH');
    	fhCustomerClass = PortalTestHelper.createCustomerClassificationForBillingAccount(fhCustomer.Id, fhBillingAccount[0].Id, fhClass.id);
		
		financialHardship = new Financial_Hardship__c();
		
		financialHardship.Active__c = true;
		financialHardship.Hardship_Status__c = 'Silver';
		financialHardship.Next_Review_Date__c = date.today();
		financialHardship.Next_Review_Action__c = 'Silver Review';
		financialHardship.Customer__c = fhCustomer.Id;
		financialHardship.Nominated_Financial_Hard_Billing_Account__c = fhBillingAccount[0].Id;
		financialHardship.Hardship_Story__c = 'test';
		
		insert financialHardship;
    	  	
		
		
		//test page and put parameter
		PageReference testPage = Page.FinancialHardshipActionPage;
        testPage.getParameters().put('Id', financialHardship.Id);
        Test.setCurrentPage(testPage);	
	 }


    static testMethod void exitProgramTest() {
        
        //call test data method
        createTestData();
        
        test.startTest();
        
        User intUser = [Select Id from User Where name = 'Integration'];
        
         System.RunAs(intUser){
         	//instantiate Controller
			FinancialHardshipActionController controller = new FinancialHardshipActionController();
			controller.fhAction = 'Exit Program';
			controller.actionOnChange();
			controller.saveFHandTask();
			controller.finishButton();
   	
         }
		
		test.stopTest();
		Task createdTask = [Select Id,WhatId FROM Task where WhatId =:financialHardship.Id];
		system.assertEquals(createdTask.WhatId,financialHardship.Id);
		
		Financial_Hardship__c FH = [Select Id,Active__c FROM Financial_Hardship__c WHERE Id =:financialHardship.Id];
		system.assertEquals(FH.Active__c,false);
    }
    
    static testMethod void changeCaseOfficerTest() {
        
        //call test data method
        createTestData();
        
        test.startTest();
        
        User intUser = [Select Id from User Where name = 'Integration'];
        
         System.RunAs(intUser){
         	//instantiate Controller
			FinancialHardshipActionController controller = new FinancialHardshipActionController();
			controller.fhAction = 'Change FH case Officer';
			controller.actionOnChange();
			controller.saveFHandTask();
			controller.finishButton();
   	
         }
		
		test.stopTest();
		Task createdTask = [Select Id,WhatId FROM Task where WhatId =:financialHardship.Id];
		system.assertEquals(createdTask.WhatId,financialHardship.Id);
    }
    
    static testMethod void checkGoldTest() {
        
        //call test data method
        createTestData();
        
        test.startTest();
        
        User intUser = [Select Id from User Where name = 'Integration'];
        
         System.RunAs(intUser){
         	//instantiate Controller
			FinancialHardshipActionController controller = new FinancialHardshipActionController();
			controller.fhAction = 'Checked Gold';
			controller.actionOnChange();
			controller.taskFHInfoWrapper.financialHardship.Next_Review_Action__c = 'Silver Review';
			controller.taskFHInfoWrapper.financialHardship.Next_Review_Date__c = date.today();
			controller.taskFHInfoWrapper.financialHardship.Last_Review_Date__c = date.today();
			controller.saveFHandTask();
			controller.finishButton();
   	
         }
		
		test.stopTest();
		Task createdTask = [Select Id,WhatId FROM Task where WhatId =:financialHardship.Id];
		system.assertEquals(createdTask.WhatId,financialHardship.Id);
    }
    
    static testMethod void reviewURGSOutcomeTest() {
        
        //call test data method
        createTestData();
        
        test.startTest();
        
        User intUser = [Select Id from User Where name = 'Integration'];
        
         System.RunAs(intUser){
         	//instantiate Controller
			FinancialHardshipActionController controller = new FinancialHardshipActionController();
			controller.fhAction = 'Review URGS Outcome';
			controller.actionOnChange();
			controller.taskFHInfoWrapper.financialHardship.Next_Review_Action__c = 'Silver Review';
			controller.taskFHInfoWrapper.financialHardship.Next_Review_Date__c = date.today();
			controller.taskFHInfoWrapper.financialHardship.Last_Review_Date__c = date.today();
			controller.saveFHandTask();
			controller.finishButton();
   	
         }
		
		test.stopTest();
		Task createdTask = [Select Id,WhatId FROM Task where WhatId =:financialHardship.Id];
		system.assertEquals(createdTask.WhatId,financialHardship.Id);
    }
    
    static testMethod void checkWaterTest() {
        
        //call test data method
        createTestData();
        
        test.startTest();
        
        User intUser = [Select Id from User Where name = 'Integration'];
        
         System.RunAs(intUser){
         	//instantiate Controller
			FinancialHardshipActionController controller = new FinancialHardshipActionController();
			controller.fhAction = 'Checked Water usage';
			controller.actionOnChange();
			controller.taskFHInfoWrapper.financialHardship.Next_Review_Action__c = 'Silver Review';
			controller.taskFHInfoWrapper.financialHardship.Next_Review_Date__c = date.today();
			controller.taskFHInfoWrapper.financialHardship.Last_Review_Date__c = date.today();
			controller.saveFHandTask();
			controller.finishButton();
   	
         }
		
		test.stopTest();
		Task createdTask = [Select Id,WhatId FROM Task where WhatId =:financialHardship.Id];
		system.assertEquals(createdTask.WhatId,financialHardship.Id);
    }
}