sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/PortalSidebarItems__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Pass_Parameters__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Pass Parameters?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_VF_Page__c</fullName>
        <defaultValue>true</defaultValue>
        <label>VF Page?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Label__c</fullName>
        <label>Item Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Link_or_VF_Page__c</fullName>
        <inlineHelpText>either a link or VF Page Name, Without slash in the front and Without Parameters</inlineHelpText>
        <label>Link or VF Page</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Visible_Profiles__c</fullName>
        <inlineHelpText>Comma seperated list
If blank, all profiles visible</inlineHelpText>
        <label>Visible Profiles</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wizard__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This menu item is part of a wizard, hence no redirect will occur</inlineHelpText>
        <label>Wizard?</label>
        <type>Checkbox</type>
    </fields>
    <label>PortalSidebarItems</label>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalSidebarController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalSidebarController
    ---------------------------------------------------------------
    History:

    25-Feb-2014 N Patterson    Created
*/
@isTest
private class PortalSidebarController_Test {

    /* TEST METHOD */
    public static testmethod void test_ToolBarSelectRecord(){
        delete [Select id from PortalSidebarItems__c];
        PortalSidebarItems__c item1 = new PortalSidebarItems__c(Name = 'Test1', Order__c = 10, Is_VF_Page__c = true,
                        Group_Name__c = 'testgroup1', Item_Label__c = 'Test 1', Link_or_VF_Page__c = 'Test1', Is_Pass_Parameters__c = true, 
                        Visible_Profiles__c = 'SEW Portal User', Is_Active__c = true, wizard__c = true);
        insert item1;
        Account a;
        Contact c;
        Id uid = UserInfo.getUserId();
        a = new Account(name = 'TEST ACCOUNT');
        Database.insert(a);
        c = new Contact(AccountId = a.id, lastname = 'lastname');
        Database.insert(c);
        Billing_Account__c bAcct = new Billing_Account__c(Customer__c = a.id, Status__c = 'Active');
        Database.insert(bAcct);
        String testemail = 'puser000@amamama.com';
        Profile p = [select id from profile where name = 'SEW Portal User'];
        User pu = new User(profileId = p.id, username = testemail, email = testemail,
                           emailencodingkey = 'UTF-8', localesidkey = 'en_US',
                           languagelocalekey = 'en_US', timezonesidkey = 'America/Los_Angeles',
                           alias='cspu', lastname='lastname', contactId = c.id);

        Database.insert(pu);
        System.runAs(pu) {
            PortalSidebarController con = new PortalSidebarController();
            con.groupName = 'testgroup1';
            con.currentDevName = 'Test1';
            con.selectedBillAcctId = item1.id;
            System.assertEquals(item1.Name, con.filteredPortalSidebarItemWrappers[0].name);
            System.assertEquals(item1.Name, con.currentChosenItem.name);
            System.assertEquals(item1.Item_Label__c , con.currentChosenItem.label);
            String tempStr = con.currentChosenItem.linkURL;
            List<SelectOption> tempSO = con.billAcctOptions;
            con.peformOperationOnSelectedBillAcct();
            con.selectedPage = 'Test1';
            con.wiznavigate();
        }
    }
}