sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WaterMAP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WaterMAP</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Consumption_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipName>Account_Periodic_Consumption_and_Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Year__c</fullName>
        <label>Financial Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <picklist>
            <picklistValues>
                <fullName>Quarter 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarter 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebilled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Read Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exception Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Water_Volume__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Water Volume (KL)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Consumption and Charge</label>
    <nameField>
        <label>Consumption Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumption and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Key_Business_Activity_Indicator__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Count</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WaterMAP__c</fullName>
        <label>WaterMAP</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>Key Business Activity Indicators</relationshipLabel>
        <relationshipName>Key_Business_Activity_Indicators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Key Business Activity Indicator</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Key Business Activity Indicator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Business Activity Indicators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>Watermap</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <description>The customer who is actually responsible for paying usage charges to SEW</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>WaterMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>KBAI_Description__c</fullName>
        <label>KBAI Description</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KBAI_Type__c</fullName>
        <label>KBAI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP</label>
    <nameField>
        <label>Water MAP #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WaterMAPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP_Submission__c.object
<CustomObject>
    <description>xxxx</description>
    <fields>
        <fullName>Authorised_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Authorised By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WaterMAP Submissions (Authorised By)</relationshipLabel>
        <relationshipName>WaterMAP_Submissions_Authorised_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prepared_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prepared By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions_Preparer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by SEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Watermap__c</fullName>
        <label>Watermap</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <picklist>
            <picklistValues>
                <fullName>2015/16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014/15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013/14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012/13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011/12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010/11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009/10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008/09</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaterMAP Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WaterMAP_Baseline_Usage_Chart_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class WaterMAP_Baseline_Usage_Chart_Controller
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class WaterMAP_Baseline_Usage_Chart_Test {

    private static testmethod void TestMe() {
    // create test data
    Account account = new Account();
    account.name = 'foo';
    insert account;

    Contact contact = new Contact();
    contact.LastName = 'Foo';
    contact.AccountId = account.id;
    contact.Title = 'x';
    contact.Phone = '1234567890';
    contact.Email = 'x@x.com';
    insert contact;

    Property__c prop = new Property__c();
    prop.Universal_Id_c__c = 'sdgfsdgf';
    prop.Name = 'Test Property';
    insert prop;

    Billing_Account__c billAcc = new Billing_Account__c();
    billAcc.Name = 'asetwetwrt';
    billAcc.Customer__c = account.id;
    billAcc.Property__c = prop.id;
    insert billAcc;

    Watermap__c waterMap = new Watermap__c();
    waterMap.Name = 'Test Me';
    waterMap.Customer__c = account.id;
    waterMap.Status__c = 'Not Started';
    waterMap.Billing_Account__c = billAcc.id;
    waterMAP.KBAI_Type__c = 'Average';
    waterMAP.KBAI_Description__c = 'Widget';
    insert waterMap;

    WaterMAP_Submission__c waterMapSub = new WaterMAP_Submission__c();
    waterMapSub.Customer__c = account.id;
    waterMapSub.Prepared_By__c = contact.id;
    waterMapSub.Prepared_By__r = contact;
    waterMapSub.Authorised_By__c = contact.id;
    waterMapSub.Authorised_By__r = contact;
    waterMapSub.Status__c = 'Not Started';
    waterMapSub.Watermap__c = waterMap.id;
    waterMapSub.Watermap__r = waterMap;
    waterMapSub.Year__c = '2011/12';
    insert waterMapSub;

    Consumption_and_Charge__c charge = new Consumption_and_Charge__c();
    charge.Water_Volume__c = 1000;
    charge.Billing_Account__c = billAcc.id;
    charge.Financial_Year__c = '2010/11';
    charge.Name = 'Jan-Mar 2010/11';
    insert charge;

    charge = new Consumption_and_Charge__c();
    charge.Water_Volume__c = 2000;
    charge.Billing_Account__c = billAcc.id;
    charge.Financial_Year__c = '2010/11';
    charge.Name = 'Apr-Jun 2010/11';
    insert charge;

    charge = new Consumption_and_Charge__c();
    charge.Water_Volume__c = 3000;
    charge.Billing_Account__c = billAcc.id;
    charge.Financial_Year__c = '2010/11';
    charge.Name = 'Jul-Sep 2010/11';
    insert charge;

    charge = new Consumption_and_Charge__c();
    charge.Water_Volume__c = 4000;
    charge.Billing_Account__c = billAcc.id;
    charge.Financial_Year__c = '2010/11';
    charge.Name = 'Oct-Dec 2010/11';
    insert charge;

    charge = new Consumption_and_Charge__c();
    charge.Water_Volume__c = 1000;
    charge.Billing_Account__c = billAcc.id;
    charge.Financial_Year__c = '2009/10';
    charge.Name = 'Oct-Dec 2009/10';
    insert charge;

    List <Key_Business_Activity_Indicator__c> Baselines = new List<Key_Business_Activity_Indicator__c>();

    Key_Business_Activity_Indicator__c Baseline = new Key_Business_Activity_Indicator__c();
    Baseline.WaterMAP__c = waterMap.id;
    Baseline.Count__c = 100;
    Baseline.Period__c = 'Jan-Mar 2010/11';
    Baseline.Year__c = '2010/11';
    insert Baseline;
    Baselines.add(Baseline);

    Baseline = new Key_Business_Activity_Indicator__c();
    Baseline.WaterMAP__c = waterMap.id;
    Baseline.Count__c = 200;
    Baseline.Period__c = 'Apr-Jun 2010/11';
    Baseline.Year__c = '2010/11';
    insert Baseline;
    Baselines.add(Baseline);

    Baseline = new Key_Business_Activity_Indicator__c();
    Baseline.WaterMAP__c = waterMap.id;
    Baseline.Count__c = 300;
    Baseline.Period__c = 'Jul-Sep 2010/11';
    Baseline.Year__c = '2010/11';
    insert Baseline;
    Baselines.add(Baseline);

    Baseline = new Key_Business_Activity_Indicator__c();
    Baseline.WaterMAP__c = waterMap.id;
    Baseline.Count__c = 400;
    Baseline.Period__c = 'Oct-Dec 2010/11';
    Baseline.Year__c = '2010/11';
    insert Baseline;
    Baselines.add(Baseline);

    Baseline = new Key_Business_Activity_Indicator__c();
    Baseline.WaterMAP__c = waterMap.id;
    Baseline.Count__c = 400;
    Baseline.Period__c = 'Oct-Dec 2009/10';
    Baseline.Year__c = '2009/10';
    insert Baseline;
    Baselines.add(Baseline);


    WaterMAP_Baseline_Usage_Chart_Controller controller = new WaterMAP_Baseline_Usage_Chart_Controller();

    controller.wmapSub = waterMapSub;
    System.assertEquals('2010/11', controller.recentYear);
    System.assertEquals(2, controller.noOfYearsToDisplayForBaseline);
    System.assertEquals(controller.orderedBaselineLines.size(), 5);
    String url =controller.googleChartURL;
    controller.NoOp();

    controller.wmapsub.WaterMAP__r.KBAI_Type__c = 'Sum';



  }
}