sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Billing_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Account</label>
        <referenceTo>Billing_Account__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>Contact Type</description>
        <inlineHelpText>This field contains information that is parsed to BRE for SMR Cases.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solicitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchaser</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B/O Sale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IS_Calc_Trade_Waste_Vol_Amount__c</fullName>
        <label>Calculated Trade Waste Volumetric Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IS_Company_Trading_On_Or_After_Settlemen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Company trading on or after settlemen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IS_Date_Of_Settlement__c</fullName>
        <label>Date of Settlement</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IS_Legal_Costs__c</fullName>
        <description>Information Statement Update field</description>
        <label>Legal Costs</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IS_Prod_Ceasing_Earlier_Than_Settle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is production ceasing before settlement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IS_Special_Read_Arranged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Special read arranged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IS_What_Date_Are_They_Ceasing__c</fullName>
        <label>What date are they ceasing?</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/CaseInfoStatementFields_Ext_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class CaseInfoStatementFields_Ext
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class CaseInfoStatementFields_Ext_Test {

    public static testMethod void testCaseInfoStatementFields_Ext() {
		RecordType recType = [Select name from RecordType where name='Information Statement Update'];
		
		Property__c prop1 = new Property__c(name='TestProp1');
		insert prop1;
        
        Account acc1 = new Account(name='test Acc');
        insert acc1;
        
        Billing_Account__c billingAcc1 = new Billing_Account__c(name='test Billing 1', Customer__c = acc1.Id);
        insert billingAcc1;
        // Insert a dummy Case that will get an error
        
        Case case1;
        
        try{
        
	        case1 = new Case(Contact_Type__c='Agent',RecordTypeId=recType.Id, Property__c=prop1.Id, IS_Legal_Costs__c=1234 );
	        
	        Insert case1;
        }
        catch(exception e){
        	system.debug(e);
        } 
        
        
        		
		
		
		Test.startTest();
		
		ApexPages.StandardController controller = new ApexPages.StandardController(case1);
		
		CaseInfoStatementFields_Ext ccccc = new CaseInfoStatementFields_Ext(controller);
		System.assertEquals(ccccc.legalCostValue.IS_Legal_Costs__c, case1.IS_Legal_Costs__c);
		ccccc.legalCostValue.IS_Legal_Costs__c = 4321;
		ccccc.saveLegalCost();

		ccccc.calcTradeWasteValue = '153';
		ccccc.legalCostValue.IS_Special_Read_Arranged__c = true;
		ccccc.legalCostValue.IS_What_Date_Are_They_Ceasing__c = Date.today();
		ccccc.legalCostValue.IS_Prod_Ceasing_Earlier_Than_Settle__c = true;
		ccccc.legalCostValue.IS_Company_Trading_On_Or_After_Settlemen__c = true;
		ccccc.legalCostValue.IS_Date_Of_Settlement__c = Date.today();
		ccccc.saveVolumetric();
		
		Case checkUpdated = [SELECT id, IS_Legal_Costs__c, IS_Calc_Trade_Waste_Vol_Amount__c, IS_Special_Read_Arranged__c, IS_What_Date_Are_They_Ceasing__c, IS_Prod_Ceasing_Earlier_Than_Settle__c,
								IS_Company_Trading_On_Or_After_Settlemen__c, IS_Date_Of_Settlement__c
							 FROM case Where Id = :case1.id];
		System.assertEquals(checkUpdated.IS_Legal_Costs__c, 4321);
		System.assertEquals(checkUpdated.IS_Calc_Trade_Waste_Vol_Amount__c, 153);
		System.assertEquals(checkUpdated.IS_Special_Read_Arranged__c, true);
		System.assertEquals(checkUpdated.IS_What_Date_Are_They_Ceasing__c, Date.today());
		System.assertEquals(checkUpdated.IS_Prod_Ceasing_Earlier_Than_Settle__c, true);
		System.assertEquals(checkUpdated.IS_Company_Trading_On_Or_After_Settlemen__c, true);
		System.assertEquals(checkUpdated.IS_Date_Of_Settlement__c, Date.today());
		
		ccccc.calcTradeWasteValue = '';
		ccccc.saveVolumetric();
		
		checkUpdated = [SELECT id, IS_Legal_Costs__c, IS_Calc_Trade_Waste_Vol_Amount__c, IS_Special_Read_Arranged__c, IS_What_Date_Are_They_Ceasing__c, IS_Prod_Ceasing_Earlier_Than_Settle__c,
								IS_Company_Trading_On_Or_After_Settlemen__c, IS_Date_Of_Settlement__c
							 FROM case Where Id = :case1.id];
		
		System.assertEquals(checkUpdated.IS_Calc_Trade_Waste_Vol_Amount__c, null);
		
		Test.stopTest(); 
	}
}