sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <formula>Customer__r.Id</formula>
        <label>Customer Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HiAF_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>HiAF Account #</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landlord</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Body Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad-Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/BillingAccountRelatedExCon.cls
/*
    Name:		BillingAccountRelatedExCon
    Type:       Controller Extension
    Purpose:    Primary purpose is for the Mercantile Recovery 
    			Billing	Account page layout - Other Related 
    			Billing Accounts list view
    Used By:    BillView
    Business
    Requirement
    Reference:	TT10680 - Test Track
    ----------------------------------------------------------------------
    History:

    29-Aug-2013 G.Tsaousidis 	(SEW)			Created
    30-Aug-2013	G.Tsaousidis	(SEW)			Adding Pagination support
*/

public with sharing class BillingAccountRelatedExCon {
	
	// Pagination Variables
	private integer totalRecords = 0;     
    private integer index = 0;
    private integer pageSize = 5;   
	
	// Lists for data control
	private Billing_Account__c bacBillingAccountRelated;
	private Billing_Account__c relatedCustomerId;
	
	// Standard Set Controller for pagination
	public ApexPages.StandardSetController sscRelatedBillingAccounts{get; set;}
	
	public BillingAccountRelatedExCon(ApexPages.StandardController stdController){
		bacBillingAccountRelated = (Billing_Account__c)stdController.getRecord();
		System.debug('::bacBillingAccountRelated:: '+ bacBillingAccountRelated);
		relatedCustomerId = [SELECT Customer_id__c 
							 FROM billing_account__c
							 WHERE id = :bacBillingAccountRelated.id];
		handleRelatedBillingAccounts();
	}
	
	
	public List<Billing_Account__c> getRelatedBillingAccounts(){
		if(sscRelatedBillingAccounts != null){
			return (List<Billing_Account__c>)sscRelatedBillingAccounts.getRecords();
		}
		else
			return null;
	}
	
	public PageReference handleRelatedBillingAccounts(){
		
		/*List<Billing_Account__c> lstBillingAccounts = 
									[SELECT 
											HiAf_Account_Number__c,
											Status__c,
											Property__r.name,
											Balance__c,
											Role__c,
											Customer_id__c
									FROM
											Billing_Account__c
									WHERE
											Customer__r.id = :relatedCustomerId.Customer_id__c
										AND id != :bacBillingAccountRelated.id
											];*/
											
		
		
		Database.QueryLocator dqlRelatedBillingAccounts = Database.getQueryLocator(
									[SELECT 
											HiAf_Account_Number__c,
											Status__c,
											Property__r.name,
											Balance__c,
											Role__c,
											Customer_id__c
									FROM
											Billing_Account__c
									WHERE
											Customer__r.id = :relatedCustomerId.Customer_id__c
										AND id != :bacBillingAccountRelated.id
											]);
											
		sscRelatedBillingAccounts = new ApexPages.Standardsetcontroller(dqlRelatedBillingAccounts);
		sscRelatedBillingAccounts.setPageSize(pageSize);
		return null;					
		
	}
	
	
	/* Pagination Methods */
	public Boolean hasNext{
		get{
			return sscRelatedBillingAccounts.getHasNext();
		}
		set;
	}
	
	public Boolean hasPrevious{
		get{
			return sscRelatedBillingAccounts.getHasPrevious();
		}
		set;
	}
	
	public void previous(){
		sscRelatedBillingAccounts.previous();
	}
	
	public void next(){
		sscRelatedBillingAccounts.next();
	}
	
	public void lastPage(){
		sscRelatedBillingAccounts.last();
	}
	
	public void firstPage(){
		sscRelatedBillingAccounts.first();
	}
	
	public Integer pageNumber{
		get{
			return sscRelatedBillingAccounts.getPageNumber();
		}
		set;
	}
	
}