sample/retrieveUnpackaged/objects/Billing_Account__c.object
<CustomObject>
    <description>This object links Customers will Properties and provides billing information.</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>Billing_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Account</label>
    <nameField>
        <label>Billing Account #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Meter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Digital Meter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/PortalPageCategory__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Stores Knowledge base page name and category</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PortalPageCategory</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Digital_Meter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag field that determines if a property belongs to digital meter trial.</description>
        <label>Digital Meter</label>
        <type>Checkbox</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalKB_CategoryController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class PortalEnquiriesMyCases_Controller
    ---------------------------------------------------------------
    History:

    26-Feb-2014 G.Tsaousidis					Created
    02-Apr-2014	ejandusay(Cloud Sherpas)		Updated with checking for digital meter user
    
*/
@isTest(seeAllData = true)
private class PortalKB_CategoryController_Test {

	public static TestMethod void portalKB_CategoryTest(){
		PageReference pageRef = Page.portalmyaccounthomepage;
    	Test.setCurrentPageReference(pageRef);
		PortalPageCategory__c cs = new PortalPageCategory__c();
		cs.name = 'portalmyaccounthomepage2';
		cs.Category__c = 'sew:home';
		insert cs;
		
		// Create Test Portal User
        Profile profVar = [Select Id from Profile where name='SEW Portal User'];
        Account testAccount = new Account(name='test account');
        insert testAccount;
        Contact testContact = new Contact(LastName='north', AccountId = testAccount.Id);
        insert testContact;
        User usrVar  = new User(ContactId=testContact.Id, ProfileId=profVar.Id, alias = 'hasrole', email='userwithrole@roletest1.com', 
	                            emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US', 
	                            localesidkey='en_US',timezonesidkey='America/Los_Angeles', username='userwithrole@testorg.com');
		
		// Create Test Property , Meter and Billing Account
	    Property__c propertyVar = new Property__c(Digital_Meter__c=true);
		insert propertyVar;
		Meter_Details__c mdVar = new Meter_Details__c(name='m2test',Property__c = propertyVar.Id,Digital_Meter__c=true);
		insert mdVar;
	    Billing_Account__c billAcc = new Billing_Account__c(Customer__c = testAccount.Id,Property__c = propertyVar.Id);
		insert billAcc;
		
		system.runAs(usrVar){
			test.startTest();
			PortalKB_CategoryController con = new PortalKB_CategoryController();
			String name = con.makePageName('apex/testPage');
			System.assertEquals(name, 'testpage');
			System.assertEquals(con.dataCategory, 'Categories:All');
			test.stopTest();
		}
		
	}
	
	
}