sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category_Level_1__c</fullName>
        <inlineHelpText>What is the case or activity about?</inlineHelpText>
        <label>What</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Account Payments &amp; Collections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plumbing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claims</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Knowledge sharing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Policy Reform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal Registration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_2__c</fullName>
        <inlineHelpText>Why is the case or activity occurring?</inlineHelpText>
        <label>Why</label>
        <picklist>
            <controllingField>Category_Level_1__c</controllingField>
            <picklistValues>
                <fullName>Account/Access</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaigns &amp; Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Recovery Action</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Did Not Receive Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficiency Programs &amp; Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Give Explanation of Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot Issues - Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect Charges</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Information Statement Update</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meter Readings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move In / Move Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Customer/Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Update Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Off/On</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water Restrictions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Water</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Injury</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tappings/Pluggings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Level_3__c</fullName>
        <inlineHelpText>The solution, the response, the process - the case creation</inlineHelpText>
        <label>How</label>
        <picklist>
            <controllingField>Category_Level_2__c</controllingField>
            <picklistValues>
                <fullName>Acceptance of Works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access to Meter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Balance/Due Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Password</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Add/Amend Concession Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Hoc Billing Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Direct Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Meter Reading</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amend Property Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Backlog Sewer Charges Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Debt Recommendation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balance Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy and  Liquidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Adjustment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bookings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Build overs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Opt In/Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caveat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Occupier Explained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check for Tampering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Claim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consent to connect Water or Sewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Classifaction Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Read Taken</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/NewCaseRedirectExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class AccountMassBAcctAddressFlagUpdateExCon
    ---------------------------------------------------------------
    History:

    24-Feb-2014 G Tsaousidis  Created
*/

@isTest
private class NewCaseRedirectExCon_Test {

	public static testmethod void test_NewCaseRedirectExCon(){ 
        PageReference pageRef = new PageReference('/'+Case.SObjectType.getDescribe().getKeyPrefix()+'/e');
        pageRef.getParameters().put('retURL', 'XXX');
        pageRef.getParameters().put('RecordType', 'YYY');
        pageRef.getParameters().put('ent', 'ZZZ');
        Test.setCurrentPage(pageRef);
        NewCaseRedirectExCon exCon = new NewCaseRedirectExCon(new ApexPages.StandardController(new Case()));
        PageReference testPageRef = exCon.redirectToNewCaseWithNewParameters();
        System.assertEquals(true, testPageRef.getParameters().containsKey('nooverride'));
        System.assertEquals(true, testPageRef.getParameters().containsKey('cas5'));
    }

    public static testmethod void test_NewCaseRedirectExCon2(){ 
        PageReference pageRef = new PageReference('/'+Case.SObjectType.getDescribe().getKeyPrefix()+'/e');
        pageRef.getParameters().put('retURL', 'XXX');
        pageRef.getParameters().put('RecordType', 'YYY');
        pageRef.getParameters().put('ent', 'ZZZ');
        Test.setCurrentPage(pageRef);
        Case cs = new Case();
        cs.Category_Level_3__c = 'Bookings';
		cs.Category_Level_1__c = 'Billing';
		cs.Category_Level_2__c = 'Billing';
        insert cs;
        NewCaseRedirectExCon exCon = new NewCaseRedirectExCon(new ApexPages.StandardController(cs));
        exCon.redirectToEditCase();
    }
}