sample/retrieveUnpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Portal_Case_Type__c</fullName>
        <description>convert how and record type to Portal meaningful description</description>
        <formula>CASE( Category_Level_3__c, 
   &apos;Update Name&apos;, &apos;Name change request&apos;,
   &apos;Time to Pay Extension&apos;, &apos;More time to pay&apos;,
   &apos;Add/Amend Concession Details&apos;, &apos;Register concession&apos;,
   &apos;Delete Concession&apos;, &apos;Delete concession&apos;,
   &apos;Customer Read&apos;, &apos;Customer meter read&apos;,
   &apos;Portal Password&apos;, &apos;Registration enquiry&apos;,
   &apos;Special Read&apos;, &apos;Move in/out&apos;,
   &apos;Merge Customers&apos;, &apos;Add an account&apos;,
    $RecordType.Name )</formula>
        <label>Portal Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Resolved_By_Article__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates that the case was closed after viewing the portal article</inlineHelpText>
        <label>Resolved By Article in Portal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>The first 255 characters of the full description will be automatically copied here.</description>
        <inlineHelpText>If blank , the first 255 characters of the full description will be automatically copied here.</inlineHelpText>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>HIDDEN_Confirmed_Portal_User__c</fullName>
        <defaultValue>false</defaultValue>
        <label>(Hidden) Confirmed Portal User</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/PortalEnquiriesMyCases_Controller.cls
public with sharing class PortalEnquiriesMyCases_Controller extends PortalPageWithAccounts_Virtual_Con {
	
/*
    Type:       Controller class
    Purpose:    Portal Enquiries - 'View My Cases' 			

    Used By:    PortalEnquiriesMyCases.page
    ---------------------------------------------------------------
    History:

    19-Mar-2012 M.Watson (Salesforce)    Created
    29-Oct-2013 N.Patterson				TT10401 - Allow for multiple customers/users linked
    26-Feb-2014 G.Tsaousidis			Technical Debt: Moved Test Methods to Test Classes
*/	

    /* PUBLIC PROPERTIES */
 	public List<Case> allOpenCases {
 		get { 
 			//TT10401
 			allOpenCases = PortalUtil.getMyCases(userContact.Id, 'open');
 			/*allOpenCases = [select Id, Portal_Case_Type__c, CreatedDate, Status, Subject, Description, Short_Description__c, CaseNumber, RecordType.Name
						from Case
						where CreatedBy.Id = :UserInfo.getUserId()
						and Origin = 'Portal'
						and Status != 'New'
						and Status != 'Error'
						and isClosed != true
						order by CaseNumber desc]; */
			return allOpenCases;
 		}
 		private set;
 	}  

 	public List<Case> allClosedCases {
 		get { 
 			//TT10401
 			allClosedCases = PortalUtil.getMyCases(userContact.Id, 'closed');
 			/*allClosedCases = [select Id, Portal_Case_Type__c, CreatedDate, Status, Subject, Description, Short_Description__c, CaseNumber, RecordType.Name
						from Case
						where CreatedBy.Id = :UserInfo.getUserId()
						and Origin = 'Portal'
						and Status != 'Cancelled'
						and isClosed = true
						and Portal_Resolved_By_Article__c = false
						order by CaseNumber desc]; */
			return allClosedCases;
 		}
 		private set;
 	}  

	public String caseToggle {get; set;} {caseToggle='open';}
	
	/* Checking of User confirmation */
	public User curUser {get;set;}

	// Check that the user is not a confirmed portal user
	/*public PageReference CheckRedirectConfirmed() {
		curUser = [Select Id, HIDDEN_Confirmed_Portal_User__c from User where Id =: UserInfo.getUserId()];
		if (curUser.HIDDEN_Confirmed_Portal_User__c != true) { 
			return Page.PortalUserConfirmation.setRedirect(true);		
		}
		return null;
	}*/

	/* CONSTRUCTOR */
	public PortalEnquiriesMyCases_Controller() {
		super();
	}

	
}