sample/retrieveUnpackaged/objects/Consumption_and_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Year__c</fullName>
        <label>Financial Year</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Current_Year__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Set by workflow and unset by batch apex</description>
        <label>Is Current Year</label>
        <type>Checkbox</type>
    </fields>
    <label>Consumption and Charge</label>
    <nameField>
        <label>Consumption Period</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consumption and Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Reports__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Custom setting for reports</description>
    <fields>
        <fullName>Year__c</fullName>
        <inlineHelpText>YYYY/YY format e.g. 2008/09</inlineHelpText>
        <label>Year</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reports</label>
</CustomObject>

sample/retrieveUnpackaged/objects/SystemSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Financial_Year__c</fullName>
        <label>Financial Year</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>SystemSettings</label>
</CustomObject>

sample/retrieveUnpackaged/classes/ConsumptionSetCurrentYrFlagBatch.cls
global class ConsumptionSetCurrentYrFlagBatch implements Database.Batchable<sObject> {

/*
    Type:       Batch class
    Purpose:    Updates the current year flag on consumption based
                the Reports__c.year__c custom setting

    Used By:
    ---------------------------------------------------------------
    History:

    08-Aug-2011 D.Thong (Salesforce)    Created
    24-Feb-2014 ejandusay (Cloud Sherpas)	Moved test methods in a separate test class

*/

    public String year;

    global database.querylocator start(Database.BatchableContext BC) {

        if (year == null)
            if (SystemSettings__c.getInstance() != null)
                year = SystemSettings__c.getInstance().financial_year__c; // current fin year
            else
                year = '2010/11';

        String query = 'Select c.Is_Current_Year__c, c.Financial_Year__c From Consumption_and_Charge__c c ';
        query +=        'where (financial_year__c = \'' + year + '\' and is_current_year__c = false) or ';
        query +=        '(financial_year__c != \'' + year + '\' and is_current_year__c = true)';

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List <Consumption_and_Charge__c> cons = new List<Consumption_and_Charge__c>();
        for (sObject s : scope) {
            Consumption_and_Charge__c c = (Consumption_and_Charge__c ) s;
            if (c.financial_year__c != year && c.is_current_year__c)
                // flag set but should not be
                c.is_current_year__c = false;
            else
                c.is_current_year__c = true;

            cons.add(c);
        }

        update cons;
    }

    global void finish(Database.BatchableContext BC){

    }

}