sample/retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Most_Recent_DD_Start_Date__c</fullName>
        <description>Captures the latest Direct Debit Commencement Date</description>
        <label>Most Recent DD Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_of_Days_Since_Sign_up_for_Ebill__c</fullName>
        <description>Indicates the number of days since the last billing account eBilling was set to Email.  If the date is empty/NULL (i.e. they don’t have any accounts with eBill Method of Email), then the value is set to -1.</description>
        <formula>if(ISNULL(Account.Most_Recent_Ebill_Email_Date__c), -1, TODAY()-Account.Most_Recent_Ebill_Email_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Days Since Sign up for Ebill</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Predictive_Trigger_Field__c</fullName>
        <description>Need a field to trigger a field update so that Predictive Campaign Flow picks up the user.</description>
        <label>Predictive Trigger Field</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/PredictiveCampaignFlowEDM03Scheduler.cls
/*
    Type:       Class Scheduler
    Purpose:    class that will be used to call the batch job PredictiveCampaignFlowBatch

    Used By:    Scheduler for EDM03 campaign
    ---------------------------------------------------------------
    History:

    29/01/2014 N Patterson      Created    
  
*/
global class PredictiveCampaignFlowEDM03Scheduler implements Schedulable{
    global void execute(SchedulableContext SC) {    
        // Initialize the PredictiveCampaignFlowBatch class
        PredictiveCampaignFlowBatch pred = new PredictiveCampaignFlowBatch();
        
        // Setup the query
        String query = 'SELECT Id, Predictive_Trigger_Field__c, Most_Recent_DD_Start_Date__c FROM Contact ';
            query += 'Where Most_Recent_DD_Start_Date__c = NULL ';
            query += 'AND (Number_of_Days_Since_Sign_up_for_Ebill__c <= 1 AND Number_of_Days_Since_Sign_up_for_Ebill__c >= 0)';
            query += 'AND HAsOptedOutOfEmail = False';
        pred.query = query;
        pred.campaignName = 'EDM03 - Paperless Billing and NOT DD';
        
        // call and execute the batch job
        ID batchprocessid = Database.executeBatch(pred,200);   
    }
}