sample/retrieveUnpackaged/objects/EncryptedKey__c.object
<CustomObject>
    <description>EncryptedKey table stores the Encrypted Key Type and Key Value</description>
    <fields>
        <fullName>Key1__c</fullName>
        <label>Key1</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key2__c</fullName>
        <label>Key2</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key3__c</fullName>
        <label>Key3</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key4__c</fullName>
        <label>Key4</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key5__c</fullName>
        <label>Key5</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key6__c</fullName>
        <label>Key6</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>EncryptedKey</label>
    <nameField>
        <label>EncryptedKey Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EncryptedKeys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/EncryptionKey.cls
/*
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Update:	Moved test method in a separate test class
*/
public without sharing class EncryptionKey {

    public static String getKey(String keyType) {
        try {
            EncryptedKey__c key = [select key1__c, key2__c, key3__c, key4__c, key5__c, key6__c from EncryptedKey__c 
                                    where name = :keyType LIMIT 1];
            
            if (key != null) {
                String keyValue = key.key1__c;
                if (key.key2__c != null)
                    keyValue += key.key2__c;
                if (key.key3__c != null)
                    keyValue += key.key3__c;
                if (key.key4__c != null)
                    keyValue += key.key4__c;
                if (key.key5__c != null)
                    keyValue += key.key5__c;
                if (key.key6__c != null)
                    keyValue += key.key6__c;
                return keyValue;
            }


            return null;        
                                     
        } catch (QueryException e) {
            return null;
        }       
    }
    
    
}