sample/retrieveUnpackaged/objects/EncryptedKey__c.object
<CustomObject>
    <description>EncryptedKey table stores the Encrypted Key Type and Key Value</description>
    <fields>
        <fullName>Key1__c</fullName>
        <label>Key1</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key2__c</fullName>
        <label>Key2</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key3__c</fullName>
        <label>Key3</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key4__c</fullName>
        <label>Key4</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key5__c</fullName>
        <label>Key5</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Key6__c</fullName>
        <label>Key6</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>EncryptedKey</label>
    <nameField>
        <label>EncryptedKey Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EncryptedKeys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/EncryptionKey_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class EncryptionKey
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class EncryptionKey_Test {

    public static testmethod void TestMe() {
        EncryptedKey__c key = new EncryptedKey__c();
        key.Name = 'TESTING123';
        key.Key1__c = 'ABC';
        key.Key2__c = 'DEF';
        key.Key3__c = 'GHI';
        key.Key4__c = 'JKL';
        key.Key5__c = 'MNO';
        key.Key6__c = 'PQR';
        insert key;
        System.assertEquals(EncryptionKey.getKey('TESTING123'), 'ABCDEFGHIJKLMNOPQR');
    }
}