sample/retrieveUnpackaged/objects/Event_Action__c.object
<CustomObject>
    <fields>
        <fullName>Alternative_Water_Supply__c</fullName>
        <label>Alternative Water Supply</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Public_Type__c</fullName>
        <label>Public Type</label>
        <picklist>
            <picklistValues>
                <fullName>Emergency works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled works</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publish_status__c</fullName>
        <label>Publish status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Rich_Text_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SEW_Event__c</fullName>
        <label>SEW Event</label>
        <referenceTo>SEW_Event__c</referenceTo>
        <relationshipLabel>Event Actions</relationshipLabel>
        <relationshipName>Event_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Action</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Event Action Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Actions</pluralLabel>
    <recordTypes>
        <fullName>Internet</fullName>
        <active>true</active>
        <label>Internet</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Event_Affected_Property__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Event Affected Properties</relationshipLabel>
        <relationshipName>Event_Affected_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SEW_Event__c</fullName>
        <label>SEW Event</label>
        <referenceTo>SEW_Event__c</referenceTo>
        <relationshipName>Affected_Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Affected Property</label>
    <nameField>
        <displayFormat>AP-{000000}</displayFormat>
        <label>Affected Properties Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Affected Properties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Event_Type_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This custom object describes the settings for each event type including the colours and images to be displayed on the mapping page</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Colour__c</fullName>
        <defaultValue>&quot;BBBBBB&quot;</defaultValue>
        <description>RGB code for the Event colour</description>
        <label>Event Colour</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon_Static_Resource_Name__c</fullName>
        <description>The name of the icon static resource for the event</description>
        <label>Icon Static Resource Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Name__c</fullName>
        <label>Public Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_Icon_Static_Resource__c</fullName>
        <description>The link to the resolved icon</description>
        <label>Resolved Icon Static Resource</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Event Type Settings</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Suburb__c</fullName>
        <label>Suburb</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/SEW_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Status__c</fullName>
        <label>Public status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Source_system_status__c</fullName>
        <label>Source system status</label>
        <picklist>
            <picklistValues>
                <fullName>Not started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Transit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working elsewhere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status_Timestamp__c</fullName>
        <label>Status Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SEW Event</label>
    <nameField>
        <label>Event Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/SystemSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Map_location_search_distance__c</fullName>
        <inlineHelpText>Specifiies the search distance(in KM) within the location filter criteria for the map</inlineHelpText>
        <label>Map location search distance</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>SystemSettings</label>
</CustomObject>

sample/retrieveUnpackaged/classes/SEWEventsLocationControllerTest.cls
/*
    Author: Eugene Jandusay
    Company: Cloud Sherpas 
    Description: Test class for SEWEventsLocationController
    History
    15/04/2014 Eugene Jandusay Created

*/
@isTest
private class SEWEventsLocationControllerTest {

public static SEW_Event__c tempEvent;
public static Property__c tempProperty;
public static Event_Affected_Property__c tempEAA;
public static Event_Action__c tempEAction;


    //void method to create test data
    static testMethod void createTestData() {
        //create event
        tempEvent = new SEW_Event__c();
        tempEvent.Event_Type__c = 'Emergency works';
        tempEvent.Street_Number__c = '20';
        tempEvent.Street_Name__c = 'Corporate';
        tempEvent.Street_Type__c = 'Drive';
        tempEvent.City__c = 'Heatherton';
        //tempEvent.Planned_Start_Time__c = dateTime.now();
        //tempEvent.Planned_End_Time__c = dateTime.now().addHours(6);
        tempEvent.Source_system_status__c = 'In Progress';
        tempEvent.Public_Status__c = 'In Progress';
        tempEvent.Coordinates__latitude__s = -37.4578;
        tempEvent.Coordinates__longitude__s = 145.4578;
        tempEvent.Status_Timestamp__c = dateTime.now();

        insert tempEvent;

        //create property
        tempProperty = new Property__c();
        tempProperty.Street_Address__c = '20 Corporate Drive';
        tempProperty.Suburb__c = 'Heatherton';
        tempProperty.Name = 'Test';

        insert tempProperty;

        //create event affected area
        tempEAA = new Event_Affected_Property__c();
        tempEAA.Property__c = tempProperty.Id;
        tempEAA.SEW_Event__c = tempEvent.Id;
        
        insert tempEAA;
        
        //create event action
        RecordType rt = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'Event_Action__c' AND Name = 'Internet' LIMIT 1];
        tempEAction = new Event_Action__c();
		tempEAction.Alternative_Water_Supply__c = 'Test';
        tempEAction.RecordTypeId = rt.id;
        tempEAction.Rich_Text_Message__c = 'This is message\nNewLine';
        tempEAction.Public_Type__c = 'Scheduled works';
        tempEAction.Resolution__c = 'Dug a really deep hole';
		tempEAction.SEW_Event__c = tempEvent.Id;
        tempEAction.Publish_status__c = 'Published';
        
        insert tempEAction;
        
        //Event_Type_Settings__c
        Event_Type_Settings__c etSetting = new Event_Type_Settings__c();
        etSetting.Name = 'Discoloured water';
        etSetting.Public_Name__c = 'Discoloured water';
        etSetting.Event_Colour__c = 'EB6419';
        etSetting.Icon_Static_Resource_Name__c = 'image';
        etSetting.Resolved_Icon_Static_Resource__c = 'image';

        etSetting.Active__c = true;
        
        insert etSetting;
        
        etSetting = new Event_Type_Settings__c();
        etSetting.Name = 'Emergency works';
        etSetting.Public_Name__c = 'Emergency works';
        etSetting.Event_Colour__c = 'C50046';
        etSetting.Icon_Static_Resource_Name__c = 'image';
        etSetting.Active__c = true;
        etSetting.Resolved_Icon_Static_Resource__c = 'image';

        insert etSetting;
        
        etSetting = new Event_Type_Settings__c();
        etSetting.Name = 'Scheduled works';
        etSetting.Public_Name__c = 'Scheduled works';
        etSetting.Event_Colour__c = '4FA52F';
        etSetting.Icon_Static_Resource_Name__c = 'image';
        etSetting.Active__c = true;
        etSetting.Resolved_Icon_Static_Resource__c = 'image';
        
        insert etSetting;

        SystemSettings__c sysSet = new SystemSettings__c();
        sysSet.Map_location_search_distance__c = 5;

        insert sysSet;
    }

    //method to test oomponent in pagelayout view
    static testMethod void testScenarioINpagelayout(){
        createTestData();

        test.startTest();
            SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.setisSingleLocation(tempEvent.Id);
        test.stopTest();
        system.assertEquals(controller.locationList.size() > 0, true);  //assert that there is an event to display
    }

    //method to test oomponent in pagelayout view without planned start and end time
    static testMethod void testScenarioINpagelayoutNEGATIVE(){
        createTestData();

        //tempEvent.Planned_Start_Time__c = null;
        //tempEvent.Planned_End_Time__c = null;

       // update tempEvent;

        test.startTest();
            SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.getisSingleLocation();
            controller.setisSingleLocation(tempEvent.Id);
        test.stopTest();
        system.assertEquals(controller.locationList.size() > 0, true);  //assert that there is an event to display
    }

    //method to test oomponent in vf page view(all events)
    static testMethod void testScenarioINvfpage(){
        createTestData();

        test.startTest();
            SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.setisSingleLocation(null);
        test.stopTest();
        //system.assertEquals(controller.locationList.size() > 0, false);  //assert that there is an event to display
    }

    //method to test oomponent in vf public site view(all events)
    static testMethod void testScenarioINpublicSite(){
        createTestData();

        test.startTest();
            SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.setisPublicSite('true');
            controller.getisPublicSite();
            controller.queryPublishedLocations();
        test.stopTest();
            system.assertEquals(controller.locationList.size() > 0, true); //assert that there is no event to display
    }

    //method to test oomponent in vf public site view(Planned filter)
    static testMethod void testScenarioINpublicSitePlannedOnly(){
        createTestData();

        test.startTest();
            SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.setisPublicSite('true');
            controller.getisPublicSite();
            controller.queryPublishedLocations();
        test.stopTest();
            system.assertEquals(controller.locationList.size() > 0, true); //assert that there is no event to display
    }

    //method to test oomponent in vf public site view(Unplanned filter)
    static testMethod void testScenarioINpublicSiteUnplannedOnly(){
        createTestData();

        test.startTest();
            SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.setisPublicSite('true');
            controller.getisPublicSite();
            controller.queryPublishedLocations();
        test.stopTest();
            system.assertEquals(controller.locationList.size() > 0, true); //assert that there is no event to display
    }

    //method to test oomponent in pagelayout view without planned start and end time
    static testMethod void testWrapperMethods(){
        createTestData();

        test.startTest();
        	SEWEventsLocationController controller = new SEWEventsLocationController();
            controller.setisPublicSite('true');
        	controller.queryPublishedLocations();
        test.stopTest();
        
        system.assertEquals(1,controller.locList.size());
        //system.assertEquals('This is messageNewLine',controller.locList[0].getMessageHtmlAsSingleLine());
        system.assertEquals(false, controller.locList[0].getDisplayResolution());
        //system.assert(controller.locList[0].getInfoBoxText().length() > 0);
    }
    
}