sample/retrieveUnpackaged/objects/Event_Action__c.object
<CustomObject>
    <fields>
        <fullName>Alternative_Water_Supply__c</fullName>
        <label>Alternative Water Supply</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chatter_Post_Id__c</fullName>
        <label>Chatter Post Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>The message in plain text.</description>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Public_Type__c</fullName>
        <label>Public Type</label>
        <picklist>
            <picklistValues>
                <fullName>Emergency works</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled works</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publish_status__c</fullName>
        <label>Publish status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Rich_Text_Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>SEW_Event__c</fullName>
        <label>SEW Event</label>
        <referenceTo>SEW_Event__c</referenceTo>
        <relationshipLabel>Event Actions</relationshipLabel>
        <relationshipName>Event_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Action</label>
    <nameField>
        <displayFormat>EA-{000000}</displayFormat>
        <label>Event Action Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Actions</pluralLabel>
    <recordTypes>
        <fullName>Internet</fullName>
        <active>true</active>
        <label>Internet</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/SEW_Event__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Status__c</fullName>
        <label>Public status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Resolution__c</fullName>
        <label>Resolution</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>SEW Event</label>
    <nameField>
        <label>Event Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SEW Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/SEWEventActionsUtilTest.cls
/*
    Author: Eugene Jandusay
    Company: Cloud Sherpas 
    Description: Test class for SEWEventActionsUtil
    History
    16/04/2014 Eugene Jandusay Created
    24/04/2014 Eugene Jandusay removed test cases for updateParent method
    13/06/2014 Eugene Jandusay added test cases

*/
@isTest(seeAllData = true)
private class SEWEventActionsUtilTest {
private static SEW_Event__c tempEvent;
private static Event_Action__c tempEventAction;
static Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Event_Action__c;
static Map<String,Schema.RecordTypeInfo> EventRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();

	static testMethod void createTestData() {
		//create event
	    tempEvent = new SEW_Event__c();
		//tempEvent.Event_Type__c = 'Repair of burst in roadway';
		tempEvent.Street_Number__c = '20';
		tempEvent.Street_Name__c = 'Corporate Drive';
		tempEvent.City__c = 'Heatherton';
		tempEvent.Class__c = 'Water Quality';
		tempEvent.Public_Status__c = 'In Progress';

		insert tempEvent;

		//create event action
		tempEventAction = new Event_Action__c();
		Id recTypeInternet= EventRecordTypeInfo .get('Internet').getRecordTypeId();
		tempEventAction.RecordTypeId = recTypeInternet;
		tempEventAction.SEW_Event__c = tempEvent.Id;
		tempEventAction.Publish_Status__c = 'Published';
		tempEventAction.Message__c = 'test';
		tempEventAction.Public_Type__c = 'Emergency works';

		insert tempEventAction;

		
	}

	static testMethod void createData(){

		createTestData();

		/*Feeditem currentFeedItem = [Select Id,ParentId FROM Feeditem WHERE ParentId =: tempEvent.Id];
		Event_Action__c currentEvent = [Select Chatter_Post_Id__c FROM Event_Action__c WHERE SEW_Event__c =:tempEvent.Id];
		system.assertEquals(currentEvent.Chatter_Post_Id__c,currentFeedItem.Id);*/
	}
	static testMethod void createTestDataUpdateStatus() {
		
		createTestData();

		tempEventAction.Publish_Status__c = 'Closed';

		update tempEventAction;

		/*Feeditem currentFeedItem = [Select Id,ParentId FROM Feeditem WHERE ParentId =: tempEvent.Id];
		Event_Action__c currentEvent = [Select Chatter_Post_Id__c FROM Event_Action__c WHERE SEW_Event__c =:tempEvent.Id];
		List<FeedComment> currentFeedComment= [Select ParentId,CommentBody FROM FeedComment WHERE FeedItemId =: currentFeedItem.Id];
		System.assert(currentFeedComment[0].CommentBody.length() > 0 );*/

	}

	static testMethod void createTestDataUpdate() {
		
		createTestData();

		tempEventAction.Rich_Text_Message__c = 'test';
		tempEventAction.Message__c = 'test';
		tempEventAction.Alternative_Water_Supply__c = 'test';
		tempEventAction.Resolution__c = 'test';
		tempEventAction.Public_Type__c = 'Scheduled works';

		update tempEventAction;

		/*Feeditem currentFeedItem = [Select Id,ParentId FROM Feeditem WHERE ParentId =: tempEvent.Id];
		Event_Action__c currentEvent = [Select Chatter_Post_Id__c FROM Event_Action__c WHERE SEW_Event__c =:tempEvent.Id];
		List<FeedComment> currentFeedComment= [Select ParentId,CommentBody FROM FeedComment WHERE FeedItemId =: currentFeedItem.Id ];
		System.assert(currentFeedComment[0].CommentBody.length() > 0 );*/

	}
}