sample/retrieveUnpackaged/objects/Financial_Hardship__c.object
<CustomObject>
    <description>Financial Hardship Stream

Represents Financial Hardship information for customers</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Signifies that the Financial Hardship Program is Active for the Customer</inlineHelpText>
        <label>Program Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hardship_Status__c</fullName>
        <inlineHelpText>Represents the level of financial hardship status for the related customer</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Gold</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Silver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Review_Action__c</fullName>
        <inlineHelpText>TO BE DEFINED</inlineHelpText>
        <label>Next Review Action</label>
        <picklist>
            <picklistValues>
                <fullName>Check URGS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Centrepay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Payment Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Plumbing Assistance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Negotiated Agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bronze Exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check Water usage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Send URGS Application</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Review_Date__c</fullName>
        <defaultValue>TODAY() + 56</defaultValue>
        <inlineHelpText>The next review date. Defaulted to eight weeks from today, however SAO&apos;s can change this (except for setting it to a past date on creation).</inlineHelpText>
        <label>Next Review Date</label>
        <type>Date</type>
    </fields>
    <label>Financial Hardship</label>
    <nameField>
        <displayFormat>FHA-{000000}</displayFormat>
        <label>Hardship Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Hardship</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/FinancialHardshipBatchJob.cls
/*
    Author: Eugene Jandusay
    Company: Cloud Sherpas 
    Description: (US-491 )Batch job for US-491 which automatically converts Silver to Bronze.
    History
    01/07/2014 Eugene Jandusay Created

*/
global class FinancialHardshipBatchJob implements Database.Batchable<sObject> {

     //Variable declarations
    global final String query;
    List<Financial_Hardship__c> updateFinancialHardshipsList = new List<Financial_Hardship__c>();
    
    //Query Lease records
    global FinancialHardshipBatchJob() {
       //query all records found matching the criteria in US-491 
       
       query = 'Select Hardship_Status__c,Next_Review_Action__c,Next_Review_Date__c FROM Financial_Hardship__c ' +
       			 'WHERE Hardship_Status__c =\'Silver\' ' + 
       			 'AND Next_Review_Action__c =\'Silver Review\' ' +
       			 'AND Next_Review_Date__c <= TODAY ' +
       			 'AND Active__c = true';
       	system.debug('!!!query: '+query);		 
    }
    
    //This method get the records passed from PipelineAutomationInsertOppBatch() method
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    //Execute method
    global void execute(Database.BatchableContext BC,List<Financial_Hardship__c> scope) {
		try{
			//update all records found         
	        for(Financial_Hardship__c fh : scope){
	        	system.debug('!!!enter');
	        	fh.Hardship_Status__c = 'Bronze';
	        	fh.Next_Review_Action__c = 'Bronze Exit';
	        	fh.Next_Review_Date__c = date.today().addMonths(6);
	        	
	        	updateFinancialHardshipsList.add(fh);
	        }
	        
	        if(updateFinancialHardshipsList.size() > 0){
	        	update updateFinancialHardshipsList;
	        }
		}catch(exception e){
			system.debug('There was an error with the batch process: '+ e);
		}
		
    }
    //Finish method
    global void finish(Database.BatchableContext BC){}

}