sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Meter_Location__c</fullName>
        <description>Shows the meter location on the house in an image form</description>
        <formula>IF(Location_Code__c == &quot;99&quot;, &quot;No Meter&quot;,
IMAGE(  &quot;https://southeastwater--c.ap1.content.force.com&quot; +
CASE(  LEFT(Location_Code__c , 1),
&quot;0&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mB4&quot;, 
&quot;1&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAo&quot;,
&quot;2&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAt&quot;,
&quot;3&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAy&quot;,
&quot;4&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mAu&quot;,
&quot;5&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mB3&quot;,
&quot;6&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mB8&quot;,
&quot;7&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mBD&quot;,
&quot;8&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mBI&quot;,
&quot;9&quot;, &quot;/servlet/servlet.ImageServer?id=015900000002mBN&quot;,
&quot;/servlet/servlet.ImageServer?id=015900000003GOp&quot;) + &quot;&amp;oid=00DO0000000W4pz&quot; 
, &quot;Meter Image&quot;))</formula>
        <label>Meter Location</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meter_Type__c</fullName>
        <label>Meter Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pit_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Pit Reference</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WS_RetrieveMeterReadingHistory.cls
/*
    Type:       Webservice extension class
    Purpose:    Process the Retrieve Meter Read History for a Billing Account request from the Webservice call

    Used By:    CustomerWebService_1_0.class
    ---------------------------------------------------------------
    History:
    16-May-13   N.Patterson         Created
    16-Aug-2013 N.Patterson			TT10401 - made class without sharing
    
*/
public without sharing class WS_RetrieveMeterReadingHistory {
	public static List<CustomerWebService_1_0.MeterReading> retrieveMeterReadingHistory(String hiAffinityNumberWithCheckDigit, String meterSerialNumber) { 
		System.debug(System.LoggingLevel.DEBUG, 'WS_RetrieveMeterReadingHistory.retrieveMeterReadingHistory(hiAffinityNumberWithCheckDigit,meterSerialNumber): ' + hiAffinityNumberWithCheckDigit + ',' + meterSerialNumber);
		List<CustomerWebService_1_0.MeterReading> resultList = new List<CustomerWebService_1_0.MeterReading>(); 
		if (meterSerialNumber != null && HiAffinityNumberWithCheckDigit != null) {
			
			List<Meter_Details__c> mdList = [SELECT Id, Name, Meter_Location__c, Pit_Reference__c, Meter_Type__c  
            									FROM Meter_Details__c  
            									WHERE Name = :meterSerialNumber];
            									
			if (!mdList.isEmpty()){
				try {
		            ApexPages.StandardController sc = new ApexPages.StandardController(mdList[0]);
		
		            MeterReadingsHistoryExCon meterCon = new MeterReadingsHistoryExCon(sc);
		            List<WSUtil_Property.MeterReading> meterReads = meterCon.RetrieveMeterReadings(mdList[0].Meter_Type__c, 
		            																				mdList[0].Pit_Reference__c, 
		            																				HiAffinityNumberWithCheckDigit.substring(0,HiAffinityNumberWithCheckDigit.length()-1));            
		            for (WSUtil_Property.MeterReading meter : meterReads) {
		            	resultList.add(new CustomerWebService_1_0.MeterReading(meter));
		            }
				}
	            catch (Exception e){
	            	System.debug(System.LoggingLevel.ERROR, 'WS_RetrieveMeterReadingHistory.retrieveMeterReadingHistory: Error retrieving meter reads.\n' + e.getMessage() + '\n' + e.getStackTraceString());
	            } 
			}
			else {
				System.debug(System.LoggingLevel.ERROR, 'WS_RetrieveMeterReadingHistory.retrieveMeterReadingHistory: Error retrieving the meter details for ' + meterSerialNumber);
			}
        }
        else {
        	System.debug(System.LoggingLevel.ERROR, 'WS_RetrieveMeterReadingHistory.retrieveMeterReadingHistory: HiAffinityNumberWithCheckDigit and meterSerialNumber must be supplied');
        } 
        return resultList;
	}
}