sample/retrieveUnpackaged/objects/Meter_Details__c.object
<CustomObject>
    <fields>
        <fullName>Meter_Type__c</fullName>
        <label>Meter Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pit_Reference__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Pit Reference</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Meters</relationshipLabel>
        <relationshipName>Meter_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Meter</label>
    <nameField>
        <label>Meter Serial</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Universal_Id_c__c</fullName>
        <externalId>true</externalId>
        <label>Universal Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/MeterReadingsHistoryExCon_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class MeterReadingsHistoryExCon
    ---------------------------------------------------------------
    History:

    24-Feb-2014 ejandusay    Created
*/
@isTest
private class MeterReadingsHistoryExCon_Test {

    /* Test Method */
    public static testmethod void test_MeterReadingsHistoryExCon(){
        Property__c prop = new Property__c();
        prop.Universal_Id_c__c = 'sdgfsdgf';
        prop.Name = 'Test Property';
        insert prop;
        Meter_Details__c meterDetail = new Meter_Details__c(Property__c = prop.id, Meter_Type__c = 'Test', Pit_Reference__c='Test');
        insert meterDetail;
        Test.startTest();
        PageReference pageRef = Page.MeterReadingsHistory;
        ApexPages.StandardController sc = new ApexPages.StandardController(meterDetail);
        Test.setCurrentPage(pageRef);
        MeterReadingsHistoryExCon excon = new MeterReadingsHistoryExCon(sc);
        pageRef.getParameters().put('retURL','/'+meterDetail.id);
        System.assert(excon.meterReadings.size() > 0);
        System.assert(excon.retURL != null);
        excon.meterReadings = null;
        excon.isTestException = true;   
        try{
            List<WSUtil_Property.MeterReading> temp = excon.meterReadings;
            //System.assert(false);
        }catch (WSUtil.MultipleWebServiceBusinessException ex){}
        
        TibcoMeterRead_MessageTypes.ProcessInputData_element pid = new TibcoMeterRead_MessageTypes.ProcessInputData_element();
        TibcoMeterRead_MessageTypes.Meter_element  me = new TibcoMeterRead_MessageTypes.Meter_element ();
        TibcoMeterRead_MessageTypes.ErrorStatus_element ee  = new TibcoMeterRead_MessageTypes.ErrorStatus_element ();
        
    }
}