sample/retrieveUnpackaged/objects/Non_Residential_Tariff_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Non Residential Tariff Codes</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tariff__c</fullName>
        <label>Tariff</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PropertyDisplayPopupController.cls
/*
Author:        ICastillo
Company:       Cloud Sherpas
Description:   Extension Controller for non residential property message page
Test Class:    
History 
30/08/2012     Created 
 */

public with sharing class PropertyDisplayPopupController {
	public property__c property {get; set;}	
	public Boolean checkTariff {get; set;}	
	
	public PropertyDisplayPopupController(ApexPages.StandardController controller){
		
		this.property = (property__c) controller.getRecord();	
		checkTariff = false;
		Set<String> tariffCodes= new Set<String>();			
		
		// query the Non_Residential_Tariff_Codes__c in custom setting sto get the name
		for (Non_Residential_Tariff_Codes__c  Tariff : [Select name from Non_Residential_Tariff_Codes__c]){				
				
			tariffCodes.add(tariff.name);			
				
		}	
		
		system.debug('@tariffCodes'+tariffCodes);
		
		// loop the Service__c to get the Tariff__c and check if it exist in tariffCodes set
		for(Service__c p: [Select Tariff__c,Property__c from Service__c where Property__c =:property.Id]){
			system.debug('@(p.Tariff__c'+p.Tariff__c);
			if(tariffCodes.contains(p.Tariff__c))	{
				checkTariff= true;
				break;
			}
		}
		system.debug('@checkTariff'+checkTariff);		
		
	}
	
	
}