sample/retrieveUnpackaged/objects/Non_Residential_Tariff_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Non Residential Tariff Codes</label>
</CustomObject>

sample/retrieveUnpackaged/objects/Property__c.object
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/Service__c.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tariff__c</fullName>
        <label>Tariff</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/PropertyDisplayPopupControllerTest.cls
/*
 *  Author: ICastillo
 *  Description:Test class for PropertyDisplayPopupControlle Class
 *  -------------------------------------------------
 *  -------------------------------------------------
 *  HISTORY:
 *  30/08/2012  Created
 *  
 */

@isTest
public class PropertyDisplayPopupControllerTest {

    static testMethod void test(){
        
        // Insert a dummy Non_Residential_Tariff_Codes__c       
        Non_Residential_Tariff_Codes__c NonRes1 = new Non_Residential_Tariff_Codes__c(name='U03');
        insert NonRes1;
        
        Non_Residential_Tariff_Codes__c NonRes2 = new Non_Residential_Tariff_Codes__c(name='U04');
        insert NonRes2;
        
        Non_Residential_Tariff_Codes__c NonRes3 = new Non_Residential_Tariff_Codes__c(name='U05');
        insert NonRes3;
        
        Non_Residential_Tariff_Codes__c NonRes4 = new Non_Residential_Tariff_Codes__c(name='U06');
        insert NonRes4;
        
        Non_Residential_Tariff_Codes__c NonRes5 = new Non_Residential_Tariff_Codes__c(name='U018');
        insert NonRes5;
        
        Non_Residential_Tariff_Codes__c NonRes7 = new Non_Residential_Tariff_Codes__c(name='U021');
        insert NonRes7;
        
        List<Non_Residential_Tariff_Codes__c> NonResList = [Select name from Non_Residential_Tariff_Codes__c];        system.debug('@NonResList'+NonResList);
        
        
        
        // Insert a dummy Property
                
        Property__c prop1 = new Property__c(name='TestProp1');
        insert prop1;
        
        // Insert a dummy Service 
        
        Service__c service1 = new Service__c(name='TestService1', Property__c = prop1.Id, Tariff__c='U03');
        insert service1;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(prop1);
        
        PropertyDisplayPopupController prop = new PropertyDisplayPopupController(sc);
    }
}