sample/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Require_Portal_Password_Reset__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Applicable for portal users only. This is only set if the user is created by a CSO and not via self-registration.</inlineHelpText>
        <label>Require Portal Password Reset</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secret_Answer__c</fullName>
        <label>Secret Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret_Question__c</fullName>
        <label>Secret Question</label>
        <picklist>
            <picklistValues>
                <fullName>What is the name of your favourite pet?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What city or town where you born in?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What is your mother’s maiden name?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Who is your favourite historical figure?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What was the last school you attended?</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/SiteLoginController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class SiteLoginController
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class SiteLoginController_Test {

    private static testMethod void testSiteLoginController () {
        // Instantiate a new controller with all parameters in the page
        SiteLoginController controller = new SiteLoginController ();
        controller.username = 'test@salesforce.com';
        controller.password = '123456';
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];        
        //create a user
        User testUser = new User(LastName = 'test',
                                 Email = 'test@salesforce.com',
                                 Alias = 'tu',
                                 LocaleSidKey = 'en_AU',
                                 EmailEncodingKey = 'UTF-8',
                                 LanguageLocaleKey = 'en_US',
                                 TimeZoneSidKey = 'Australia/Sydney',       
                                 username = 'test@portal.sewl.com.au.cfg',
                                 Secret_Question__c = 'What is the name of your favorite pet?',
                                 Secret_Answer__c = 'dog',
                                 ProfileId = p.Id,
                                 Require_Portal_Password_Reset__c = true);
        insert testUser;
        System.debug('***testUser***' + testUser);
        
        User firstTimeUser = [SELECT username from User where Require_Portal_Password_Reset__c = true LIMIT 1];
        if(firstTimeUser!=Null){
            controller.username = firstTimeUser.username;
            controller.setLoginUser(firstTimeUser.username);
            controller.isFirstTime();
            System.assertEquals(controller.login(),null);
        }
        
        User normalUser = [SELECT username from User where Require_Portal_Password_Reset__c = false LIMIT 1];
        if(normalUser!=Null){
            controller.username = normalUser.username;
            controller.setLoginUser(normalUser.username);
            controller.isFirstTime();
            System.assertEquals(controller.login(),null);   
        }
        
        controller.username = 'test';
        controller.password = '123456';
        String name = 'test';
        controller.username = controller.convertUserName(name);
        controller.ForgotPwd();
        controller.ForgotUsername();
    }
}