sample/retrieveUnpackaged/objects/User.object
<CustomObject>
    <fields>
        <fullName>Secret_Answer__c</fullName>
        <label>Secret Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secret_Question__c</fullName>
        <label>Secret Question</label>
        <picklist>
            <picklistValues>
                <fullName>What is the name of your favourite pet?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What city or town where you born in?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What is your mother’s maiden name?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Who is your favourite historical figure?</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>What was the last school you attended?</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sample/retrieveUnpackaged/classes/SecretQuestionController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class SecretQuestionController
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class SecretQuestionController_Test {

    static testMethod void testSave() {
		User testUser;  
        // Modify the test to query for a portal user that exists in your org
        List<User> existingPortalUsers = [SELECT id, profileId, userRoleId, userType FROM User WHERE UserRoleId <> null AND UserType='CustomerSuccess'];

        if (existingPortalUsers.isEmpty()) {
            testUser = [select id, title, firstname, lastname, email, phone, mobilephone, fax, street, city, state, postalcode, country, userType
                                FROM User WHERE id =: UserInfo.getUserId()];
		} else {
            testUser = existingPortalUsers[0];
        }
        System.runAs(testUser) {
            SecretQuestionController controller = new SecretQuestionController(); 
            User myUser = controller.getUser();         
            controller.save();          
            myUser.Secret_Question__c = 'What is your favorite pet?';
            myUser.Secret_Answer__c = 'dog';
            controller.save();           
        }
	}
}