sample/retrieveUnpackaged/objects/WaterMAP__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <description>The customer who is actually responsible for paying usage charges to SEW</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAPs</relationshipLabel>
        <relationshipName>WaterMaps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WaterMAP</label>
    <nameField>
        <label>Water MAP #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WaterMAPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/objects/WaterMAP_Submission__c.object
<CustomObject>
    <description>xxxx</description>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Watermap__c</fullName>
        <label>Watermap</label>
        <referenceTo>WaterMAP__c</referenceTo>
        <relationshipLabel>WaterMAP Submissions</relationshipLabel>
        <relationshipName>WaterMAP_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WaterMAP Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaterMAP Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WaterMAPContentsSidebarController_Test.cls
/*
    Type:       Test class
    Purpose:    Tests the class WaterMAPContentsSidebarController
    ---------------------------------------------------------------
    History:

    25-Feb-2014 ejandusay    Created
*/
@isTest
private class WaterMAPContentsSidebarController_Test {

    public static testmethod void TestMe() {
        // create test data
        Account account = new Account();
        account.name = 'foo';
        insert account;

        Watermap__c waterMap = new Watermap__c();
        waterMap.Name = 'Test Me';
        waterMap.Customer__c = account.id;
        insert waterMap;

        Watermap_Submission__c waterMapSub = new Watermap_Submission__c();
        waterMapSub.Watermap__c = waterMap.id;
        insert waterMapSub;

        // start the test
        Test.startTest();
        WaterMAPContentsSidebarController controller = new WaterMAPContentsSidebarController();
        controller.waterMAPSubId = waterMapSub.id;
        Watermap_Submission__c newWaterMap = controller.waterMapSub;
        Test.stopTest();
    }
}