sample/retrieveUnpackaged/objects/WaterMAP_Submission__c.object
<CustomObject>
    <description>xxxx</description>
    <fields>
        <fullName>Action_Plan_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Action Plan Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Site_Info_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Company &amp; Site Info Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cover_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cover Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicators_Targets_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indicators &amp; Targets Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunities_to_Save_Water_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunities to Save Water Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by SEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WaterMAP Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaterMAP Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WaterMAP_Submit_Controller.cls
public with sharing class WaterMAP_Submit_Controller {
/*
    Type:       Controller Extension
    Purpose:    Controller to display the WMAP Submission

    Used By:    WaterMAP_Submit_Page VF Page
    ---------------------------------------------------------------
    History:

    30-May-2011 D Thong Created
    25-Feb-2014 ejandusay(Cloud Sherpas)	Moved test method in a separate test class

*/

    /* PUBLIC GETTERS/SETTERS */
    public WaterMAP_Submission__c waterMAPSub {get; set;}

    public Boolean submittable {
        // everything is complete except for review and the watermap is currently
        // in progress
        get {
            if (waterMAPSub.Action_Plan_Complete__c &&
                waterMAPSub.Company_Site_Info_Complete__c &&
                waterMAPSub.Cover_Complete__c &&
                waterMAPSub.Indicators_Targets_Complete__c &&
                waterMAPSub.Opportunities_to_Save_Water_Complete__c &&
                waterMAPSub.Status__c == 'In Progress') {

                return true;
            }
            return false;
        }
        private set;
    }

    public Boolean submitted {
        get {
            if (waterMAPSub.Status__c == 'Submitted for Approval' ||
                waterMAPSub.Status__c == 'Approved by SEW' ||
                waterMAPSub.Status__c == 'Ready for Review' ||
                waterMAPSub.Status__c == 'Review Completed') {

                return true;
            }
            return false;
        }
    }


    /* CONSTRUCTORS */
    public WaterMAP_Submit_Controller(ApexPages.StandardController controller) {
        waterMapSub = (WaterMAP_Submission__c) controller.getRecord();
    }

    /* PUBLIC METHODS */
    public PageReference Submit() {
        // change the owner to the KAM
        // set status to "Submitted for Approval"
        // set submitted date time to today
        try {
            WaterMAPUtil.SubmitWMAPSubmission(waterMAPSub);
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This WaterMAP has been submitted to your Key Account Manager for approval'));
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }

        return null;
    }

    public PageReference View() {
        return null;
    }

    public void NoOp() {}

    

}