sample/retrieveUnpackaged/objects/WaterMAP_Submission__c.object
<CustomObject>
    <description>xxxx</description>
    <fields>
        <fullName>Action_Plan_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Action Plan Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Company_Site_Info_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Company &amp; Site Info Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cover_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cover Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Indicators_Targets_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Indicators &amp; Targets Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunities_to_Save_Water_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunities to Save Water Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Review_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Review Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site_Address__c</fullName>
        <formula>Watermap__r.Site_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved by SEW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Water_Consumption_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Water Consumption Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>WaterMAP Submission</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WaterMAP Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sample/retrieveUnpackaged/classes/WaterMAPContentsSidebarController.cls
public with sharing class WaterMAPContentsSidebarController {

/*
    Type:       Component Controller
    Purpose:    Controller to display the sidebar of the watermap
                Returns the sections of the watermap that are complete
                as well as the property address

    Used By:    WaterMAPContentsSidebar Component
    ---------------------------------------------------------------
    History:

    02-Feb-2011 D.Thong (Salesforce)    Created
    25-Feb-2014 ejandusay(Cloud Sherpas)Moved test method in a separate test class

*/

    /* PUBLIC PROPERTIES */
    public Id waterMAPSubId { get; set; }

    public WaterMap_Submission__c waterMapSub {
        get {
            if (waterMAPSubId != null && waterMapSubRecord == null) {
                waterMapSubRecord = [select id, status__c, site_address__c, cover_complete__c,
                                  Action_Plan_Complete__c, Indicators_Targets_Complete__c,
                                  Opportunities_to_Save_Water_Complete__c, Review_Complete__c,
                                  Water_Consumption_Complete__c, Company_Site_Info_Complete__c
                                  from WaterMap_Submission__c
                                  where Id = :waterMAPSubId];
            }

            return waterMapSubRecord;

        }
        set;
    }

    /* PRIVATE PROPERTIES */
    private WaterMap_Submission__c waterMapSubRecord;

    
}